// Mailyard, Copyright (c) 2021-2026 YouSysAdmin

// Code generated by cmd/sdkgen. DO NOT EDIT.

package api

import (
	"context"
	"fmt"
)

// ListAdminApiKeys List platform credentials.
//
// GET /admin/api-keys
func (c *Client) ListAdminApiKeys(ctx context.Context, opts ...RequestOption) (AdminListResponse, error) {
	return do[AdminListResponse](ctx, c, "GET", "/admin/api-keys", nil, opts)
}

// CreateAdminApiKey Mint a platform credential.
//
// POST /admin/api-keys
func (c *Client) CreateAdminApiKey(ctx context.Context, body AdminCreateInput, opts ...RequestOption) (AdminCreatedResponse, error) {
	return do[AdminCreatedResponse](ctx, c, "POST", "/admin/api-keys", body, opts)
}

// DeleteAdminApiKey Delete a platform credential.
//
// DELETE /admin/api-keys/:id
func (c *Client) DeleteAdminApiKey(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/admin/api-keys/%s", escape(id)), nil, opts)
	return err
}

// RevokeAdminApiKey Revoke a platform credential.
//
// POST /admin/api-keys/:id/revoke
func (c *Client) RevokeAdminApiKey(ctx context.Context, id string, opts ...RequestOption) (AdminAPIKeyResponse, error) {
	return do[AdminAPIKeyResponse](ctx, c, "POST", fmt.Sprintf("/admin/api-keys/%s/revoke", escape(id)), nil, opts)
}

// ListAdminCertificates List managed certificates and listener assignments.
//
// GET /admin/certificates
func (c *Client) ListAdminCertificates(ctx context.Context, opts ...RequestOption) (ListResponse, error) {
	return do[ListResponse](ctx, c, "GET", "/admin/certificates", nil, opts)
}

// CreateAdminCertificate Upload a certificate and its private key.
//
// POST /admin/certificates
func (c *Client) CreateAdminCertificate(ctx context.Context, body UploadInput, opts ...RequestOption) (ManagedResponse, error) {
	return do[ManagedResponse](ctx, c, "POST", "/admin/certificates", body, opts)
}

// DeleteAdminCertificate Delete a managed certificate.
//
// DELETE /admin/certificates/:name
func (c *Client) DeleteAdminCertificate(ctx context.Context, name string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/admin/certificates/%s", escape(name)), nil, opts)
	return err
}

// GetAdminCertificatePem Read a certificate's public half.
//
// GET /admin/certificates/:name/pem
func (c *Client) GetAdminCertificatePem(ctx context.Context, name string, opts ...RequestOption) (PEMResponse, error) {
	return do[PEMResponse](ctx, c, "GET", fmt.Sprintf("/admin/certificates/%s/pem", escape(name)), nil, opts)
}

// GetAdminCertificatesAcme What ACME is configured to do, and what it holds.
//
// GET /admin/certificates/acme
func (c *Client) GetAdminCertificatesAcme(ctx context.Context, opts ...RequestOption) (ACMEResponse, error) {
	return do[ACMEResponse](ctx, c, "GET", "/admin/certificates/acme", nil, opts)
}

// AcmeOrderAdminCertificate Obtain a certificate for one configured host.
//
// POST /admin/certificates/acme/order
func (c *Client) AcmeOrderAdminCertificate(ctx context.Context, body RenewInput, opts ...RequestOption) (MessageResponse, error) {
	return do[MessageResponse](ctx, c, "POST", "/admin/certificates/acme/order", body, opts)
}

// AcmeRenewAdminCertificate Discard what is cached for a host and order again.
//
// POST /admin/certificates/acme/renew
func (c *Client) AcmeRenewAdminCertificate(ctx context.Context, body RenewInput, opts ...RequestOption) (MessageResponse, error) {
	return do[MessageResponse](ctx, c, "POST", "/admin/certificates/acme/renew", body, opts)
}

// GenerateAdminCertificate Generate a certificate for a listener.
//
// POST /admin/certificates/generate
func (c *Client) GenerateAdminCertificate(ctx context.Context, body GenerateInput, opts ...RequestOption) (ManagedResponse, error) {
	return do[ManagedResponse](ctx, c, "POST", "/admin/certificates/generate", body, opts)
}

// GenerateCaAdminCertificate Generate a certificate authority.
//
// POST /admin/certificates/generate-ca
func (c *Client) GenerateCaAdminCertificate(ctx context.Context, body GenerateCAInput, opts ...RequestOption) (ManagedResponse, error) {
	return do[ManagedResponse](ctx, c, "POST", "/admin/certificates/generate-ca", body, opts)
}

// GetAdminCertificatesSystem List the certificates the installation holds for itself.
//
// GET /admin/certificates/system
func (c *Client) GetAdminCertificatesSystem(ctx context.Context, opts ...RequestOption) (SystemResponse, error) {
	return do[SystemResponse](ctx, c, "GET", "/admin/certificates/system", nil, opts)
}

// ListAdminJobs Jobs.
//
// GET /admin/jobs
func (c *Client) ListAdminJobs(ctx context.Context, opts ...RequestOption) (JobsResponse, error) {
	return do[JobsResponse](ctx, c, "GET", "/admin/jobs", nil, opts)
}

// RunAdminJob Run job.
//
// POST /admin/jobs/:name/run
func (c *Client) RunAdminJob(ctx context.Context, name string, opts ...RequestOption) (JobsResponse, error) {
	return do[JobsResponse](ctx, c, "POST", fmt.Sprintf("/admin/jobs/%s/run", escape(name)), nil, opts)
}

// ListAdminOauthProviders List.
//
// GET /admin/oauth-providers/
func (c *Client) ListAdminOauthProviders(ctx context.Context, opts ...RequestOption) (OauthproviderListResponse, error) {
	return do[OauthproviderListResponse](ctx, c, "GET", "/admin/oauth-providers", nil, opts)
}

// CreateAdminOauthProvider Create.
//
// POST /admin/oauth-providers/
func (c *Client) CreateAdminOauthProvider(ctx context.Context, body UpsertInput, opts ...RequestOption) (ProviderResponse, error) {
	return do[ProviderResponse](ctx, c, "POST", "/admin/oauth-providers", body, opts)
}

// DeleteAdminOauthProvider Delete.
//
// DELETE /admin/oauth-providers/:id
func (c *Client) DeleteAdminOauthProvider(ctx context.Context, id string, opts ...RequestOption) (DeletedResponse, error) {
	return do[DeletedResponse](ctx, c, "DELETE", fmt.Sprintf("/admin/oauth-providers/%s", escape(id)), nil, opts)
}

// GetAdminOauthProvider Get.
//
// GET /admin/oauth-providers/:id
func (c *Client) GetAdminOauthProvider(ctx context.Context, id string, opts ...RequestOption) (ProviderResponse, error) {
	return do[ProviderResponse](ctx, c, "GET", fmt.Sprintf("/admin/oauth-providers/%s", escape(id)), nil, opts)
}

// UpdateAdminOauthProvider Update.
//
// PATCH /admin/oauth-providers/:id
func (c *Client) UpdateAdminOauthProvider(ctx context.Context, id string, body UpsertInput, opts ...RequestOption) (ProviderResponse, error) {
	return do[ProviderResponse](ctx, c, "PATCH", fmt.Sprintf("/admin/oauth-providers/%s", escape(id)), body, opts)
}

// TestAdminOauthProvider Test.
//
// POST /admin/oauth-providers/:id/test
func (c *Client) TestAdminOauthProvider(ctx context.Context, id string, opts ...RequestOption) (TestResponse, error) {
	return do[TestResponse](ctx, c, "POST", fmt.Sprintf("/admin/oauth-providers/%s/test", escape(id)), nil, opts)
}

// ListAdminPlans List.
//
// GET /admin/plans/
func (c *Client) ListAdminPlans(ctx context.Context, opts ...RequestOption) (PlanListResponse, error) {
	return do[PlanListResponse](ctx, c, "GET", "/admin/plans", nil, opts)
}

// CreateAdminPlan Create.
//
// POST /admin/plans/
func (c *Client) CreateAdminPlan(ctx context.Context, body PlanUpsertInput, opts ...RequestOption) (PlanResponse, error) {
	return do[PlanResponse](ctx, c, "POST", "/admin/plans", body, opts)
}

// DeleteAdminPlan Delete.
//
// DELETE /admin/plans/:id
func (c *Client) DeleteAdminPlan(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/admin/plans/%s", escape(id)), nil, opts)
	return err
}

// UpdateAdminPlan Update.
//
// PATCH /admin/plans/:id
func (c *Client) UpdateAdminPlan(ctx context.Context, id string, body PlanUpsertInput, opts ...RequestOption) (PlanResponse, error) {
	return do[PlanResponse](ctx, c, "PATCH", fmt.Sprintf("/admin/plans/%s", escape(id)), body, opts)
}

// UpdateAdminProjectPlan Assign.
//
// PATCH /admin/projects/:id/plan
func (c *Client) UpdateAdminProjectPlan(ctx context.Context, id string, body AssignInput, opts ...RequestOption) (AssignResponse, error) {
	return do[AssignResponse](ctx, c, "PATCH", fmt.Sprintf("/admin/projects/%s/plan", escape(id)), body, opts)
}

// ListAdminRelayNodes List.
//
// GET /admin/relay-nodes/
func (c *Client) ListAdminRelayNodes(ctx context.Context, opts ...RequestOption) (ListOutput, error) {
	return do[ListOutput](ctx, c, "GET", "/admin/relay-nodes", nil, opts)
}

// DeleteAdminRelayNode Delete.
//
// DELETE /admin/relay-nodes/:id
func (c *Client) DeleteAdminRelayNode(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/admin/relay-nodes/%s", escape(id)), nil, opts)
	return err
}

// ApproveAdminRelayNode Approve.
//
// POST /admin/relay-nodes/:id/approve
func (c *Client) ApproveAdminRelayNode(ctx context.Context, id string, opts ...RequestOption) (StatusResponse, error) {
	return do[StatusResponse](ctx, c, "POST", fmt.Sprintf("/admin/relay-nodes/%s/approve", escape(id)), nil, opts)
}

// SuspendAdminRelayNode Suspend.
//
// POST /admin/relay-nodes/:id/suspend
func (c *Client) SuspendAdminRelayNode(ctx context.Context, id string, opts ...RequestOption) (StatusResponse, error) {
	return do[StatusResponse](ctx, c, "POST", fmt.Sprintf("/admin/relay-nodes/%s/suspend", escape(id)), nil, opts)
}

// DeleteAdminRelayNodesAuthority Destroy the relay authority.
//
// DELETE /admin/relay-nodes/authority
func (c *Client) DeleteAdminRelayNodesAuthority(ctx context.Context, opts ...RequestOption) (ResetAuthorityResponse, error) {
	return do[ResetAuthorityResponse](ctx, c, "DELETE", "/admin/relay-nodes/authority", nil, opts)
}

// ListAdminSettings List.
//
// GET /admin/settings
func (c *Client) ListAdminSettings(ctx context.Context, opts ...RequestOption) (SettingListResponse, error) {
	return do[SettingListResponse](ctx, c, "GET", "/admin/settings", nil, opts)
}

// UpdateAdminSettings Update.
//
// PUT /admin/settings
func (c *Client) UpdateAdminSettings(ctx context.Context, body UpdateInput, opts ...RequestOption) (SettingListResponse, error) {
	return do[SettingListResponse](ctx, c, "PUT", "/admin/settings", body, opts)
}

// ListAdminSharedSmtpServers List.
//
// GET /admin/shared-smtp-servers/
func (c *Client) ListAdminSharedSmtpServers(ctx context.Context, opts ...RequestOption) (SharedListResponse, error) {
	return do[SharedListResponse](ctx, c, "GET", "/admin/shared-smtp-servers", nil, opts)
}

// CreateAdminSharedSmtpServer Create.
//
// POST /admin/shared-smtp-servers/
func (c *Client) CreateAdminSharedSmtpServer(ctx context.Context, body SharedCreateInput, opts ...RequestOption) (SharedResponse, error) {
	return do[SharedResponse](ctx, c, "POST", "/admin/shared-smtp-servers", body, opts)
}

// DeleteAdminSharedSmtpServer Delete.
//
// DELETE /admin/shared-smtp-servers/:id
func (c *Client) DeleteAdminSharedSmtpServer(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/admin/shared-smtp-servers/%s", escape(id)), nil, opts)
	return err
}

// GetAdminSharedSmtpServer Get.
//
// GET /admin/shared-smtp-servers/:id
func (c *Client) GetAdminSharedSmtpServer(ctx context.Context, id string, opts ...RequestOption) (SharedResponse, error) {
	return do[SharedResponse](ctx, c, "GET", fmt.Sprintf("/admin/shared-smtp-servers/%s", escape(id)), nil, opts)
}

// UpdateAdminSharedSmtpServer Update.
//
// PATCH /admin/shared-smtp-servers/:id
func (c *Client) UpdateAdminSharedSmtpServer(ctx context.Context, id string, body SharedUpdateInput, opts ...RequestOption) (SharedResponse, error) {
	return do[SharedResponse](ctx, c, "PATCH", fmt.Sprintf("/admin/shared-smtp-servers/%s", escape(id)), body, opts)
}

// TestAdminSharedSmtpServer Test.
//
// POST /admin/shared-smtp-servers/:id/test
func (c *Client) TestAdminSharedSmtpServer(ctx context.Context, id string, opts ...RequestOption) (SharedTestResponse, error) {
	return do[SharedTestResponse](ctx, c, "POST", fmt.Sprintf("/admin/shared-smtp-servers/%s/test", escape(id)), nil, opts)
}

// ListAdminSystemMail System mail status.
//
// GET /admin/system-mail
func (c *Client) ListAdminSystemMail(ctx context.Context, opts ...RequestOption) (SystemMailStatusResponse, error) {
	return do[SystemMailStatusResponse](ctx, c, "GET", "/admin/system-mail", nil, opts)
}

// TestAdminSystemMail System mail test.
//
// POST /admin/system-mail/test
func (c *Client) TestAdminSystemMail(ctx context.Context, body SystemMailTestInput, opts ...RequestOption) (AuthMessageResponse, error) {
	return do[AuthMessageResponse](ctx, c, "POST", "/admin/system-mail/test", body, opts)
}

// ListAdminUsers List.
//
// GET /admin/users/
func (c *Client) ListAdminUsers(ctx context.Context, opts ...RequestOption) (UserListResponse, error) {
	return do[UserListResponse](ctx, c, "GET", "/admin/users", nil, opts)
}

// CreateAdminUser Create.
//
// POST /admin/users/
func (c *Client) CreateAdminUser(ctx context.Context, body CreateInput, opts ...RequestOption) (UserResponse, error) {
	return do[UserResponse](ctx, c, "POST", "/admin/users", body, opts)
}

// DeleteAdminUser Delete.
//
// DELETE /admin/users/:id
func (c *Client) DeleteAdminUser(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/admin/users/%s", escape(id)), nil, opts)
	return err
}

// GetAdminUser Get.
//
// GET /admin/users/:id
func (c *Client) GetAdminUser(ctx context.Context, id string, opts ...RequestOption) (UserResponse, error) {
	return do[UserResponse](ctx, c, "GET", fmt.Sprintf("/admin/users/%s", escape(id)), nil, opts)
}

// UpdateAdminUser Update.
//
// PATCH /admin/users/:id
func (c *Client) UpdateAdminUser(ctx context.Context, id string, body UserUpdateInput, opts ...RequestOption) (UserResponse, error) {
	return do[UserResponse](ctx, c, "PATCH", fmt.Sprintf("/admin/users/%s", escape(id)), body, opts)
}

// DeleteAdminUser2fa Reset t o t p.
//
// DELETE /admin/users/:id/2fa
func (c *Client) DeleteAdminUser2fa(ctx context.Context, id string, opts ...RequestOption) (UserResponse, error) {
	return do[UserResponse](ctx, c, "DELETE", fmt.Sprintf("/admin/users/%s/2fa", escape(id)), nil, opts)
}

// DeleteAdminUserPasskey Reset passkeys.
//
// DELETE /admin/users/:id/passkeys
func (c *Client) DeleteAdminUserPasskey(ctx context.Context, id string, opts ...RequestOption) (PasskeyResetResponse, error) {
	return do[PasskeyResetResponse](ctx, c, "DELETE", fmt.Sprintf("/admin/users/%s/passkeys", escape(id)), nil, opts)
}

// ListAdminUserProjects Projects.
//
// GET /admin/users/:id/projects
func (c *Client) ListAdminUserProjects(ctx context.Context, id string, opts ...RequestOption) (ProjectsResponse, error) {
	return do[ProjectsResponse](ctx, c, "GET", fmt.Sprintf("/admin/users/%s/projects", escape(id)), nil, opts)
}

// CreateAdminUserRevokeSession Revoke sessions.
//
// POST /admin/users/:id/revoke-sessions
func (c *Client) CreateAdminUserRevokeSession(ctx context.Context, id string, opts ...RequestOption) (RevokedResponse, error) {
	return do[RevokedResponse](ctx, c, "POST", fmt.Sprintf("/admin/users/%s/revoke-sessions", escape(id)), nil, opts)
}

// ListAnalytics Daily delivery trend and status breakdown.
//
// GET /analytics
func (c *Client) ListAnalytics(ctx context.Context, opts ...RequestOption) (TrendResponse, error) {
	return do[TrendResponse](ctx, c, "GET", "/analytics", nil, opts)
}

// ListApiKeys List.
//
// GET /api-keys/
func (c *Client) ListApiKeys(ctx context.Context, opts ...RequestOption) (ApikeyListResponse, error) {
	return do[ApikeyListResponse](ctx, c, "GET", "/api-keys", nil, opts)
}

// CreateApiKey Create.
//
// POST /api-keys/
func (c *Client) CreateApiKey(ctx context.Context, body ApikeyCreateInput, opts ...RequestOption) (CreatedResponse, error) {
	return do[CreatedResponse](ctx, c, "POST", "/api-keys", body, opts)
}

// DeleteApiKey Delete.
//
// DELETE /api-keys/:id
func (c *Client) DeleteApiKey(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/api-keys/%s", escape(id)), nil, opts)
	return err
}

// RevokeApiKey Revoke.
//
// POST /api-keys/:id/revoke
func (c *Client) RevokeApiKey(ctx context.Context, id string, opts ...RequestOption) (APIKeyResponse, error) {
	return do[APIKeyResponse](ctx, c, "POST", fmt.Sprintf("/api-keys/%s/revoke", escape(id)), nil, opts)
}

// ListAuditLog Project log.
//
// GET /audit-log
func (c *Client) ListAuditLog(ctx context.Context, opts ...RequestOption) (AuditListResponse, error) {
	return do[AuditListResponse](ctx, c, "GET", "/audit-log", nil, opts)
}

// GetAuditLog Project event.
//
// GET /audit-log/:id
func (c *Client) GetAuditLog(ctx context.Context, id string, opts ...RequestOption) (EventResponse, error) {
	return do[EventResponse](ctx, c, "GET", fmt.Sprintf("/audit-log/%s", escape(id)), nil, opts)
}

// GetAuditLogExport Export the project log.
//
// GET /audit-log/export
func (c *Client) GetAuditLogExport(ctx context.Context, opts ...RequestOption) (ExportResponse, error) {
	return do[ExportResponse](ctx, c, "GET", "/audit-log/export", nil, opts)
}

// DeleteBounces Delete the bounce reports for an address.
//
// DELETE /bounces
func (c *Client) DeleteBounces(ctx context.Context, opts ...RequestOption) (DeleteResponse, error) {
	return do[DeleteResponse](ctx, c, "DELETE", "/bounces", nil, opts)
}

// ListBounces List bounce reports.
//
// GET /bounces
func (c *Client) ListBounces(ctx context.Context, opts ...RequestOption) (BounceListResponse, error) {
	return do[BounceListResponse](ctx, c, "GET", "/bounces", nil, opts)
}

// ListCampaigns List.
//
// GET /campaigns/
func (c *Client) ListCampaigns(ctx context.Context, opts ...RequestOption) (CampaignListResponse, error) {
	return do[CampaignListResponse](ctx, c, "GET", "/campaigns", nil, opts)
}

// CreateCampaign Create.
//
// POST /campaigns/
func (c *Client) CreateCampaign(ctx context.Context, body CampaignUpsertInput, opts ...RequestOption) (CampaignResponse, error) {
	return do[CampaignResponse](ctx, c, "POST", "/campaigns", body, opts)
}

// DeleteCampaign Delete.
//
// DELETE /campaigns/:id
func (c *Client) DeleteCampaign(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/campaigns/%s", escape(id)), nil, opts)
	return err
}

// GetCampaign Get.
//
// GET /campaigns/:id
func (c *Client) GetCampaign(ctx context.Context, id string, opts ...RequestOption) (CampaignDetailResponse, error) {
	return do[CampaignDetailResponse](ctx, c, "GET", fmt.Sprintf("/campaigns/%s", escape(id)), nil, opts)
}

// UpdateCampaign Update.
//
// PATCH /campaigns/:id
func (c *Client) UpdateCampaign(ctx context.Context, id string, body CampaignUpsertInput, opts ...RequestOption) (CampaignResponse, error) {
	return do[CampaignResponse](ctx, c, "PATCH", fmt.Sprintf("/campaigns/%s", escape(id)), body, opts)
}

// ListCampaignAnalytics Analytics.
//
// GET /campaigns/:id/analytics
func (c *Client) ListCampaignAnalytics(ctx context.Context, id string, opts ...RequestOption) (AnalyticsResponse, error) {
	return do[AnalyticsResponse](ctx, c, "GET", fmt.Sprintf("/campaigns/%s/analytics", escape(id)), nil, opts)
}

// CancelCampaign Cancel.
//
// POST /campaigns/:id/cancel
func (c *Client) CancelCampaign(ctx context.Context, id string, opts ...RequestOption) (CampaignResponse, error) {
	return do[CampaignResponse](ctx, c, "POST", fmt.Sprintf("/campaigns/%s/cancel", escape(id)), nil, opts)
}

// DuplicateCampaign Duplicate.
//
// POST /campaigns/:id/duplicate
func (c *Client) DuplicateCampaign(ctx context.Context, id string, opts ...RequestOption) (CampaignResponse, error) {
	return do[CampaignResponse](ctx, c, "POST", fmt.Sprintf("/campaigns/%s/duplicate", escape(id)), nil, opts)
}

// ListCampaignMessages Messages.
//
// GET /campaigns/:id/messages
func (c *Client) ListCampaignMessages(ctx context.Context, id string, opts ...RequestOption) (MessageListResponse, error) {
	return do[MessageListResponse](ctx, c, "GET", fmt.Sprintf("/campaigns/%s/messages", escape(id)), nil, opts)
}

// PauseCampaign Pause.
//
// POST /campaigns/:id/pause
func (c *Client) PauseCampaign(ctx context.Context, id string, opts ...RequestOption) (CampaignResponse, error) {
	return do[CampaignResponse](ctx, c, "POST", fmt.Sprintf("/campaigns/%s/pause", escape(id)), nil, opts)
}

// ResumeCampaign Resume.
//
// POST /campaigns/:id/resume
func (c *Client) ResumeCampaign(ctx context.Context, id string, opts ...RequestOption) (CampaignResponse, error) {
	return do[CampaignResponse](ctx, c, "POST", fmt.Sprintf("/campaigns/%s/resume", escape(id)), nil, opts)
}

// SendCampaign Send.
//
// POST /campaigns/:id/send
func (c *Client) SendCampaign(ctx context.Context, id string, body SendInput, opts ...RequestOption) (CampaignResponse, error) {
	return do[CampaignResponse](ctx, c, "POST", fmt.Sprintf("/campaigns/%s/send", escape(id)), body, opts)
}

// ListContacts Addresses this project has delivered to.
//
// GET /contacts
func (c *Client) ListContacts(ctx context.Context, opts ...RequestOption) (ContactListResponse, error) {
	return do[ContactListResponse](ctx, c, "GET", "/contacts", nil, opts)
}

// GetContact One contact.
//
// GET /contacts/:id
func (c *Client) GetContact(ctx context.Context, id string, opts ...RequestOption) (GetResponse, error) {
	return do[GetResponse](ctx, c, "GET", fmt.Sprintf("/contacts/%s", escape(id)), nil, opts)
}

// ListDashboardStats Aggregate counts for a dashboard.
//
// GET /dashboard/stats
func (c *Client) ListDashboardStats(ctx context.Context, opts ...RequestOption) (StatsResponse, error) {
	return do[StatsResponse](ctx, c, "GET", "/dashboard/stats", nil, opts)
}

// CreateDataDeleteContact Delete contacts.
//
// POST /data/delete-contacts
func (c *Client) CreateDataDeleteContact(ctx context.Context, body DeleteContactsInput, opts ...RequestOption) (ErasureResponse, error) {
	return do[ErasureResponse](ctx, c, "POST", "/data/delete-contacts", body, opts)
}

// CreateDataDeleteEmailLog Delete email logs.
//
// POST /data/delete-email-logs
func (c *Client) CreateDataDeleteEmailLog(ctx context.Context, body DeleteLogsInput, opts ...RequestOption) (ErasureResponse, error) {
	return do[ErasureResponse](ctx, c, "POST", "/data/delete-email-logs", body, opts)
}

// GetDataExport Export every record of the key's project.
//
// GET /data/export
func (c *Client) GetDataExport(ctx context.Context, opts ...RequestOption) (DataExportResponse, error) {
	return do[DataExportResponse](ctx, c, "GET", "/data/export", nil, opts)
}

// ListDomains List.
//
// GET /domains/
func (c *Client) ListDomains(ctx context.Context, opts ...RequestOption) (DomainsListResponse, error) {
	return do[DomainsListResponse](ctx, c, "GET", "/domains", nil, opts)
}

// CreateDomain Create.
//
// POST /domains/
func (c *Client) CreateDomain(ctx context.Context, body DomainsCreateInput, opts ...RequestOption) (DetailResponse, error) {
	return do[DetailResponse](ctx, c, "POST", "/domains", body, opts)
}

// DeleteDomain Delete.
//
// DELETE /domains/:id
func (c *Client) DeleteDomain(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/domains/%s", escape(id)), nil, opts)
	return err
}

// GetDomain Get.
//
// GET /domains/:id
func (c *Client) GetDomain(ctx context.Context, id string, opts ...RequestOption) (DetailResponse, error) {
	return do[DetailResponse](ctx, c, "GET", fmt.Sprintf("/domains/%s", escape(id)), nil, opts)
}

// VerifyDomain Verify.
//
// POST /domains/:id/verify
func (c *Client) VerifyDomain(ctx context.Context, id string, opts ...RequestOption) (DetailResponse, error) {
	return do[DetailResponse](ctx, c, "POST", fmt.Sprintf("/domains/%s/verify", escape(id)), nil, opts)
}

// ListEmails List sent and queued emails.
//
// GET /emails
func (c *Client) ListEmails(ctx context.Context, opts ...RequestOption) (EmailListResponse, error) {
	return do[EmailListResponse](ctx, c, "GET", "/emails", nil, opts)
}

// GetEmail One email with its full delivery record.
//
// GET /emails/:id
func (c *Client) GetEmail(ctx context.Context, id string, opts ...RequestOption) (EmailResponse, error) {
	return do[EmailResponse](ctx, c, "GET", fmt.Sprintf("/emails/%s", escape(id)), nil, opts)
}

// GetEmailAttachment Attachment.
//
// GET /emails/:id/attachments/:idx
func (c *Client) GetEmailAttachment(ctx context.Context, id string, idx string, opts ...RequestOption) ([]byte, error) {
	return doRaw(ctx, c, "GET", fmt.Sprintf("/emails/%s/attachments/%s", escape(id), escape(idx)), opts)
}

// RetryEmail Requeue a failed email.
//
// POST /emails/:id/retry
func (c *Client) RetryEmail(ctx context.Context, id string, opts ...RequestOption) (EmailResponse, error) {
	return do[EmailResponse](ctx, c, "POST", fmt.Sprintf("/emails/%s/retry", escape(id)), nil, opts)
}

// ListEmailStatus Delivery status only.
//
// GET /emails/:id/status
func (c *Client) ListEmailStatus(ctx context.Context, id string, opts ...RequestOption) (EmailStatusResponse, error) {
	return do[EmailStatusResponse](ctx, c, "GET", fmt.Sprintf("/emails/%s/status", escape(id)), nil, opts)
}

// ListEmailTrackedLinks Original destinations behind the click redirects.
//
// GET /emails/:id/tracked-links
func (c *Client) ListEmailTrackedLinks(ctx context.Context, id string, opts ...RequestOption) (TrackedLinksResponse, error) {
	return do[TrackedLinksResponse](ctx, c, "GET", fmt.Sprintf("/emails/%s/tracked-links", escape(id)), nil, opts)
}

// BatchEmail Queue up to 100 emails in one call.
//
// POST /emails/batch
func (c *Client) BatchEmail(ctx context.Context, body BatchInput, opts ...RequestOption) (BatchResponse, error) {
	return do[BatchResponse](ctx, c, "POST", "/emails/batch", body, opts)
}

// ListEmailsLimits What a send may carry on this installation.
//
// GET /emails/limits
func (c *Client) ListEmailsLimits(ctx context.Context, opts ...RequestOption) (LimitsResponse, error) {
	return do[LimitsResponse](ctx, c, "GET", "/emails/limits", nil, opts)
}

// PreviewEmail Render a template without sending.
//
// POST /emails/preview
func (c *Client) PreviewEmail(ctx context.Context, body RenderPreviewInput, opts ...RequestOption) (PreviewResponse, error) {
	return do[PreviewResponse](ctx, c, "POST", "/emails/preview", body, opts)
}

// SendEmail Queue one email.
//
// POST /emails/send
func (c *Client) SendEmail(ctx context.Context, body EmailSendInput, opts ...RequestOption) (SendResponse, error) {
	return do[SendResponse](ctx, c, "POST", "/emails/send", body, opts)
}

// SendTemplateEmail Render a stored template and queue the result.
//
// POST /emails/send-template
func (c *Client) SendTemplateEmail(ctx context.Context, body TemplateSendInput, opts ...RequestOption) (SendResponse, error) {
	return do[SendResponse](ctx, c, "POST", "/emails/send-template", body, opts)
}

// ListEmailsStats Count emails by delivery status.
//
// GET /emails/stats
func (c *Client) ListEmailsStats(ctx context.Context, opts ...RequestOption) (EmailStatsResponse, error) {
	return do[EmailStatsResponse](ctx, c, "GET", "/emails/stats", nil, opts)
}

// VerifyEmail Judge whether an address is worth sending to.
//
// POST /emails/verify
func (c *Client) VerifyEmail(ctx context.Context, body VerifyInput, opts ...RequestOption) (VerifyResponse, error) {
	return do[VerifyResponse](ctx, c, "POST", "/emails/verify", body, opts)
}

// ListInboundEmails List mail received by the MX listener.
//
// GET /inbound-emails
func (c *Client) ListInboundEmails(ctx context.Context, opts ...RequestOption) (InboundListResponse, error) {
	return do[InboundListResponse](ctx, c, "GET", "/inbound-emails", nil, opts)
}

// DeleteInboundEmail Delete.
//
// DELETE /inbound-emails/:id
func (c *Client) DeleteInboundEmail(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/inbound-emails/%s", escape(id)), nil, opts)
	return err
}

// GetInboundEmail One received message.
//
// GET /inbound-emails/:id
func (c *Client) GetInboundEmail(ctx context.Context, id string, opts ...RequestOption) (InboundGetResponse, error) {
	return do[InboundGetResponse](ctx, c, "GET", fmt.Sprintf("/inbound-emails/%s", escape(id)), nil, opts)
}

// GetInboundEmailAttachment Attachment.
//
// GET /inbound-emails/:id/attachments/:idx
func (c *Client) GetInboundEmailAttachment(ctx context.Context, id string, idx string, opts ...RequestOption) ([]byte, error) {
	return doRaw(ctx, c, "GET", fmt.Sprintf("/inbound-emails/%s/attachments/%s", escape(id), escape(idx)), opts)
}

// GetInboundEmailRaw Raw.
//
// GET /inbound-emails/:id/raw
func (c *Client) GetInboundEmailRaw(ctx context.Context, id string, opts ...RequestOption) ([]byte, error) {
	return doRaw(ctx, c, "GET", fmt.Sprintf("/inbound-emails/%s/raw", escape(id)), opts)
}

// RetryInboundEmail Retry.
//
// POST /inbound-emails/:id/retry
func (c *Client) RetryInboundEmail(ctx context.Context, id string, opts ...RequestOption) (EmittedResponse, error) {
	return do[EmittedResponse](ctx, c, "POST", fmt.Sprintf("/inbound-emails/%s/retry", escape(id)), nil, opts)
}

// ListInboundEmailsStats Count received mail by status.
//
// GET /inbound-emails/stats
func (c *Client) ListInboundEmailsStats(ctx context.Context, opts ...RequestOption) (InboundStatsResponse, error) {
	return do[InboundStatsResponse](ctx, c, "GET", "/inbound-emails/stats", nil, opts)
}

// AcceptInvitation Accept invitation.
//
// POST /invitations/:token/accept
func (c *Client) AcceptInvitation(ctx context.Context, token string, opts ...RequestOption) (JoinedResponse, error) {
	return do[JoinedResponse](ctx, c, "POST", fmt.Sprintf("/invitations/%s/accept", escape(token)), nil, opts)
}

// DeclineInvitation Decline invitation.
//
// POST /invitations/:token/decline
func (c *Client) DeclineInvitation(ctx context.Context, token string, opts ...RequestOption) (DeclinedResponse, error) {
	return do[DeclinedResponse](ctx, c, "POST", fmt.Sprintf("/invitations/%s/decline", escape(token)), nil, opts)
}

// ListLanguages List.
//
// GET /languages/
func (c *Client) ListLanguages(ctx context.Context, opts ...RequestOption) (LanguageListResponse, error) {
	return do[LanguageListResponse](ctx, c, "GET", "/languages", nil, opts)
}

// CreateLanguage Create.
//
// POST /languages/
func (c *Client) CreateLanguage(ctx context.Context, body LanguageUpsertInput, opts ...RequestOption) (LanguageResponse, error) {
	return do[LanguageResponse](ctx, c, "POST", "/languages", body, opts)
}

// DeleteLanguage Delete.
//
// DELETE /languages/:id
func (c *Client) DeleteLanguage(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/languages/%s", escape(id)), nil, opts)
	return err
}

// UpdateLanguage Update.
//
// PUT /languages/:id
func (c *Client) UpdateLanguage(ctx context.Context, id string, body LanguageUpsertInput, opts ...RequestOption) (LanguageResponse, error) {
	return do[LanguageResponse](ctx, c, "PUT", fmt.Sprintf("/languages/%s", escape(id)), body, opts)
}

// ListMyRelayNodes List mine.
//
// GET /my/relay-nodes/
func (c *Client) ListMyRelayNodes(ctx context.Context, opts ...RequestOption) (ListOutput, error) {
	return do[ListOutput](ctx, c, "GET", "/my/relay-nodes", nil, opts)
}

// DeleteMyRelayNode Delete mine.
//
// DELETE /my/relay-nodes/:id
func (c *Client) DeleteMyRelayNode(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/my/relay-nodes/%s", escape(id)), nil, opts)
	return err
}

// RelayNodesApproveMy Approve mine.
//
// POST /my/relay-nodes/:id/approve
func (c *Client) RelayNodesApproveMy(ctx context.Context, id string, opts ...RequestOption) (StatusResponse, error) {
	return do[StatusResponse](ctx, c, "POST", fmt.Sprintf("/my/relay-nodes/%s/approve", escape(id)), nil, opts)
}

// RelayNodesSuspendMy Suspend mine.
//
// POST /my/relay-nodes/:id/suspend
func (c *Client) RelayNodesSuspendMy(ctx context.Context, id string, opts ...RequestOption) (StatusResponse, error) {
	return do[StatusResponse](ctx, c, "POST", fmt.Sprintf("/my/relay-nodes/%s/suspend", escape(id)), nil, opts)
}

// ListNotifications List.
//
// GET /notifications/
func (c *Client) ListNotifications(ctx context.Context, opts ...RequestOption) (NotificationListResponse, error) {
	return do[NotificationListResponse](ctx, c, "GET", "/notifications", nil, opts)
}

// DeleteNotification Delete.
//
// DELETE /notifications/:id
func (c *Client) DeleteNotification(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/notifications/%s", escape(id)), nil, opts)
	return err
}

// ReadNotification Mark read.
//
// POST /notifications/:id/read
func (c *Client) ReadNotification(ctx context.Context, id string, opts ...RequestOption) (ReadResponse, error) {
	return do[ReadResponse](ctx, c, "POST", fmt.Sprintf("/notifications/%s/read", escape(id)), nil, opts)
}

// ReadAllNotification Mark all read.
//
// POST /notifications/read-all
func (c *Client) ReadAllNotification(ctx context.Context, opts ...RequestOption) (MarkedResponse, error) {
	return do[MarkedResponse](ctx, c, "POST", "/notifications/read-all", nil, opts)
}

// GetNotificationsUnread Unread.
//
// GET /notifications/unread
func (c *Client) GetNotificationsUnread(ctx context.Context, opts ...RequestOption) (UnreadResponse, error) {
	return do[UnreadResponse](ctx, c, "GET", "/notifications/unread", nil, opts)
}

// ListPermissions Catalog.
//
// GET /permissions
func (c *Client) ListPermissions(ctx context.Context, opts ...RequestOption) (CatalogResponse, error) {
	return do[CatalogResponse](ctx, c, "GET", "/permissions", nil, opts)
}

// ListProjects List.
//
// GET /projects/
func (c *Client) ListProjects(ctx context.Context, opts ...RequestOption) (ProjectListResponse, error) {
	return do[ProjectListResponse](ctx, c, "GET", "/projects", nil, opts)
}

// CreateProject Create.
//
// POST /projects/
func (c *Client) CreateProject(ctx context.Context, body ProjectCreateInput, opts ...RequestOption) (ProjectResponse, error) {
	return do[ProjectResponse](ctx, c, "POST", "/projects", body, opts)
}

// DeleteProject Delete.
//
// DELETE /projects/:id
func (c *Client) DeleteProject(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/projects/%s", escape(id)), nil, opts)
	return err
}

// GetProject Get.
//
// GET /projects/:id
func (c *Client) GetProject(ctx context.Context, id string, opts ...RequestOption) (ProjectAccessResponse, error) {
	return do[ProjectAccessResponse](ctx, c, "GET", fmt.Sprintf("/projects/%s", escape(id)), nil, opts)
}

// UpdateProject Update.
//
// PATCH /projects/:id
func (c *Client) UpdateProject(ctx context.Context, id string, body ProjectUpdateInput, opts ...RequestOption) (ProjectResponse, error) {
	return do[ProjectResponse](ctx, c, "PATCH", fmt.Sprintf("/projects/%s", escape(id)), body, opts)
}

// UpdateProjectDefaultRole Set the default role.
//
// PUT /projects/:id/default-role
func (c *Client) UpdateProjectDefaultRole(ctx context.Context, id string, body DefaultRoleInput, opts ...RequestOption) (ProjectResponse, error) {
	return do[ProjectResponse](ctx, c, "PUT", fmt.Sprintf("/projects/%s/default-role", escape(id)), body, opts)
}

// ListProjectInvitations List invitations.
//
// GET /projects/:id/invitations
func (c *Client) ListProjectInvitations(ctx context.Context, id string, opts ...RequestOption) (InvitationListResponse, error) {
	return do[InvitationListResponse](ctx, c, "GET", fmt.Sprintf("/projects/%s/invitations", escape(id)), nil, opts)
}

// CreateProjectInvitation Create invitation.
//
// POST /projects/:id/invitations
func (c *Client) CreateProjectInvitation(ctx context.Context, id string, body InviteInput, opts ...RequestOption) (InvitationCreatedResponse, error) {
	return do[InvitationCreatedResponse](ctx, c, "POST", fmt.Sprintf("/projects/%s/invitations", escape(id)), body, opts)
}

// DeleteProjectInvitation Delete invitation.
//
// DELETE /projects/:id/invitations/:invId
func (c *Client) DeleteProjectInvitation(ctx context.Context, id string, invId string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/projects/%s/invitations/%s", escape(id), escape(invId)), nil, opts)
	return err
}

// ListProjectMembers List members.
//
// GET /projects/:id/members
func (c *Client) ListProjectMembers(ctx context.Context, id string, opts ...RequestOption) (MemberListResponse, error) {
	return do[MemberListResponse](ctx, c, "GET", fmt.Sprintf("/projects/%s/members", escape(id)), nil, opts)
}

// CreateProjectMember Add member.
//
// POST /projects/:id/members
func (c *Client) CreateProjectMember(ctx context.Context, id string, body MemberInput, opts ...RequestOption) (MemberResponse, error) {
	return do[MemberResponse](ctx, c, "POST", fmt.Sprintf("/projects/%s/members", escape(id)), body, opts)
}

// DeleteProjectMember Remove member.
//
// DELETE /projects/:id/members/:userId
func (c *Client) DeleteProjectMember(ctx context.Context, id string, userId string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/projects/%s/members/%s", escape(id), escape(userId)), nil, opts)
	return err
}

// UpdateProjectMember Update member.
//
// PATCH /projects/:id/members/:userId
func (c *Client) UpdateProjectMember(ctx context.Context, id string, userId string, body MemberRoleInput, opts ...RequestOption) (MemberResponse, error) {
	return do[MemberResponse](ctx, c, "PATCH", fmt.Sprintf("/projects/%s/members/%s", escape(id), escape(userId)), body, opts)
}

// ListProjectRoles List roles.
//
// GET /projects/:id/roles
func (c *Client) ListProjectRoles(ctx context.Context, id string, opts ...RequestOption) (RoleListResponse, error) {
	return do[RoleListResponse](ctx, c, "GET", fmt.Sprintf("/projects/%s/roles", escape(id)), nil, opts)
}

// CreateProjectRole Create role.
//
// POST /projects/:id/roles
func (c *Client) CreateProjectRole(ctx context.Context, id string, body RoleInput, opts ...RequestOption) (RoleResponse, error) {
	return do[RoleResponse](ctx, c, "POST", fmt.Sprintf("/projects/%s/roles", escape(id)), body, opts)
}

// DeleteProjectRole Delete role.
//
// DELETE /projects/:id/roles/:roleId
func (c *Client) DeleteProjectRole(ctx context.Context, id string, roleId string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/projects/%s/roles/%s", escape(id), escape(roleId)), nil, opts)
	return err
}

// UpdateProjectRole Update role.
//
// PATCH /projects/:id/roles/:roleId
func (c *Client) UpdateProjectRole(ctx context.Context, id string, roleId string, body RoleInput, opts ...RequestOption) (RoleResponse, error) {
	return do[RoleResponse](ctx, c, "PATCH", fmt.Sprintf("/projects/%s/roles/%s", escape(id), escape(roleId)), body, opts)
}

// ListSandbox List.
//
// GET /sandbox/
func (c *Client) ListSandbox(ctx context.Context, opts ...RequestOption) (SandboxListResponse, error) {
	return do[SandboxListResponse](ctx, c, "GET", "/sandbox", nil, opts)
}

// DeleteSandbox Delete.
//
// DELETE /sandbox/:id
func (c *Client) DeleteSandbox(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/sandbox/%s", escape(id)), nil, opts)
	return err
}

// GetSandbox Get.
//
// GET /sandbox/:id
func (c *Client) GetSandbox(ctx context.Context, id string, opts ...RequestOption) (SandboxEmailResponse, error) {
	return do[SandboxEmailResponse](ctx, c, "GET", fmt.Sprintf("/sandbox/%s", escape(id)), nil, opts)
}

// GetSandboxAttachment Attachment.
//
// GET /sandbox/:id/attachments/:idx
func (c *Client) GetSandboxAttachment(ctx context.Context, id string, idx string, opts ...RequestOption) ([]byte, error) {
	return doRaw(ctx, c, "GET", fmt.Sprintf("/sandbox/%s/attachments/%s", escape(id), escape(idx)), opts)
}

// GetSandboxRaw Raw.
//
// GET /sandbox/:id/raw
func (c *Client) GetSandboxRaw(ctx context.Context, id string, opts ...RequestOption) ([]byte, error) {
	return doRaw(ctx, c, "GET", fmt.Sprintf("/sandbox/%s/raw", escape(id)), opts)
}

// ClearSandbox Clear.
//
// POST /sandbox/clear
func (c *Client) ClearSandbox(ctx context.Context, opts ...RequestOption) (SandboxDeletedResponse, error) {
	return do[SandboxDeletedResponse](ctx, c, "POST", "/sandbox/clear", nil, opts)
}

// ListSandboxCredentials List credentials.
//
// GET /sandbox/credentials
func (c *Client) ListSandboxCredentials(ctx context.Context, opts ...RequestOption) (CredentialListResponse, error) {
	return do[CredentialListResponse](ctx, c, "GET", "/sandbox/credentials", nil, opts)
}

// CreateSandboxCredential Create credential.
//
// POST /sandbox/credentials
func (c *Client) CreateSandboxCredential(ctx context.Context, body CredentialInput, opts ...RequestOption) (CredentialCreatedResponse, error) {
	return do[CredentialCreatedResponse](ctx, c, "POST", "/sandbox/credentials", body, opts)
}

// CredentialsRevokeSandbox Revoke credential.
//
// POST /sandbox/credentials/:id/revoke
func (c *Client) CredentialsRevokeSandbox(ctx context.Context, id string, opts ...RequestOption) (CredentialResponse, error) {
	return do[CredentialResponse](ctx, c, "POST", fmt.Sprintf("/sandbox/credentials/%s/revoke", escape(id)), nil, opts)
}

// GetSandboxInfo Info.
//
// GET /sandbox/info
func (c *Client) GetSandboxInfo(ctx context.Context, opts ...RequestOption) (SettingsResponse, error) {
	return do[SettingsResponse](ctx, c, "GET", "/sandbox/info", nil, opts)
}

// ListSenders List.
//
// GET /senders/
func (c *Client) ListSenders(ctx context.Context, opts ...RequestOption) (SenderListResponse, error) {
	return do[SenderListResponse](ctx, c, "GET", "/senders", nil, opts)
}

// CreateSender Create.
//
// POST /senders/
func (c *Client) CreateSender(ctx context.Context, body SenderCreateInput, opts ...RequestOption) (SenderResponse, error) {
	return do[SenderResponse](ctx, c, "POST", "/senders", body, opts)
}

// DeleteSender Delete.
//
// DELETE /senders/:id
func (c *Client) DeleteSender(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/senders/%s", escape(id)), nil, opts)
	return err
}

// ListSmtpCredentials List.
//
// GET /smtp-credentials/
func (c *Client) ListSmtpCredentials(ctx context.Context, opts ...RequestOption) (SmtpcredentialListResponse, error) {
	return do[SmtpcredentialListResponse](ctx, c, "GET", "/smtp-credentials", nil, opts)
}

// CreateSmtpCredential Create.
//
// POST /smtp-credentials/
func (c *Client) CreateSmtpCredential(ctx context.Context, body SmtpcredentialCreateInput, opts ...RequestOption) (SmtpcredentialCreatedResponse, error) {
	return do[SmtpcredentialCreatedResponse](ctx, c, "POST", "/smtp-credentials", body, opts)
}

// DeleteSmtpCredential Delete.
//
// DELETE /smtp-credentials/:id
func (c *Client) DeleteSmtpCredential(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/smtp-credentials/%s", escape(id)), nil, opts)
	return err
}

// RevokeSmtpCredential Revoke.
//
// POST /smtp-credentials/:id/revoke
func (c *Client) RevokeSmtpCredential(ctx context.Context, id string, opts ...RequestOption) (SmtpcredentialCredentialResponse, error) {
	return do[SmtpcredentialCredentialResponse](ctx, c, "POST", fmt.Sprintf("/smtp-credentials/%s/revoke", escape(id)), nil, opts)
}

// ListSmtpServerGroups List.
//
// GET /smtp-server-groups/
func (c *Client) ListSmtpServerGroups(ctx context.Context, opts ...RequestOption) (GroupListResponse, error) {
	return do[GroupListResponse](ctx, c, "GET", "/smtp-server-groups", nil, opts)
}

// CreateSmtpServerGroup Create.
//
// POST /smtp-server-groups/
func (c *Client) CreateSmtpServerGroup(ctx context.Context, body GroupCreateInput, opts ...RequestOption) (GroupResponse, error) {
	return do[GroupResponse](ctx, c, "POST", "/smtp-server-groups", body, opts)
}

// DeleteSmtpServerGroup Delete.
//
// DELETE /smtp-server-groups/:id
func (c *Client) DeleteSmtpServerGroup(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/smtp-server-groups/%s", escape(id)), nil, opts)
	return err
}

// GetSmtpServerGroup Get.
//
// GET /smtp-server-groups/:id
func (c *Client) GetSmtpServerGroup(ctx context.Context, id string, opts ...RequestOption) (GroupResponse, error) {
	return do[GroupResponse](ctx, c, "GET", fmt.Sprintf("/smtp-server-groups/%s", escape(id)), nil, opts)
}

// UpdateSmtpServerGroup Update.
//
// PATCH /smtp-server-groups/:id
func (c *Client) UpdateSmtpServerGroup(ctx context.Context, id string, body GroupUpdateInput, opts ...RequestOption) (GroupResponse, error) {
	return do[GroupResponse](ctx, c, "PATCH", fmt.Sprintf("/smtp-server-groups/%s", escape(id)), body, opts)
}

// ListSmtpServers List.
//
// GET /smtp-servers/
func (c *Client) ListSmtpServers(ctx context.Context, opts ...RequestOption) (SmtpserverListResponse, error) {
	return do[SmtpserverListResponse](ctx, c, "GET", "/smtp-servers", nil, opts)
}

// CreateSmtpServer Create.
//
// POST /smtp-servers/
func (c *Client) CreateSmtpServer(ctx context.Context, body SmtpserverCreateInput, opts ...RequestOption) (ServerResponse, error) {
	return do[ServerResponse](ctx, c, "POST", "/smtp-servers", body, opts)
}

// DeleteSmtpServer Delete.
//
// DELETE /smtp-servers/:id
func (c *Client) DeleteSmtpServer(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/smtp-servers/%s", escape(id)), nil, opts)
	return err
}

// GetSmtpServer Get.
//
// GET /smtp-servers/:id
func (c *Client) GetSmtpServer(ctx context.Context, id string, opts ...RequestOption) (ServerResponse, error) {
	return do[ServerResponse](ctx, c, "GET", fmt.Sprintf("/smtp-servers/%s", escape(id)), nil, opts)
}

// UpdateSmtpServer Update.
//
// PATCH /smtp-servers/:id
func (c *Client) UpdateSmtpServer(ctx context.Context, id string, body SmtpserverUpdateInput, opts ...RequestOption) (ServerResponse, error) {
	return do[ServerResponse](ctx, c, "PATCH", fmt.Sprintf("/smtp-servers/%s", escape(id)), body, opts)
}

// DisableSmtpServer Disable.
//
// POST /smtp-servers/:id/disable
func (c *Client) DisableSmtpServer(ctx context.Context, id string, opts ...RequestOption) (ServerResponse, error) {
	return do[ServerResponse](ctx, c, "POST", fmt.Sprintf("/smtp-servers/%s/disable", escape(id)), nil, opts)
}

// EnableSmtpServer Enable.
//
// POST /smtp-servers/:id/enable
func (c *Client) EnableSmtpServer(ctx context.Context, id string, opts ...RequestOption) (ServerResponse, error) {
	return do[ServerResponse](ctx, c, "POST", fmt.Sprintf("/smtp-servers/%s/enable", escape(id)), nil, opts)
}

// TestSmtpServer Test.
//
// POST /smtp-servers/:id/test
func (c *Client) TestSmtpServer(ctx context.Context, id string, opts ...RequestOption) (SmtpserverTestResponse, error) {
	return do[SmtpserverTestResponse](ctx, c, "POST", fmt.Sprintf("/smtp-servers/%s/test", escape(id)), nil, opts)
}

// ListStylesheets List.
//
// GET /stylesheets/
func (c *Client) ListStylesheets(ctx context.Context, opts ...RequestOption) (StylesheetListResponse, error) {
	return do[StylesheetListResponse](ctx, c, "GET", "/stylesheets", nil, opts)
}

// CreateStylesheet Create.
//
// POST /stylesheets/
func (c *Client) CreateStylesheet(ctx context.Context, body StylesheetUpsertInput, opts ...RequestOption) (StylesheetResponse, error) {
	return do[StylesheetResponse](ctx, c, "POST", "/stylesheets", body, opts)
}

// DeleteStylesheet Delete.
//
// DELETE /stylesheets/:id
func (c *Client) DeleteStylesheet(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/stylesheets/%s", escape(id)), nil, opts)
	return err
}

// GetStylesheet Get.
//
// GET /stylesheets/:id
func (c *Client) GetStylesheet(ctx context.Context, id string, opts ...RequestOption) (StylesheetResponse, error) {
	return do[StylesheetResponse](ctx, c, "GET", fmt.Sprintf("/stylesheets/%s", escape(id)), nil, opts)
}

// UpdateStylesheet Update.
//
// PUT /stylesheets/:id
func (c *Client) UpdateStylesheet(ctx context.Context, id string, body StylesheetUpsertInput, opts ...RequestOption) (StylesheetResponse, error) {
	return do[StylesheetResponse](ctx, c, "PUT", fmt.Sprintf("/stylesheets/%s", escape(id)), body, opts)
}

// ListSubscriberLists List.
//
// GET /subscriber-lists/
func (c *Client) ListSubscriberLists(ctx context.Context, opts ...RequestOption) (SubscriberlistListResponse, error) {
	return do[SubscriberlistListResponse](ctx, c, "GET", "/subscriber-lists", nil, opts)
}

// CreateSubscriberList Create.
//
// POST /subscriber-lists/
func (c *Client) CreateSubscriberList(ctx context.Context, body SubscriberlistUpsertInput, opts ...RequestOption) (ListDetailResponse, error) {
	return do[ListDetailResponse](ctx, c, "POST", "/subscriber-lists", body, opts)
}

// DeleteSubscriberList Delete.
//
// DELETE /subscriber-lists/:id
func (c *Client) DeleteSubscriberList(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/subscriber-lists/%s", escape(id)), nil, opts)
	return err
}

// GetSubscriberList Get.
//
// GET /subscriber-lists/:id
func (c *Client) GetSubscriberList(ctx context.Context, id string, opts ...RequestOption) (ListDetailResponse, error) {
	return do[ListDetailResponse](ctx, c, "GET", fmt.Sprintf("/subscriber-lists/%s", escape(id)), nil, opts)
}

// UpdateSubscriberList Update.
//
// PATCH /subscriber-lists/:id
func (c *Client) UpdateSubscriberList(ctx context.Context, id string, body SubscriberlistUpsertInput, opts ...RequestOption) (ListDetailResponse, error) {
	return do[ListDetailResponse](ctx, c, "PATCH", fmt.Sprintf("/subscriber-lists/%s", escape(id)), body, opts)
}

// ListSubscriberListMembers List members.
//
// GET /subscriber-lists/:id/members
func (c *Client) ListSubscriberListMembers(ctx context.Context, id string, opts ...RequestOption) (SubscriberlistMemberListResponse, error) {
	return do[SubscriberlistMemberListResponse](ctx, c, "GET", fmt.Sprintf("/subscriber-lists/%s/members", escape(id)), nil, opts)
}

// CreateSubscriberListMember Add member.
//
// POST /subscriber-lists/:id/members
func (c *Client) CreateSubscriberListMember(ctx context.Context, id string, body SubscriberlistMemberInput, opts ...RequestOption) (SubscriberResponse, error) {
	return do[SubscriberResponse](ctx, c, "POST", fmt.Sprintf("/subscriber-lists/%s/members", escape(id)), body, opts)
}

// DeleteSubscriberListMember Remove member.
//
// DELETE /subscriber-lists/:id/members/:subscriberId
func (c *Client) DeleteSubscriberListMember(ctx context.Context, id string, subscriberId string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/subscriber-lists/%s/members/%s", escape(id), escape(subscriberId)), nil, opts)
	return err
}

// ResubscribeSubscriberList Re-add an address that had opted out.
//
// POST /subscriber-lists/:id/resubscribe
func (c *Client) ResubscribeSubscriberList(ctx context.Context, id string, body ListEmailInput, opts ...RequestOption) (MembershipChange, error) {
	return do[MembershipChange](ctx, c, "POST", fmt.Sprintf("/subscriber-lists/%s/resubscribe", escape(id)), body, opts)
}

// UnsubscribeSubscriberList Remove an address from a list.
//
// POST /subscriber-lists/:id/unsubscribe
func (c *Client) UnsubscribeSubscriberList(ctx context.Context, id string, body ListEmailInput, opts ...RequestOption) (MembershipChange, error) {
	return do[MembershipChange](ctx, c, "POST", fmt.Sprintf("/subscriber-lists/%s/unsubscribe", escape(id)), body, opts)
}

// PreviewSegmentSubscriberList Preview segment.
//
// POST /subscriber-lists/preview-segment
func (c *Client) PreviewSegmentSubscriberList(ctx context.Context, body PreviewInput, opts ...RequestOption) (SegmentPreviewResponse, error) {
	return do[SegmentPreviewResponse](ctx, c, "POST", "/subscriber-lists/preview-segment", body, opts)
}

// SubscribeSubscriberList Add an address to a static list.
//
// POST /subscriber-lists/subscribe
func (c *Client) SubscribeSubscriberList(ctx context.Context, body SubscribeInput, opts ...RequestOption) (SubscribeResponse, error) {
	return do[SubscribeResponse](ctx, c, "POST", "/subscriber-lists/subscribe", body, opts)
}

// ListSubscribers List.
//
// GET /subscribers/
func (c *Client) ListSubscribers(ctx context.Context, opts ...RequestOption) (SubscriberListResponse, error) {
	return do[SubscriberListResponse](ctx, c, "GET", "/subscribers", nil, opts)
}

// CreateSubscriber Create.
//
// POST /subscribers/
func (c *Client) CreateSubscriber(ctx context.Context, body SubscriberUpsertInput, opts ...RequestOption) (SubscriberSubscriberResponse, error) {
	return do[SubscriberSubscriberResponse](ctx, c, "POST", "/subscribers", body, opts)
}

// DeleteSubscriber Delete.
//
// DELETE /subscribers/:id
func (c *Client) DeleteSubscriber(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/subscribers/%s", escape(id)), nil, opts)
	return err
}

// GetSubscriber Get.
//
// GET /subscribers/:id
func (c *Client) GetSubscriber(ctx context.Context, id string, opts ...RequestOption) (SubscriberSubscriberResponse, error) {
	return do[SubscriberSubscriberResponse](ctx, c, "GET", fmt.Sprintf("/subscribers/%s", escape(id)), nil, opts)
}

// UpdateSubscriber Update.
//
// PATCH /subscribers/:id
func (c *Client) UpdateSubscriber(ctx context.Context, id string, body SubscriberUpsertInput, opts ...RequestOption) (SubscriberSubscriberResponse, error) {
	return do[SubscriberSubscriberResponse](ctx, c, "PATCH", fmt.Sprintf("/subscribers/%s", escape(id)), body, opts)
}

// ImportSubscriber Import.
//
// POST /subscribers/import
func (c *Client) ImportSubscriber(ctx context.Context, body ImportInput, opts ...RequestOption) (ImportResponse, error) {
	return do[ImportResponse](ctx, c, "POST", "/subscribers/import", body, opts)
}

// ImportCsvSubscriber Import CSV.
//
// POST /subscribers/import/csv
func (c *Client) ImportCsvSubscriber(ctx context.Context, opts ...RequestOption) (ImportResponse, error) {
	return do[ImportResponse](ctx, c, "POST", "/subscribers/import/csv", nil, opts)
}

// DeleteSuppressions Unblock an address.
//
// DELETE /suppressions
func (c *Client) DeleteSuppressions(ctx context.Context, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", "/suppressions", nil, opts)
	return err
}

// ListSuppressions List blocked addresses.
//
// GET /suppressions
func (c *Client) ListSuppressions(ctx context.Context, opts ...RequestOption) (SuppressionListResponse, error) {
	return do[SuppressionListResponse](ctx, c, "GET", "/suppressions", nil, opts)
}

// CreateSuppression Block an address.
//
// POST /suppressions
func (c *Client) CreateSuppression(ctx context.Context, body SuppressionCreateInput, opts ...RequestOption) (CreateResponse, error) {
	return do[CreateResponse](ctx, c, "POST", "/suppressions", body, opts)
}

// ListTemplates List templates.
//
// GET /templates
func (c *Client) ListTemplates(ctx context.Context, opts ...RequestOption) (TemplateListResponse, error) {
	return do[TemplateListResponse](ctx, c, "GET", "/templates", nil, opts)
}

// CreateTemplate Create.
//
// POST /templates/
func (c *Client) CreateTemplate(ctx context.Context, body TemplateCreateInput, opts ...RequestOption) (TemplateResponse, error) {
	return do[TemplateResponse](ctx, c, "POST", "/templates", body, opts)
}

// DeleteTemplate Delete.
//
// DELETE /templates/:id
func (c *Client) DeleteTemplate(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/templates/%s", escape(id)), nil, opts)
	return err
}

// GetTemplate One template with its version history.
//
// GET /templates/:id
func (c *Client) GetTemplate(ctx context.Context, id string, opts ...RequestOption) (TemplateGetResponse, error) {
	return do[TemplateGetResponse](ctx, c, "GET", fmt.Sprintf("/templates/%s", escape(id)), nil, opts)
}

// UpdateTemplate Update.
//
// PATCH /templates/:id
func (c *Client) UpdateTemplate(ctx context.Context, id string, body TemplateUpdateInput, opts ...RequestOption) (TemplateResponse, error) {
	return do[TemplateResponse](ctx, c, "PATCH", fmt.Sprintf("/templates/%s", escape(id)), body, opts)
}

// ActivateTemplate Activate.
//
// POST /templates/:id/activate/:versionId
func (c *Client) ActivateTemplate(ctx context.Context, id string, versionId string, opts ...RequestOption) (ActiveVersionResponse, error) {
	return do[ActiveVersionResponse](ctx, c, "POST", fmt.Sprintf("/templates/%s/activate/%s", escape(id), escape(versionId)), nil, opts)
}

// ListTemplateAttachments List attachments.
//
// GET /templates/:id/attachments
func (c *Client) ListTemplateAttachments(ctx context.Context, id string, opts ...RequestOption) (AttachmentListResponse, error) {
	return do[AttachmentListResponse](ctx, c, "GET", fmt.Sprintf("/templates/%s/attachments", escape(id)), nil, opts)
}

// CreateTemplateAttachment Upload attachment.
//
// POST /templates/:id/attachments
func (c *Client) CreateTemplateAttachment(ctx context.Context, id string, body AttachmentInput, opts ...RequestOption) (AttachmentResponse, error) {
	return do[AttachmentResponse](ctx, c, "POST", fmt.Sprintf("/templates/%s/attachments", escape(id)), body, opts)
}

// DeleteTemplateAttachment Delete attachment.
//
// DELETE /templates/:id/attachments/:attId
func (c *Client) DeleteTemplateAttachment(ctx context.Context, id string, attId string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/templates/%s/attachments/%s", escape(id), escape(attId)), nil, opts)
	return err
}

// GetTemplateAttachmentsDownload Download attachment.
//
// GET /templates/:id/attachments/:attId/download
func (c *Client) GetTemplateAttachmentsDownload(ctx context.Context, id string, attId string, opts ...RequestOption) ([]byte, error) {
	return doRaw(ctx, c, "GET", fmt.Sprintf("/templates/%s/attachments/%s/download", escape(id), escape(attId)), opts)
}

// GetTemplateExport Export.
//
// GET /templates/:id/export
func (c *Client) GetTemplateExport(ctx context.Context, id string, opts ...RequestOption) (TemplateExportResponse, error) {
	return do[TemplateExportResponse](ctx, c, "GET", fmt.Sprintf("/templates/%s/export", escape(id)), nil, opts)
}

// DeleteTemplateLocalization Delete localization.
//
// DELETE /templates/:id/localizations/:localizationId
func (c *Client) DeleteTemplateLocalization(ctx context.Context, id string, localizationId string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/templates/%s/localizations/%s", escape(id), escape(localizationId)), nil, opts)
	return err
}

// SendTestTemplate Send test.
//
// POST /templates/:id/send-test
func (c *Client) SendTestTemplate(ctx context.Context, id string, body TestSendInput, opts ...RequestOption) (SendResponse, error) {
	return do[SendResponse](ctx, c, "POST", fmt.Sprintf("/templates/%s/send-test", escape(id)), body, opts)
}

// ListTemplateVersions List versions.
//
// GET /templates/:id/versions
func (c *Client) ListTemplateVersions(ctx context.Context, id string, opts ...RequestOption) (VersionListResponse, error) {
	return do[VersionListResponse](ctx, c, "GET", fmt.Sprintf("/templates/%s/versions", escape(id)), nil, opts)
}

// CreateTemplateVersion Create version.
//
// POST /templates/:id/versions
func (c *Client) CreateTemplateVersion(ctx context.Context, id string, body VersionInput, opts ...RequestOption) (VersionResponse, error) {
	return do[VersionResponse](ctx, c, "POST", fmt.Sprintf("/templates/%s/versions", escape(id)), body, opts)
}

// DeleteTemplateVersion Delete version.
//
// DELETE /templates/:id/versions/:versionId
func (c *Client) DeleteTemplateVersion(ctx context.Context, id string, versionId string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/templates/%s/versions/%s", escape(id), escape(versionId)), nil, opts)
	return err
}

// UpdateTemplateVersion Update version.
//
// PATCH /templates/:id/versions/:versionId
func (c *Client) UpdateTemplateVersion(ctx context.Context, id string, versionId string, body VersionInput, opts ...RequestOption) (VersionResponse, error) {
	return do[VersionResponse](ctx, c, "PATCH", fmt.Sprintf("/templates/%s/versions/%s", escape(id), escape(versionId)), body, opts)
}

// ListTemplateVersionsLocalizations List localizations.
//
// GET /templates/:id/versions/:versionId/localizations
func (c *Client) ListTemplateVersionsLocalizations(ctx context.Context, id string, versionId string, opts ...RequestOption) (LocalizationListResponse, error) {
	return do[LocalizationListResponse](ctx, c, "GET", fmt.Sprintf("/templates/%s/versions/%s/localizations", escape(id), escape(versionId)), nil, opts)
}

// UpdateTemplateVersionsLocalization Put localization.
//
// PUT /templates/:id/versions/:versionId/localizations
func (c *Client) UpdateTemplateVersionsLocalization(ctx context.Context, id string, versionId string, body LocalizationInput, opts ...RequestOption) (LocalizationResponse, error) {
	return do[LocalizationResponse](ctx, c, "PUT", fmt.Sprintf("/templates/%s/versions/%s/localizations", escape(id), escape(versionId)), body, opts)
}

// VersionsPreviewTemplate Preview version.
//
// POST /templates/:id/versions/:versionId/preview
func (c *Client) VersionsPreviewTemplate(ctx context.Context, id string, versionId string, body VersionPreviewInput, opts ...RequestOption) (RenderLanguageResponse, error) {
	return do[RenderLanguageResponse](ctx, c, "POST", fmt.Sprintf("/templates/%s/versions/%s/preview", escape(id), escape(versionId)), body, opts)
}

// ImportTemplate Import.
//
// POST /templates/import
func (c *Client) ImportTemplate(ctx context.Context, body TransferDoc, opts ...RequestOption) (TemplateResponse, error) {
	return do[TemplateResponse](ctx, c, "POST", "/templates/import", body, opts)
}

// PreviewTemplate Preview.
//
// POST /templates/preview
func (c *Client) PreviewTemplate(ctx context.Context, body TemplatePreviewInput, opts ...RequestOption) (RenderResponse, error) {
	return do[RenderResponse](ctx, c, "POST", "/templates/preview", body, opts)
}

// ListUnsubscribeLists List transactional opt-out scopes.
//
// GET /unsubscribe-lists
func (c *Client) ListUnsubscribeLists(ctx context.Context, opts ...RequestOption) (UnsubscribelistListResponse, error) {
	return do[UnsubscribelistListResponse](ctx, c, "GET", "/unsubscribe-lists", nil, opts)
}

// CreateUnsubscribeList Create.
//
// POST /unsubscribe-lists/
func (c *Client) CreateUnsubscribeList(ctx context.Context, body UnsubscribelistCreateInput, opts ...RequestOption) (UnsubscribelistGetResponse, error) {
	return do[UnsubscribelistGetResponse](ctx, c, "POST", "/unsubscribe-lists", body, opts)
}

// DeleteUnsubscribeList Delete.
//
// DELETE /unsubscribe-lists/:id
func (c *Client) DeleteUnsubscribeList(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/unsubscribe-lists/%s", escape(id)), nil, opts)
	return err
}

// GetUnsubscribeList One opt-out scope.
//
// GET /unsubscribe-lists/:id
func (c *Client) GetUnsubscribeList(ctx context.Context, id string, opts ...RequestOption) (UnsubscribelistGetResponse, error) {
	return do[UnsubscribelistGetResponse](ctx, c, "GET", fmt.Sprintf("/unsubscribe-lists/%s", escape(id)), nil, opts)
}

// UpdateUnsubscribeList Update.
//
// PATCH /unsubscribe-lists/:id
func (c *Client) UpdateUnsubscribeList(ctx context.Context, id string, body UnsubscribelistUpdateInput, opts ...RequestOption) (UnsubscribelistGetResponse, error) {
	return do[UnsubscribelistGetResponse](ctx, c, "PATCH", fmt.Sprintf("/unsubscribe-lists/%s", escape(id)), body, opts)
}

// ListUsage Usage.
//
// GET /usage
func (c *Client) ListUsage(ctx context.Context, opts ...RequestOption) (UsageResponse, error) {
	return do[UsageResponse](ctx, c, "GET", "/usage", nil, opts)
}

// ListWebhooks List outgoing webhooks.
//
// GET /webhooks
func (c *Client) ListWebhooks(ctx context.Context, opts ...RequestOption) (WebhookListResponse, error) {
	return do[WebhookListResponse](ctx, c, "GET", "/webhooks", nil, opts)
}

// CreateWebhook Create an outgoing webhook.
//
// POST /webhooks
func (c *Client) CreateWebhook(ctx context.Context, body WebhookCreateInput, opts ...RequestOption) (WebhookCreateResponse, error) {
	return do[WebhookCreateResponse](ctx, c, "POST", "/webhooks", body, opts)
}

// DeleteWebhook Delete a webhook.
//
// DELETE /webhooks/:id
func (c *Client) DeleteWebhook(ctx context.Context, id string, opts ...RequestOption) error {
	_, err := do[struct{}](ctx, c, "DELETE", fmt.Sprintf("/webhooks/%s", escape(id)), nil, opts)
	return err
}

// ListWebhookDeliveries Delivery log of one webhook.
//
// GET /webhooks/:id/deliveries
func (c *Client) ListWebhookDeliveries(ctx context.Context, id string, opts ...RequestOption) (DeliveriesResponse, error) {
	return do[DeliveriesResponse](ctx, c, "GET", fmt.Sprintf("/webhooks/%s/deliveries", escape(id)), nil, opts)
}

// BounceWebhook Ingest a bounce report.
//
// POST /webhooks/bounce
func (c *Client) BounceWebhook(ctx context.Context, body IngestInput, opts ...RequestOption) (IngestResponse, error) {
	return do[IngestResponse](ctx, c, "POST", "/webhooks/bounce", body, opts)
}
