// Mailyard, Copyright (c) 2021-2026 YouSysAdmin

// Code generated by cmd/sdkgen. DO NOT EDIT.

package api

import "time"

// ACMEHost is the wire body.
type ACMEHost struct {
	Host    string   `json:"host"`
	Details *Details `json:"details,omitempty"`
}

// ACMEResponse is the response body.
type ACMEResponse struct {
	Enabled           bool       `json:"enabled"`
	Email             string     `json:"email"`
	DirectoryURL      string     `json:"directory_url"`
	Staging           bool       `json:"staging"`
	Hosts             []ACMEHost `json:"hosts"`
	Suggested         string     `json:"suggested,omitempty"`
	ChallengeAddr     string     `json:"challenge_addr,omitempty"`
	TLSTerminatedHere bool       `json:"tls_terminated_here"`
}

// APIKeyResponse is the response body.
type APIKeyResponse struct {
	APIKey *Key `json:"api_key"`
}

// ActiveVersionResponse is the response body.
type ActiveVersionResponse struct {
	ActiveVersionID string `json:"active_version_id"`
}

// Admin is the wire body.
type Admin struct {
	ID         string     `json:"id"`
	CreatedBy  string     `json:"created_by,omitempty"`
	Name       string     `json:"name"`
	KeyPrefix  string     `json:"key_prefix"`
	AllowedIPs []string   `json:"allowed_ips"`
	Revoked    bool       `json:"revoked"`
	ExpiresAt  *time.Time `json:"expires_at,omitempty"`
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	CreatedAt  time.Time  `json:"created_at"`
}

// AdminAPIKeyResponse is the response body.
type AdminAPIKeyResponse struct {
	AdminAPIKey *Admin `json:"admin_api_key"`
}

// AdminCreateInput is the request body.
type AdminCreateInput struct {
	Name       string   `json:"name"`
	AllowedIPs []string `json:"allowed_ips"`
	ExpiresAt  string   `json:"expires_at"`
}

// AdminCreatedResponse is the response body.
type AdminCreatedResponse struct {
	AdminAPIKey *Admin `json:"admin_api_key"`
	Token       string `json:"token"`
}

// AdminListResponse is the response body.
type AdminListResponse struct {
	AdminAPIKeys []*Admin `json:"admin_api_keys"`
}

// AnalyticsEngagement is the wire body.
type AnalyticsEngagement struct {
	TrackedSent int64   `json:"tracked_sent"`
	Opened      int64   `json:"opened"`
	Clicked     int64   `json:"clicked"`
	OpenRate    float64 `json:"open_rate"`
	ClickRate   float64 `json:"click_rate"`
}

// AnalyticsResponse is the response body.
type AnalyticsResponse struct {
	Links       any `json:"links"`
	OpenSeries  any `json:"open_series"`
	ClickSeries any `json:"click_series"`
}

// ApikeyCreateInput is the request body.
type ApikeyCreateInput struct {
	Name        string   `json:"name"`
	Permissions []string `json:"permissions"`
	AllowedIPs  []string `json:"allowed_ips"`
	ExpiresAt   string   `json:"expires_at"`
	Sandbox     bool     `json:"sandbox"`
}

// ApikeyListResponse is the response body.
type ApikeyListResponse struct {
	APIKeys []*Key `json:"api_keys"`
}

// AssignInput is the request body.
type AssignInput struct {
	PlanID string `json:"plan_id"`
}

// AssignResponse is the response body.
type AssignResponse struct {
	Project *Project `json:"project"`
}

// Attachment is the wire body.
type Attachment struct {
	Filename    string `json:"filename"`
	Content     string `json:"content,omitempty"`
	ContentType string `json:"content_type,omitempty"`
	StorageKey  string `json:"storage_key,omitempty"`
	Size        int64  `json:"size,omitzero"`
}

// AttachmentInput is the request body.
type AttachmentInput struct {
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
	Content     string `json:"content"`
}

// AttachmentListResponse is the response body.
type AttachmentListResponse struct {
	Attachments []*TemplateAttachment `json:"attachments"`
}

// AttachmentResponse is the response body.
type AttachmentResponse struct {
	Attachment *TemplateAttachment `json:"attachment"`
}

// AuditListResponse is the response body.
type AuditListResponse struct {
	Events []*Event `json:"events"`
	Limit  int64    `json:"limit"`
	Offset int64    `json:"offset"`
}

// Auth is the wire body.
type Auth struct {
	SPF         string `json:"spf"`
	DKIM        string `json:"dkim"`
	DMARC       string `json:"dmarc"`
	DMARCPolicy string `json:"dmarc_policy,omitempty"`
	Aligned     bool   `json:"aligned"`
	ClientIP    string `json:"client_ip,omitempty"`
}

// AuthMessageResponse is the response body.
type AuthMessageResponse struct {
	Message string `json:"message"`
}

// BatchInput is the request body.
type BatchInput struct {
	From         string           `json:"from"`
	TemplateID   string           `json:"template_id"`
	TemplateName string           `json:"template_name"`
	Language     string           `json:"language"`
	Items        []BatchItemInput `json:"items"`
}

// BatchItemInput is the request body.
type BatchItemInput struct {
	To                    []string       `json:"to"`
	Language              string         `json:"language"`
	Data                  map[string]any `json:"data"`
	Subject               string         `json:"subject"`
	HTML                  string         `json:"html"`
	Text                  string         `json:"text"`
	ListUnsubscribeURL    string         `json:"list_unsubscribe_url"`
	ListUnsubscribeMailto string         `json:"list_unsubscribe_mailto"`
	ListUnsubscribePost   bool           `json:"list_unsubscribe_post"`
}

// BatchResponse is the response body.
type BatchResponse struct {
	Total    int64         `json:"total"`
	Accepted int64         `json:"accepted"`
	Results  []BatchResult `json:"results"`
}

// BatchResult is the wire body.
type BatchResult struct {
	Index      int64    `json:"index"`
	EmailID    string   `json:"email_id,omitempty"`
	Status     string   `json:"status,omitempty"`
	Suppressed []string `json:"suppressed_recipients,omitempty"`
	Error      string   `json:"error,omitempty"`
}

// Bounce is the wire body.
type Bounce struct {
	ID        string    `json:"id"`
	ProjectID string    `json:"project_id"`
	EmailID   string    `json:"email_id,omitempty"`
	Recipient string    `json:"recipient"`
	Type      string    `json:"type"`
	Reason    string    `json:"reason,omitempty"`
	CreatedAt time.Time `json:"created_at"`
}

// BounceListResponse is the response body.
type BounceListResponse struct {
	Bounces    []*Bounce `json:"bounces"`
	NextCursor string    `json:"next_cursor"`
}

// Campaign is the wire body.
type Campaign struct {
	ID              string         `json:"id"`
	ProjectID       string         `json:"project_id"`
	CreatedBy       string         `json:"created_by,omitempty"`
	Name            string         `json:"name"`
	Subject         string         `json:"subject,omitempty"`
	FromEmail       string         `json:"from_email"`
	FromName        string         `json:"from_name,omitempty"`
	TemplateID      string         `json:"template_id"`
	Language        string         `json:"language,omitempty"`
	TemplateData    map[string]any `json:"template_data,omitempty"`
	Status          string         `json:"status"`
	ListID          string         `json:"list_id"`
	SMTPGroupID     string         `json:"smtp_group_id,omitempty"`
	SendRate        int64          `json:"send_rate"`
	SendAtLocalTime bool           `json:"send_at_local_time"`
	ABTestEnabled   bool           `json:"ab_test_enabled"`
	ABVariants      []Variant      `json:"ab_variants,omitempty"`
	ScheduledAt     *time.Time     `json:"scheduled_at,omitempty"`
	StartedAt       *time.Time     `json:"started_at,omitempty"`
	CompletedAt     *time.Time     `json:"completed_at,omitempty"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       *time.Time     `json:"updated_at,omitempty"`
}

// CampaignDetailResponse is the response body.
type CampaignDetailResponse struct {
	Campaign       *Campaign  `json:"campaign"`
	Stats          any        `json:"stats"`
	StatsByVariant any        `json:"stats_by_variant"`
	Engagement     Engagement `json:"engagement"`
}

// CampaignListResponse is the response body.
type CampaignListResponse struct {
	Campaigns []*Campaign `json:"campaigns"`
}

// CampaignResponse is the response body.
type CampaignResponse struct {
	Campaign *Campaign `json:"campaign"`
}

// CampaignUpsertInput is the request body.
type CampaignUpsertInput struct {
	Name            string         `json:"name"`
	Subject         string         `json:"subject"`
	FromEmail       string         `json:"from_email"`
	FromName        string         `json:"from_name"`
	TemplateID      string         `json:"template_id"`
	Language        string         `json:"language"`
	TemplateData    map[string]any `json:"template_data"`
	ListID          string         `json:"list_id"`
	SMTPGroup       string         `json:"smtp_group"`
	SendRate        int64          `json:"send_rate"`
	SendAtLocalTime bool           `json:"send_at_local_time"`
	ABTestEnabled   bool           `json:"ab_test_enabled"`
	ABVariants      []Variant      `json:"ab_variants"`
}

// CatalogResponse is the response body.
type CatalogResponse struct {
	Resources []Definition `json:"resources"`
	Actions   []string     `json:"actions"`
}

// Checks is the wire body.
type Checks struct {
	Syntax      bool   `json:"syntax"`
	MX          bool   `json:"mx"`
	Disposable  bool   `json:"disposable"`
	RoleAccount bool   `json:"role_account"`
	SMTP        string `json:"smtp"`
}

// Contact is the wire body.
type Contact struct {
	ID           string     `json:"id"`
	ProjectID    string     `json:"project_id"`
	Email        string     `json:"email"`
	Name         string     `json:"name,omitempty"`
	SentCount    int64      `json:"sent_count"`
	FailCount    int64      `json:"fail_count"`
	Suppressed   bool       `json:"suppressed"`
	LastSentAt   *time.Time `json:"last_sent_at,omitempty"`
	LastFailedAt *time.Time `json:"last_failed_at,omitempty"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

// ContactListResponse is the response body.
type ContactListResponse struct {
	Contacts []*Contact `json:"contacts"`
	Total    int64      `json:"total"`
	Limit    int64      `json:"limit"`
	Offset   int64      `json:"offset"`
}

// Counts is the wire body.
type Counts struct {
	SandboxMessages int64 `json:"sandbox_messages"`
	EmailsLastHour  int64 `json:"emails_last_hour"`
	EmailsLastDay   int64 `json:"emails_last_day"`
	APIKeys         int64 `json:"api_keys"`
	SMTPServers     int64 `json:"smtp_servers"`
	Domains         int64 `json:"domains"`
	Subscribers     int64 `json:"subscribers"`
}

// CreateInput is the request body.
type CreateInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Admin    bool   `json:"admin"`
}

// CreateResponse is the response body.
type CreateResponse struct {
	Suppression *Suppression `json:"suppression"`
}

// CreatedResponse is the response body.
type CreatedResponse struct {
	APIKey *Key   `json:"api_key"`
	Token  string `json:"token"`
}

// Credential is the wire body.
type Credential struct {
	ID          string     `json:"id"`
	ProjectID   string     `json:"project_id"`
	CreatedBy   string     `json:"created_by,omitempty"`
	Name        string     `json:"name"`
	Username    string     `json:"username"`
	AllowedIPs  []string   `json:"allowed_ips"`
	SMTPGroupID string     `json:"smtp_group_id,omitempty"`
	Sandbox     bool       `json:"sandbox"`
	Revoked     bool       `json:"revoked"`
	LastUsedAt  *time.Time `json:"last_used_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`
}

// CredentialCreatedResponse is the response body.
type CredentialCreatedResponse struct {
	SMTPCredential *Credential         `json:"smtp_credential"`
	Password       string              `json:"password"`
	Submission     SandboxListenerInfo `json:"submission"`
}

// CredentialInput is the request body.
type CredentialInput struct {
	Name string `json:"name"`
}

// CredentialListResponse is the response body.
type CredentialListResponse struct {
	SMTPCredentials []*Credential       `json:"smtp_credentials"`
	Submission      SandboxListenerInfo `json:"submission"`
}

// CredentialResponse is the response body.
type CredentialResponse struct {
	SMTPCredential *Credential `json:"smtp_credential"`
}

// DataExportResponse is the response body.
type DataExportResponse struct {
	Export *Export `json:"export"`
}

// DayCount is the wire body.
type DayCount struct {
	Date  string `json:"date"`
	Count int64  `json:"count"`
}

// DeclinedResponse is the response body.
type DeclinedResponse struct {
	Declined bool `json:"declined"`
}

// DefaultRoleInput is the request body.
type DefaultRoleInput struct {
	RoleID string `json:"role_id"`
}

// Definition is the wire body.
type Definition struct {
	Resource       string   `json:"resource"`
	Label          string   `json:"label"`
	Description    string   `json:"description"`
	Actions        []string `json:"actions"`
	Infrastructure bool     `json:"infrastructure"`
}

// DeleteContactsInput is the request body.
type DeleteContactsInput struct {
	Email      string `json:"email"`
	ConfirmAll bool   `json:"confirm_all"`
}

// DeleteLogsInput is the request body.
type DeleteLogsInput struct {
	OlderThanDays int64  `json:"older_than_days"`
	Email         string `json:"email"`
	ConfirmAll    bool   `json:"confirm_all"`
}

// DeleteResponse is the response body.
type DeleteResponse struct {
	Deleted int64 `json:"deleted"`
}

// DeletedResponse is the response body.
type DeletedResponse struct {
	Deleted bool `json:"deleted"`
}

// DeliveriesResponse is the response body.
type DeliveriesResponse struct {
	Deliveries []*Delivery `json:"deliveries"`
	NextCursor string      `json:"next_cursor"`
}

// Delivery is the wire body.
type Delivery struct {
	ID           string    `json:"id"`
	WebhookID    string    `json:"webhook_id"`
	ProjectID    string    `json:"project_id"`
	Event        string    `json:"event"`
	Status       string    `json:"status"`
	HTTPStatus   int64     `json:"http_status,omitzero"`
	ErrorMessage string    `json:"error_message,omitempty"`
	Attempt      int64     `json:"attempt"`
	CreatedAt    time.Time `json:"created_at"`
}

// Descriptor is the wire body.
type Descriptor struct {
	ID             string        `json:"id"`
	Label          string        `json:"label"`
	Dial           bool          `json:"dial"`
	Options        []OptionField `json:"options,omitempty"`
	CredentialHint string        `json:"credential_hint,omitempty"`
	ReSigns        bool          `json:"re_signs"`
}

// DetailResponse is the response body.
type DetailResponse struct {
	Domain     *Domain  `json:"domain"`
	DNSRecords []Record `json:"dns_records"`
}

// Details is the wire body.
type Details struct {
	Subject        string    `json:"subject"`
	Issuer         string    `json:"issuer"`
	DNSNames       []string  `json:"dns_names,omitempty"`
	NotBefore      time.Time `json:"not_before"`
	NotAfter       time.Time `json:"not_after"`
	Serial         string    `json:"serial"`
	Fingerprint    string    `json:"fingerprint"`
	KeyAlgo        string    `json:"key_algorithm"`
	SelfSigned     bool      `json:"self_signed"`
	IsCA           bool      `json:"is_ca"`
	SubjectKeyID   string    `json:"subject_key_id,omitempty"`
	AuthorityKeyID string    `json:"authority_key_id,omitempty"`
	Chain          int64     `json:"chain_length"`
}

// Domain is the wire body.
type Domain struct {
	ID                string     `json:"id"`
	ProjectID         string     `json:"project_id"`
	CreatedBy         string     `json:"created_by,omitempty"`
	Domain            string     `json:"domain"`
	VerificationToken string     `json:"verification_token"`
	Verified          bool       `json:"verified"`
	VerifiedAt        *time.Time `json:"verified_at,omitempty"`
	CreatedAt         time.Time  `json:"created_at"`
	DKIMSelector      string     `json:"dkim_selector,omitempty"`
	DKIMPublicKey     string     `json:"dkim_public_key,omitempty"`
	SPFVerified       bool       `json:"spf_verified"`
	DKIMVerified      bool       `json:"dkim_verified"`
	DMARCVerified     bool       `json:"dmarc_verified"`
	CheckedAt         *time.Time `json:"checked_at,omitempty"`
}

// DomainsCreateInput is the request body.
type DomainsCreateInput struct {
	Domain string `json:"domain"`
}

// DomainsListResponse is the response body.
type DomainsListResponse struct {
	Domains []*Domain `json:"domains"`
}

// Email is the wire body.
type Email struct {
	ID                    string            `json:"id"`
	ProjectID             string            `json:"project_id"`
	CreatedBy             string            `json:"created_by,omitempty"`
	APIKeyID              string            `json:"api_key_id,omitempty"`
	SMTPServerID          string            `json:"smtp_server_id,omitempty"`
	DeliveredVia          string            `json:"delivered_via,omitempty"`
	SMTPGroupID           string            `json:"smtp_group_id,omitempty"`
	Sender                string            `json:"sender"`
	Recipients            []string          `json:"recipients"`
	Subject               string            `json:"subject"`
	TemplateName          string            `json:"template_name,omitempty"`
	HTMLBody              string            `json:"html_body,omitempty"`
	TextBody              string            `json:"text_body,omitempty"`
	Attachments           []Attachment      `json:"attachments,omitempty"`
	Headers               map[string]string `json:"headers,omitempty"`
	ListUnsubscribeURL    string            `json:"list_unsubscribe_url,omitempty"`
	ListUnsubscribeMailto string            `json:"list_unsubscribe_mailto,omitempty"`
	UnsubscribeListID     string            `json:"unsubscribe_list_id,omitempty"`
	Tracked               bool              `json:"tracked"`
	OpenedAt              *time.Time        `json:"opened_at,omitempty"`
	ClickedAt             *time.Time        `json:"clicked_at,omitempty"`
	OpenCount             int64             `json:"open_count"`
	ClickCount            int64             `json:"click_count"`
	ListUnsubscribePost   bool              `json:"list_unsubscribe_post,omitzero"`
	Status                string            `json:"status"`
	ErrorMessage          string            `json:"error_message,omitempty"`
	Attempts              int64             `json:"attempts"`
	MaxAttempts           int64             `json:"max_attempts"`
	NextAttemptAt         *time.Time        `json:"next_attempt_at,omitempty"`
	CreatedAt             time.Time         `json:"created_at"`
	ScheduledAt           *time.Time        `json:"scheduled_at,omitempty"`
	SentAt                *time.Time        `json:"sent_at,omitempty"`
}

// EmailListResponse is the response body.
type EmailListResponse struct {
	Emails []*Email `json:"emails"`
}

// EmailResponse is the response body.
type EmailResponse struct {
	Email *Email `json:"email"`
}

// EmailSendInput is the request body.
type EmailSendInput struct {
	From                  string            `json:"from"`
	To                    []string          `json:"to"`
	Subject               string            `json:"subject"`
	HTML                  string            `json:"html"`
	Text                  string            `json:"text"`
	Headers               map[string]string `json:"headers"`
	Attachments           []Attachment      `json:"attachments"`
	SendAt                string            `json:"send_at"`
	DryRun                bool              `json:"dry_run"`
	UnsubscribeListID     string            `json:"unsubscribe_list_id"`
	ListUnsubscribeURL    string            `json:"list_unsubscribe_url"`
	ListUnsubscribeMailto string            `json:"list_unsubscribe_mailto"`
	ListUnsubscribePost   bool              `json:"list_unsubscribe_post"`
	SMTPGroup             string            `json:"smtp_group"`
	DisableTracking       bool              `json:"disable_tracking"`
	SMTPServerID          string            `json:"smtp_server_id"`
	Sandbox               *bool             `json:"sandbox"`
	SandboxRetentionDays  int64             `json:"sandbox_retention_days"`
}

// EmailStatsResponse is the response body.
type EmailStatsResponse struct {
	Counts map[string]int64 `json:"counts"`
}

// EmailStatusResponse is the response body.
type EmailStatusResponse struct {
	ID           string     `json:"id"`
	Status       string     `json:"status"`
	Attempts     int64      `json:"attempts"`
	ErrorMessage string     `json:"error_message"`
	SentAt       *time.Time `json:"sent_at"`
}

// EmittedResponse is the response body.
type EmittedResponse struct {
	Emitted bool `json:"emitted"`
}

// Engagement is the wire body.
type Engagement struct {
	Opened    int64   `json:"opened"`
	Clicked   int64   `json:"clicked"`
	Sent      int64   `json:"sent"`
	OpenRate  float64 `json:"open_rate"`
	ClickRate float64 `json:"click_rate"`
}

// ErasureResponse is the response body.
type ErasureResponse struct {
	Deleted int64  `json:"deleted"`
	Message string `json:"message"`
}

// Event is the wire body.
type Event struct {
	ID         string    `json:"id"`
	Category   string    `json:"category"`
	Type       string    `json:"type"`
	ProjectID  string    `json:"project_id,omitempty"`
	ActorID    string    `json:"actor_id,omitempty"`
	ActorEmail string    `json:"actor_email,omitempty"`
	ClientIP   string    `json:"client_ip,omitempty"`
	UserAgent  string    `json:"user_agent,omitempty"`
	Method     string    `json:"method,omitempty"`
	Path       string    `json:"path,omitempty"`
	Status     int64     `json:"status,omitzero"`
	Detail     string    `json:"detail,omitempty"`
	CreatedAt  time.Time `json:"created_at"`
}

// EventResponse is the response body.
type EventResponse struct {
	Event *Event `json:"event"`
}

// Export is the wire body.
type Export struct {
	MailyardVersion  string    `json:"mailyard_version"`
	ExportedAt       time.Time `json:"exported_at"`
	Project          any       `json:"project"`
	Templates        []any     `json:"templates"`
	Stylesheets      []any     `json:"stylesheets"`
	Languages        []any     `json:"languages"`
	Contacts         []any     `json:"contacts"`
	Subscribers      []any     `json:"subscribers"`
	SubscriberLists  []any     `json:"subscriber_lists"`
	Suppressions     []any     `json:"suppressions"`
	UnsubscribeLists []any     `json:"unsubscribe_lists"`
	Webhooks         []any     `json:"webhooks"`
	SMTPServers      []any     `json:"smtp_servers"`
	Domains          []any     `json:"domains"`
	Senders          []any     `json:"senders"`
	Truncated        []string  `json:"truncated"`
}

// ExportResponse is the response body.
type ExportResponse struct {
	Events    []*Event  `json:"events"`
	From      time.Time `json:"from"`
	To        time.Time `json:"to"`
	Count     int64     `json:"count"`
	Truncated bool      `json:"truncated"`
	Cap       int64     `json:"cap"`
}

// FilterRule is the wire body.
type FilterRule struct {
	Field    string `json:"field"`
	Operator string `json:"operator"`
	Value    any    `json:"value"`
}

// GenerateCAInput is the request body.
type GenerateCAInput struct {
	Name         string        `json:"name"`
	Subject      SubjectFields `json:"subject"`
	Algorithm    string        `json:"algorithm"`
	ValidityDays int64         `json:"validity_days"`
}

// GenerateInput is the request body.
type GenerateInput struct {
	Name         string        `json:"name"`
	Hosts        []string      `json:"hosts"`
	Subject      SubjectFields `json:"subject"`
	Algorithm    string        `json:"algorithm"`
	Issuer       string        `json:"issuer"`
	ValidityDays int64         `json:"validity_days"`
}

// GetResponse is the response body.
type GetResponse struct {
	Contact *Contact `json:"contact"`
}

// Group is the wire body.
type Group struct {
	ID          string    `json:"id"`
	ProjectID   string    `json:"project_id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description string    `json:"description,omitempty"`
	Default     bool      `json:"is_default"`
	CreatedAt   time.Time `json:"created_at"`
	Servers     []*Server `json:"servers,omitempty"`
}

// GroupCreateInput is the request body.
type GroupCreateInput struct {
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
}

// GroupListResponse is the response body.
type GroupListResponse struct {
	Groups []*Group `json:"smtp_server_groups"`
}

// GroupResponse is the response body.
type GroupResponse struct {
	Group *Group `json:"smtp_server_group"`
}

// GroupUpdateInput is the request body.
type GroupUpdateInput struct {
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	Description *string `json:"description"`
	MakeDefault bool    `json:"make_default"`
}

// ImportInput is the request body.
type ImportInput struct {
	Subscribers []SubscriberUpsertInput `json:"subscribers"`
}

// ImportResponse is the response body.
type ImportResponse struct {
	Created int64            `json:"created"`
	Updated int64            `json:"updated"`
	Skipped int64            `json:"skipped"`
	Errors  []map[string]any `json:"errors"`
}

// InboundAttachment is the wire body.
type InboundAttachment struct {
	Filename    string `json:"filename"`
	ContentType string `json:"content_type,omitempty"`
	Size        int64  `json:"size"`
	Content     string `json:"content,omitempty"`
	StorageKey  string `json:"storage_key,omitempty"`
}

// InboundEmail is the wire body.
type InboundEmail struct {
	ID           string              `json:"id"`
	ProjectID    string              `json:"project_id"`
	DomainID     string              `json:"domain_id"`
	MessageID    string              `json:"message_id,omitempty"`
	Sender       string              `json:"sender"`
	Recipients   []string            `json:"recipients"`
	Subject      string              `json:"subject,omitempty"`
	TextBody     string              `json:"text_body,omitempty"`
	HTMLBody     string              `json:"html_body,omitempty"`
	Headers      map[string]string   `json:"headers,omitempty"`
	Attachments  []InboundAttachment `json:"attachments,omitempty"`
	HasRaw       bool                `json:"has_raw,omitzero"`
	Size         int64               `json:"size"`
	Auth         *Auth               `json:"auth,omitempty"`
	Status       string              `json:"status"`
	ErrorMessage string              `json:"error_message,omitempty"`
	ReceivedAt   time.Time           `json:"received_at"`
	CreatedAt    time.Time           `json:"created_at"`
}

// InboundGetResponse is the response body.
type InboundGetResponse struct {
	InboundEmail *InboundEmail `json:"inbound_email"`
}

// InboundListResponse is the response body.
type InboundListResponse struct {
	InboundEmails []*InboundEmail `json:"inbound_emails"`
}

// InboundStatsResponse is the response body.
type InboundStatsResponse struct {
	Counts map[string]int64 `json:"counts"`
}

// IngestInput is the request body.
type IngestInput struct {
	Recipient string `json:"recipient"`
	EmailID   string `json:"email_id"`
	Type      string `json:"type"`
	Reason    string `json:"reason"`
}

// IngestResponse is the response body.
type IngestResponse struct {
	Bounce     *Bounce `json:"bounce"`
	Suppressed bool    `json:"suppressed"`
}

// Invitation is the wire body.
type Invitation struct {
	ID        string    `json:"id"`
	ProjectID string    `json:"project_id"`
	Email     string    `json:"email"`
	RoleID    string    `json:"role_id,omitempty"`
	RoleName  string    `json:"role_name,omitempty"`
	Status    string    `json:"status"`
	InvitedBy string    `json:"invited_by"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

// InvitationCreatedResponse is the response body.
type InvitationCreatedResponse struct {
	Invitation *Invitation `json:"invitation"`
	Token      string      `json:"token"`
	Emailed    bool        `json:"emailed"`
}

// InvitationListResponse is the response body.
type InvitationListResponse struct {
	Invitations []*Invitation `json:"invitations"`
}

// InviteInput is the request body.
type InviteInput struct {
	Email  string `json:"email"`
	RoleID string `json:"role_id"`
}

// JobsResponse is the response body.
type JobsResponse struct {
	Jobs []Status `json:"jobs"`
}

// JoinedResponse is the response body.
type JoinedResponse struct {
	Project *Project `json:"project"`
	Member  *Member  `json:"member"`
}

// Key is the wire body.
type Key struct {
	ID          string     `json:"id"`
	ProjectID   string     `json:"project_id"`
	CreatedBy   string     `json:"created_by,omitempty"`
	Name        string     `json:"name"`
	KeyPrefix   string     `json:"key_prefix"`
	Permissions []string   `json:"permissions"`
	AllowedIPs  []string   `json:"allowed_ips"`
	Sandbox     bool       `json:"sandbox"`
	Revoked     bool       `json:"revoked"`
	ExpiresAt   *time.Time `json:"expires_at,omitempty"`
	LastUsedAt  *time.Time `json:"last_used_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`
}

// Language is the wire body.
type Language struct {
	ID        string    `json:"id"`
	ProjectID string    `json:"project_id"`
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	IsDefault bool      `json:"is_default"`
	CreatedAt time.Time `json:"created_at"`
}

// LanguageListResponse is the response body.
type LanguageListResponse struct {
	Languages []*Language `json:"languages"`
}

// LanguageResponse is the response body.
type LanguageResponse struct {
	Language *Language `json:"language"`
}

// LanguageUpsertInput is the request body.
type LanguageUpsertInput struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	IsDefault bool   `json:"is_default"`
}

// LimitsResponse is the response body.
type LimitsResponse struct {
	Limits SendingLimits `json:"limits"`
}

// List is the wire body.
type List struct {
	ID          string       `json:"id"`
	ProjectID   string       `json:"project_id"`
	Name        string       `json:"name"`
	Description string       `json:"description,omitempty"`
	Type        string       `json:"type"`
	FilterRules []FilterRule `json:"filter_rules"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   *time.Time   `json:"updated_at,omitempty"`
}

// ListDetailResponse is the response body.
type ListDetailResponse struct {
	SubscriberList *List  `json:"subscriber_list"`
	MemberCount    *int64 `json:"member_count,omitempty"`
}

// ListEmailInput is the request body.
type ListEmailInput struct {
	Email  string `json:"email"`
	Reason string `json:"reason"`
}

// ListOutput is the response body.
type ListOutput struct {
	Nodes       []NodeView `json:"relay_nodes"`
	SPFInclude  string     `json:"spf_include"`
	MXHosts     []string   `json:"mx_hosts"`
	AutoApprove bool       `json:"auto_approve"`
	Enabled     bool       `json:"enabled"`
	Available   bool       `json:"available"`
}

// ListResponse is the response body.
type ListResponse struct {
	Certificates []Managed       `json:"certificates"`
	Listeners    []ListenerState `json:"listeners"`
}

// ListenerInfo is the wire body.
type ListenerInfo struct {
	Enabled  bool   `json:"enabled"`
	Host     string `json:"host"`
	Port     string `json:"port"`
	STARTTLS bool   `json:"starttls"`
}

// ListenerState is the wire body.
type ListenerState struct {
	Listener      string   `json:"listener"`
	TLS           bool     `json:"tls"`
	Assigned      string   `json:"assigned,omitempty"`
	Serving       string   `json:"serving"`
	ServingNames  []string `json:"serving_names,omitempty"`
	Fallback      string   `json:"fallback"`
	FallbackNames []string `json:"fallback_names,omitempty"`
}

// Localization is the wire body.
type Localization struct {
	ID        string     `json:"id"`
	VersionID string     `json:"version_id"`
	Language  string     `json:"language"`
	Subject   string     `json:"subject"`
	HTML      string     `json:"html,omitempty"`
	Text      string     `json:"text,omitempty"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// LocalizationInput is the request body.
type LocalizationInput struct {
	Language string `json:"language"`
	Subject  string `json:"subject"`
	HTML     string `json:"html"`
	Text     string `json:"text"`
}

// LocalizationListResponse is the response body.
type LocalizationListResponse struct {
	Localizations []*Localization `json:"localizations"`
}

// LocalizationResponse is the response body.
type LocalizationResponse struct {
	Localization *Localization `json:"localization"`
}

// Managed is the wire body.
type Managed struct {
	Name      string   `json:"name"`
	Details   *Details `json:"details,omitempty"`
	UsedBy    []string `json:"used_by,omitempty"`
	Dormant   []string `json:"dormant,omitempty"`
	CreatedAt string   `json:"created_at"`
	UpdatedAt string   `json:"updated_at"`
}

// ManagedResponse is the response body.
type ManagedResponse struct {
	Certificate Managed `json:"certificate"`
}

// MarkedResponse is the response body.
type MarkedResponse struct {
	Marked int64 `json:"marked"`
}

// Member is the wire body.
type Member struct {
	ID            string    `json:"id"`
	ProjectID     string    `json:"project_id"`
	UserID        string    `json:"user_id"`
	Email         string    `json:"email,omitempty"`
	Owner         bool      `json:"owner"`
	RoleID        string    `json:"role_id,omitempty"`
	RoleName      string    `json:"role_name,omitempty"`
	InheritedRole bool      `json:"inherited_role,omitzero"`
	CreatedAt     time.Time `json:"created_at"`
}

// MemberInput is the request body.
type MemberInput struct {
	Email  string `json:"email"`
	RoleID string `json:"role_id"`
}

// MemberListResponse is the response body.
type MemberListResponse struct {
	Members []*Member `json:"members"`
}

// MemberResponse is the response body.
type MemberResponse struct {
	Member *Member `json:"member"`
}

// MemberRoleInput is the request body.
type MemberRoleInput struct {
	RoleID *string `json:"role_id"`
	Owner  *bool   `json:"owner"`
}

// MembershipChange is the wire body.
type MembershipChange struct {
	Unsubscribed bool   `json:"unsubscribed,omitzero"`
	Resubscribed bool   `json:"resubscribed,omitzero"`
	ListID       string `json:"list_id"`
	Email        string `json:"email"`
}

// Message is the wire body.
type Message struct {
	ID           string     `json:"id"`
	CampaignID   string     `json:"campaign_id"`
	SubscriberID string     `json:"subscriber_id"`
	Email        string     `json:"email,omitempty"`
	EmailID      string     `json:"email_id,omitempty"`
	Status       string     `json:"status"`
	ErrorMessage string     `json:"error_message,omitempty"`
	Variant      string     `json:"variant,omitempty"`
	DeliverAt    *time.Time `json:"deliver_at,omitempty"`
	SentAt       *time.Time `json:"sent_at,omitempty"`
	OpenedAt     *time.Time `json:"opened_at,omitempty"`
	ClickedAt    *time.Time `json:"clicked_at,omitempty"`
	CreatedAt    time.Time  `json:"created_at"`
}

// MessageListResponse is the response body.
type MessageListResponse struct {
	Messages []*Message `json:"messages"`
}

// MessageResponse is the response body.
type MessageResponse struct {
	Message string `json:"message"`
}

// NodeView is the wire body.
type NodeView struct {
	ID             string     `json:"id"`
	ProjectID      string     `json:"project_id,omitempty"`
	ServerID       string     `json:"server_id"`
	Name           string     `json:"name"`
	Version        string     `json:"version,omitempty"`
	PublicIP       string     `json:"public_ip,omitempty"`
	LastSeenAt     *time.Time `json:"last_seen_at,omitempty"`
	CreatedAt      time.Time  `json:"created_at"`
	InboundEnabled bool       `json:"inbound_enabled"`
	InboundQueued  int64      `json:"inbound_queued"`
	LastInboundAt  *time.Time `json:"last_inbound_at,omitempty"`
	Host           string     `json:"host"`
	Port           int64      `json:"port"`
	Status         string     `json:"status"`
	Alive          bool       `json:"alive"`
}

// Notification is the wire body.
type Notification struct {
	ID        string     `json:"id"`
	ProjectID string     `json:"project_id"`
	Type      string     `json:"type"`
	Severity  string     `json:"severity"`
	Title     string     `json:"title"`
	Body      string     `json:"body,omitempty"`
	Link      string     `json:"link,omitempty"`
	ReadAt    *time.Time `json:"read_at,omitempty"`
	CreatedAt time.Time  `json:"created_at"`
}

// NotificationListResponse is the response body.
type NotificationListResponse struct {
	Notifications []*Notification `json:"notifications"`
	Unread        int64           `json:"unread"`
	Limit         int64           `json:"limit"`
	Offset        int64           `json:"offset"`
}

// OauthproviderListResponse is the response body.
type OauthproviderListResponse struct {
	Providers []ProviderView `json:"providers"`
}

// OptionField is the wire body.
type OptionField struct {
	Key      string `json:"key"`
	Label    string `json:"label"`
	Required bool   `json:"required"`
	Hint     string `json:"hint,omitempty"`
}

// Output is the response body.
type Output struct {
	Subject string `json:"subject"`
	HTML    string `json:"html"`
	Text    string `json:"text"`
}

// PEMResponse is the response body.
type PEMResponse struct {
	Name string `json:"name"`
	PEM  string `json:"pem"`
}

// PasskeyResetResponse is the response body.
type PasskeyResetResponse struct {
	Removed int64 `json:"removed"`
}

// Plan is the wire body.
type Plan struct {
	ID                      string     `json:"id"`
	Name                    string     `json:"name"`
	Description             string     `json:"description,omitempty"`
	IsDefault               bool       `json:"is_default"`
	HourlyEmailLimit        int64      `json:"hourly_email_limit"`
	DailyEmailLimit         int64      `json:"daily_email_limit"`
	MaxAPIKeys              int64      `json:"max_api_keys"`
	MaxSMTPServers          int64      `json:"max_smtp_servers"`
	MaxDomains              int64      `json:"max_domains"`
	MaxSubscribers          int64      `json:"max_subscribers"`
	MaxSandboxMessages      int64      `json:"max_sandbox_messages"`
	MaxSandboxRetentionDays int64      `json:"max_sandbox_retention_days"`
	CreatedAt               time.Time  `json:"created_at"`
	UpdatedAt               *time.Time `json:"updated_at,omitempty"`
}

// PlanListResponse is the response body.
type PlanListResponse struct {
	Plans []*Plan `json:"plans"`
}

// PlanResponse is the response body.
type PlanResponse struct {
	Plan *Plan `json:"plan"`
}

// PlanUpsertInput is the request body.
type PlanUpsertInput struct {
	Name                    string `json:"name"`
	Description             string `json:"description"`
	IsDefault               *bool  `json:"is_default"`
	HourlyEmailLimit        *int64 `json:"hourly_email_limit"`
	DailyEmailLimit         *int64 `json:"daily_email_limit"`
	MaxAPIKeys              *int64 `json:"max_api_keys"`
	MaxSMTPServers          *int64 `json:"max_smtp_servers"`
	MaxDomains              *int64 `json:"max_domains"`
	MaxSubscribers          *int64 `json:"max_subscribers"`
	MaxSandboxMessages      *int64 `json:"max_sandbox_messages"`
	MaxSandboxRetentionDays *int64 `json:"max_sandbox_retention_days"`
}

// PreviewInput is the request body.
type PreviewInput struct {
	FilterRules []FilterRule `json:"filter_rules"`
}

// PreviewResponse is the response body.
type PreviewResponse struct {
	Template string  `json:"template"`
	Preview  *Output `json:"preview"`
}

// Project is the wire body.
type Project struct {
	ID                   string     `json:"id"`
	Name                 string     `json:"name"`
	Slug                 string     `json:"slug"`
	Description          string     `json:"description,omitempty"`
	OwnerID              string     `json:"owner_id,omitempty"`
	DefaultLanguage      string     `json:"default_language"`
	PlanID               string     `json:"plan_id,omitempty"`
	DefaultRoleID        string     `json:"default_role_id,omitempty"`
	StrictSenders        bool       `json:"strict_senders"`
	TrackOpens           bool       `json:"track_opens"`
	TrackClicks          bool       `json:"track_clicks"`
	BounceAddress        string     `json:"bounce_address,omitempty"`
	AlertEmail           string     `json:"alert_email,omitempty"`
	SandboxRetentionDays int64      `json:"sandbox_retention_days"`
	CreatedAt            time.Time  `json:"created_at"`
	UpdatedAt            *time.Time `json:"updated_at,omitempty"`
}

// ProjectAccess is the wire body.
type ProjectAccess struct {
	Owner       bool     `json:"owner"`
	Permissions []string `json:"permissions"`
}

// ProjectAccessResponse is the response body.
type ProjectAccessResponse struct {
	Project     *Project `json:"project"`
	Owner       bool     `json:"owner"`
	Permissions []string `json:"permissions"`
}

// ProjectCreateInput is the request body.
type ProjectCreateInput struct {
	Name            string `json:"name"`
	Slug            string `json:"slug"`
	Description     string `json:"description"`
	DefaultLanguage string `json:"default_language"`
}

// ProjectListResponse is the response body.
type ProjectListResponse struct {
	Projects  []*Project               `json:"projects"`
	Access    map[string]ProjectAccess `json:"access"`
	CanCreate bool                     `json:"can_create"`
}

// ProjectResponse is the response body.
type ProjectResponse struct {
	Project *Project `json:"project"`
}

// ProjectUpdateInput is the request body.
type ProjectUpdateInput struct {
	Name                 string  `json:"name"`
	Description          *string `json:"description"`
	DefaultLanguage      string  `json:"default_language"`
	StrictSenders        *bool   `json:"strict_senders"`
	TrackOpens           *bool   `json:"track_opens"`
	TrackClicks          *bool   `json:"track_clicks"`
	BounceAddress        *string `json:"bounce_address"`
	AlertEmail           *string `json:"alert_email"`
	SandboxRetentionDays *int64  `json:"sandbox_retention_days"`
}

// ProjectsResponse is the response body.
type ProjectsResponse struct {
	Projects []*Project `json:"projects"`
}

// ProviderResponse is the response body.
type ProviderResponse struct {
	Provider ProviderView `json:"provider"`
}

// ProviderView is the wire body.
type ProviderView struct {
	ID                   string    `json:"id"`
	Name                 string    `json:"name"`
	Slug                 string    `json:"slug"`
	Type                 string    `json:"type"`
	ClientID             string    `json:"client_id"`
	HasSecret            bool      `json:"has_secret"`
	Issuer               string    `json:"issuer"`
	AuthURL              string    `json:"auth_url"`
	TokenURL             string    `json:"token_url"`
	UserInfoURL          string    `json:"userinfo_url"`
	Scopes               []string  `json:"scopes"`
	Enabled              bool      `json:"enabled"`
	Hidden               bool      `json:"hidden"`
	AutoRegister         bool      `json:"auto_register"`
	RequireEmailVerified bool      `json:"require_email_verified"`
	AllowedDomains       []string  `json:"allowed_domains"`
	AllowedEmails        []string  `json:"allowed_emails"`
	GroupsClaim          string    `json:"groups_claim"`
	AllowedGroups        []string  `json:"allowed_groups"`
	Usable               bool      `json:"usable"`
	CallbackURL          string    `json:"callback_url"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
}

// ReadResponse is the response body.
type ReadResponse struct {
	Read bool `json:"read"`
}

// Record is the wire body.
type Record struct {
	Kind     string `json:"kind"`
	Type     string `json:"type"`
	Host     string `json:"host"`
	Value    string `json:"value"`
	Required bool   `json:"required"`
	Verified bool   `json:"verified"`
	Detail   string `json:"detail,omitempty"`
}

// RenderLanguageResponse is the response body.
type RenderLanguageResponse struct {
	Preview  *Output `json:"preview"`
	Language string  `json:"language"`
}

// RenderPreviewInput is the request body.
type RenderPreviewInput struct {
	TemplateID   string         `json:"template_id"`
	TemplateName string         `json:"template_name"`
	Language     string         `json:"language"`
	Data         map[string]any `json:"data"`
}

// RenderResponse is the response body.
type RenderResponse struct {
	Preview *Output `json:"preview"`
}

// RenewInput is the request body.
type RenewInput struct {
	Host string `json:"host"`
}

// ResetAuthorityResponse is the response body.
type ResetAuthorityResponse struct {
	NodesUnenrolled int64  `json:"nodes_unenrolled"`
	Message         string `json:"message"`
}

// Result is the wire body.
type Result struct {
	Email             string    `json:"email"`
	Status            string    `json:"status"`
	Score             int64     `json:"score"`
	Checks            Checks    `json:"checks"`
	Reason            string    `json:"reason,omitempty"`
	MailboxVerified   bool      `json:"mailbox_verified"`
	Suppressed        bool      `json:"suppressed"`
	PreviouslyBounced bool      `json:"previously_bounced"`
	Cached            bool      `json:"cached"`
	CheckedAt         time.Time `json:"checked_at"`
}

// RetentionInfo is the wire body.
type RetentionInfo struct {
	RetentionDays int64 `json:"retention_days"`
	MaxMessages   int64 `json:"max_messages"`
}

// RevokedResponse is the response body.
type RevokedResponse struct {
	Revoked int64 `json:"revoked"`
}

// Role is the wire body.
type Role struct {
	ID          string     `json:"id"`
	ProjectID   string     `json:"project_id"`
	Name        string     `json:"name"`
	Description string     `json:"description,omitempty"`
	Permissions []string   `json:"permissions"`
	Members     int64      `json:"members"`
	Default     bool       `json:"default"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   *time.Time `json:"updated_at,omitempty"`
}

// RoleInput is the request body.
type RoleInput struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Permissions []string `json:"permissions"`
}

// RoleListResponse is the response body.
type RoleListResponse struct {
	Roles []*Role `json:"roles"`
}

// RoleResponse is the response body.
type RoleResponse struct {
	Role *Role `json:"role"`
}

// SandboxAttachment is the wire body.
type SandboxAttachment struct {
	Filename    string `json:"filename"`
	ContentType string `json:"content_type,omitempty"`
	Size        int64  `json:"size"`
}

// SandboxDeletedResponse is the response body.
type SandboxDeletedResponse struct {
	Deleted int64 `json:"deleted"`
}

// SandboxEmail is the wire body.
type SandboxEmail struct {
	ID           string              `json:"id"`
	ProjectID    string              `json:"project_id"`
	Source       string              `json:"source"`
	CredentialID string              `json:"credential_id,omitempty"`
	APIKeyID     string              `json:"api_key_id,omitempty"`
	Sender       string              `json:"sender"`
	Recipients   []string            `json:"recipients"`
	Subject      string              `json:"subject,omitempty"`
	TextBody     string              `json:"text_body,omitempty"`
	HTMLBody     string              `json:"html_body,omitempty"`
	Headers      map[string]string   `json:"headers,omitempty"`
	Attachments  []SandboxAttachment `json:"attachments,omitempty"`
	Size         int64               `json:"size"`
	ClientIP     string              `json:"client_ip,omitempty"`
	ExpiresAt    *time.Time          `json:"expires_at,omitempty"`
	ReceivedAt   time.Time           `json:"received_at"`
	CreatedAt    time.Time           `json:"created_at"`
}

// SandboxEmailResponse is the response body.
type SandboxEmailResponse struct {
	SandboxEmail *SandboxEmail `json:"sandbox_email"`
}

// SandboxListResponse is the response body.
type SandboxListResponse struct {
	SandboxEmails []*SandboxEmail `json:"sandbox_emails"`
	Total         int64           `json:"total"`
	Settings      RetentionInfo   `json:"settings"`
}

// SandboxListenerInfo is the wire body.
type SandboxListenerInfo struct {
	Enabled  bool   `json:"enabled"`
	Host     string `json:"host"`
	Port     string `json:"port"`
	STARTTLS bool   `json:"starttls"`
}

// SegmentPreviewResponse is the response body.
type SegmentPreviewResponse struct {
	Matched int64         `json:"matched"`
	Sample  []*Subscriber `json:"sample"`
}

// SendInput is the request body.
type SendInput struct {
	ScheduledAt string `json:"scheduled_at"`
}

// SendResponse is the response body.
type SendResponse struct {
	Email      *Email   `json:"email"`
	Suppressed []string `json:"suppressed_recipients"`
}

// Sender is the wire body.
type Sender struct {
	ID        string    `json:"id"`
	ProjectID string    `json:"project_id"`
	CreatedBy string    `json:"created_by,omitempty"`
	Email     string    `json:"email"`
	Name      string    `json:"name,omitempty"`
	CreatedAt time.Time `json:"created_at"`
}

// SenderCreateInput is the request body.
type SenderCreateInput struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

// SenderListResponse is the response body.
type SenderListResponse struct {
	Senders []*Sender `json:"senders"`
}

// SenderResponse is the response body.
type SenderResponse struct {
	Sender *Sender `json:"sender"`
}

// SendingLimits is the wire body.
type SendingLimits struct {
	MaxRecipients          int64 `json:"max_recipients"`
	MaxAttachments         int64 `json:"max_attachments"`
	MaxAttachmentSize      int64 `json:"max_attachment_size"`
	MaxTotalAttachmentSize int64 `json:"max_total_attachment_size"`
}

// Server is the wire body.
type Server struct {
	ID              string            `json:"id"`
	ProjectID       string            `json:"project_id,omitempty"`
	CreatedBy       string            `json:"created_by,omitempty"`
	Name            string            `json:"name"`
	Host            string            `json:"host"`
	Port            int64             `json:"port"`
	Username        string            `json:"username,omitempty"`
	Encryption      string            `json:"encryption"`
	SkipDKIM        bool              `json:"skip_dkim"`
	AllowedEmails   []string          `json:"allowed_emails"`
	AllowedDomains  []string          `json:"allowed_domains"`
	GroupID         string            `json:"group_id,omitempty"`
	Priority        int64             `json:"priority"`
	Status          string            `json:"status"`
	ValidationError string            `json:"validation_error,omitempty"`
	ValidatedAt     *time.Time        `json:"validated_at,omitempty"`
	CreatedAt       time.Time         `json:"created_at"`
	SESTopicARN     string            `json:"ses_topic_arn,omitempty"`
	NodeID          string            `json:"node_id,omitempty"`
	LastSeenAt      *time.Time        `json:"last_seen_at,omitempty"`
	Provider        string            `json:"provider,omitempty"`
	ProviderConfig  map[string]string `json:"provider_config,omitempty"`
}

// ServerResponse is the response body.
type ServerResponse struct {
	SMTPServer *Server `json:"smtp_server"`
}

// SettingInput is the request body.
type SettingInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// SettingItem is the wire body.
type SettingItem struct {
	Key         string     `json:"key"`
	Type        string     `json:"type"`
	Default     string     `json:"default"`
	Description string     `json:"description"`
	Value       string     `json:"value"`
	Overridden  bool       `json:"overridden"`
	Unit        string     `json:"unit,omitempty"`
	ManagedAt   string     `json:"managed_at,omitempty"`
	ManagedIn   string     `json:"managed_in,omitempty"`
	Edition     string     `json:"edition,omitempty"`
	UpdatedAt   *time.Time `json:"updated_at,omitempty"`
	UpdatedBy   string     `json:"updated_by,omitempty"`
}

// SettingListResponse is the response body.
type SettingListResponse struct {
	Settings []SettingItem `json:"settings"`
}

// SettingsResponse is the response body.
type SettingsResponse struct {
	Submission    SubmissionInfo `json:"submission"`
	RetentionDays int64          `json:"retention_days"`
	MaxMessages   int64          `json:"max_messages"`
	SandboxOnly   bool           `json:"sandbox_only"`
}

// Shared is the wire body.
type Shared struct {
	ID              string            `json:"id"`
	ProjectID       string            `json:"project_id,omitempty"`
	CreatedBy       string            `json:"created_by,omitempty"`
	Name            string            `json:"name"`
	Host            string            `json:"host"`
	Port            int64             `json:"port"`
	Username        string            `json:"username,omitempty"`
	Encryption      string            `json:"encryption"`
	SkipDKIM        bool              `json:"skip_dkim"`
	AllowedEmails   []string          `json:"allowed_emails"`
	AllowedDomains  []string          `json:"allowed_domains"`
	GroupID         string            `json:"group_id,omitempty"`
	Priority        int64             `json:"priority"`
	Status          string            `json:"status"`
	ValidationError string            `json:"validation_error,omitempty"`
	ValidatedAt     *time.Time        `json:"validated_at,omitempty"`
	CreatedAt       time.Time         `json:"created_at"`
	SESTopicARN     string            `json:"ses_topic_arn,omitempty"`
	NodeID          string            `json:"node_id,omitempty"`
	LastSeenAt      *time.Time        `json:"last_seen_at,omitempty"`
	Provider        string            `json:"provider,omitempty"`
	ProviderConfig  map[string]string `json:"provider_config,omitempty"`
	SecurityMode    string            `json:"security_mode"`
	PlatformOnly    bool              `json:"platform_only"`
}

// SharedCreateInput is the request body.
type SharedCreateInput struct {
	Name           string            `json:"name"`
	Provider       string            `json:"provider"`
	Host           string            `json:"host"`
	Port           int64             `json:"port"`
	Username       string            `json:"username"`
	Password       string            `json:"password"`
	Encryption     string            `json:"encryption"`
	SkipDKIM       bool              `json:"skip_dkim"`
	SESTopicARN    string            `json:"ses_topic_arn"`
	AllowedEmails  []string          `json:"allowed_emails"`
	AllowedDomains []string          `json:"allowed_domains"`
	SecurityMode   string            `json:"security_mode"`
	Priority       int64             `json:"priority"`
	PlatformOnly   bool              `json:"platform_only"`
	ProviderConfig map[string]string `json:"provider_config"`
}

// SharedListResponse is the response body.
type SharedListResponse struct {
	SharedSMTPServers []*Shared    `json:"shared_smtp_servers"`
	Providers         []Descriptor `json:"providers"`
}

// SharedResponse is the response body.
type SharedResponse struct {
	SharedSMTPServer *Shared `json:"shared_smtp_server"`
}

// SharedTestResponse is the response body.
type SharedTestResponse struct {
	Ok          bool       `json:"ok"`
	Status      string     `json:"status"`
	ValidatedAt *time.Time `json:"validated_at"`
}

// SharedUpdateInput is the request body.
type SharedUpdateInput struct {
	Name           string             `json:"name"`
	Host           string             `json:"host"`
	Port           int64              `json:"port"`
	Username       *string            `json:"username"`
	Password       *string            `json:"password"`
	Encryption     string             `json:"encryption"`
	SkipDKIM       *bool              `json:"skip_dkim"`
	SESTopicARN    *string            `json:"ses_topic_arn"`
	AllowedEmails  *[]string          `json:"allowed_emails"`
	AllowedDomains *[]string          `json:"allowed_domains"`
	SecurityMode   string             `json:"security_mode"`
	Priority       *int64             `json:"priority"`
	Status         string             `json:"status"`
	PlatformOnly   *bool              `json:"platform_only"`
	ProviderConfig *map[string]string `json:"provider_config"`
}

// SmtpcredentialCreateInput is the request body.
type SmtpcredentialCreateInput struct {
	Name       string   `json:"name"`
	AllowedIPs []string `json:"allowed_ips"`
	SMTPGroup  string   `json:"smtp_group"`
	Sandbox    bool     `json:"sandbox"`
}

// SmtpcredentialCreatedResponse is the response body.
type SmtpcredentialCreatedResponse struct {
	SMTPCredential *Credential  `json:"smtp_credential"`
	Password       string       `json:"password"`
	Submission     ListenerInfo `json:"submission"`
}

// SmtpcredentialCredentialResponse is the response body.
type SmtpcredentialCredentialResponse struct {
	SMTPCredential *Credential `json:"smtp_credential"`
}

// SmtpcredentialListResponse is the response body.
type SmtpcredentialListResponse struct {
	SMTPCredentials []*Credential `json:"smtp_credentials"`
	Submission      ListenerInfo  `json:"submission"`
}

// SmtpserverCreateInput is the request body.
type SmtpserverCreateInput struct {
	Name           string            `json:"name"`
	Provider       string            `json:"provider"`
	Host           string            `json:"host"`
	Port           int64             `json:"port"`
	Username       string            `json:"username"`
	Password       string            `json:"password"`
	Encryption     string            `json:"encryption"`
	SkipDKIM       bool              `json:"skip_dkim"`
	ProviderConfig map[string]string `json:"provider_config"`
	SESTopicARN    string            `json:"ses_topic_arn"`
	AllowedEmails  []string          `json:"allowed_emails"`
	AllowedDomains []string          `json:"allowed_domains"`
	GroupID        string            `json:"group_id"`
	Priority       int64             `json:"priority"`
}

// SmtpserverListResponse is the response body.
type SmtpserverListResponse struct {
	SMTPServers []*Server    `json:"smtp_servers"`
	Providers   []Descriptor `json:"providers"`
}

// SmtpserverTestResponse is the response body.
type SmtpserverTestResponse struct {
	Ok    bool   `json:"ok"`
	Error string `json:"error,omitempty"`
}

// SmtpserverUpdateInput is the request body.
type SmtpserverUpdateInput struct {
	Name           string             `json:"name"`
	Host           string             `json:"host"`
	Port           int64              `json:"port"`
	Username       *string            `json:"username"`
	Password       *string            `json:"password"`
	Encryption     string             `json:"encryption"`
	SkipDKIM       *bool              `json:"skip_dkim"`
	SESTopicARN    *string            `json:"ses_topic_arn"`
	AllowedEmails  *[]string          `json:"allowed_emails"`
	AllowedDomains *[]string          `json:"allowed_domains"`
	GroupID        string             `json:"group_id"`
	Priority       *int64             `json:"priority"`
	ProviderConfig *map[string]string `json:"provider_config"`
}

// StatsResponse is the response body.
type StatsResponse struct {
	Stats *Summary `json:"stats"`
}

// Status is the wire body.
type Status struct {
	Name           string     `json:"name"`
	Schedule       string     `json:"schedule"`
	Running        bool       `json:"running"`
	LastRunAt      *time.Time `json:"last_run_at"`
	LastError      string     `json:"last_error"`
	NextRunAt      *time.Time `json:"next_run_at"`
	LastDurationMS int64      `json:"last_duration_ms"`
}

// StatusResponse is the response body.
type StatusResponse struct {
	Status string `json:"status"`
}

// Stylesheet is the wire body.
type Stylesheet struct {
	ID        string     `json:"id"`
	ProjectID string     `json:"project_id"`
	Name      string     `json:"name"`
	CSS       string     `json:"css"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// StylesheetListResponse is the response body.
type StylesheetListResponse struct {
	Stylesheets []*Stylesheet `json:"stylesheets"`
}

// StylesheetResponse is the response body.
type StylesheetResponse struct {
	Stylesheet *Stylesheet `json:"stylesheet"`
}

// StylesheetUpsertInput is the request body.
type StylesheetUpsertInput struct {
	Name string `json:"name"`
	CSS  string `json:"css"`
}

// SubjectFields is the wire body.
type SubjectFields struct {
	CommonName   string `json:"common_name"`
	Organization string `json:"organization"`
	Unit         string `json:"unit"`
	Country      string `json:"country"`
	State        string `json:"state"`
	Locality     string `json:"locality"`
}

// SubmissionInfo is the wire body.
type SubmissionInfo struct {
	Enabled  bool   `json:"enabled"`
	Host     string `json:"host"`
	Addr     string `json:"addr"`
	STARTTLS bool   `json:"starttls"`
}

// SubscribeInput is the request body.
type SubscribeInput struct {
	ListID       string         `json:"list_id"`
	Email        string         `json:"email"`
	Name         string         `json:"name"`
	CustomFields map[string]any `json:"custom_fields"`
	Timezone     string         `json:"timezone"`
	Language     string         `json:"language"`
}

// SubscribeResponse is the response body.
type SubscribeResponse struct {
	Subscriber *Subscriber `json:"subscriber"`
	ListID     string      `json:"list_id"`
}

// Subscriber is the wire body.
type Subscriber struct {
	ID             string         `json:"id"`
	ProjectID      string         `json:"project_id"`
	Email          string         `json:"email"`
	Name           string         `json:"name,omitempty"`
	Status         string         `json:"status"`
	CustomFields   map[string]any `json:"custom_fields,omitempty"`
	Timezone       string         `json:"timezone,omitempty"`
	Language       string         `json:"language,omitempty"`
	SubscribedAt   *time.Time     `json:"subscribed_at,omitempty"`
	UnsubscribedAt *time.Time     `json:"unsubscribed_at,omitempty"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      *time.Time     `json:"updated_at,omitempty"`
}

// SubscriberListResponse is the response body.
type SubscriberListResponse struct {
	Subscribers []*Subscriber `json:"subscribers"`
	Total       int64         `json:"total"`
}

// SubscriberResponse is the response body.
type SubscriberResponse struct {
	Subscriber *Subscriber `json:"subscriber"`
}

// SubscriberSubscriberResponse is the response body.
type SubscriberSubscriberResponse struct {
	Subscriber *Subscriber `json:"subscriber"`
}

// SubscriberUpsertInput is the request body.
type SubscriberUpsertInput struct {
	Email        string         `json:"email"`
	Name         string         `json:"name"`
	Status       string         `json:"status"`
	CustomFields map[string]any `json:"custom_fields"`
	Timezone     string         `json:"timezone"`
	Language     string         `json:"language"`
}

// SubscriberlistListResponse is the response body.
type SubscriberlistListResponse struct {
	SubscriberLists []*List `json:"subscriber_lists"`
}

// SubscriberlistMemberInput is the request body.
type SubscriberlistMemberInput struct {
	SubscriberID string `json:"subscriber_id"`
	Email        string `json:"email"`
}

// SubscriberlistMemberListResponse is the response body.
type SubscriberlistMemberListResponse struct {
	Members []*Subscriber `json:"members"`
}

// SubscriberlistUpsertInput is the request body.
type SubscriberlistUpsertInput struct {
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Type        string       `json:"type"`
	FilterRules []FilterRule `json:"filter_rules"`
}

// Summary is the wire body.
type Summary struct {
	Emails      map[string]int64    `json:"emails"`
	TotalEmails int64               `json:"total_emails"`
	FailureRate float64             `json:"failure_rate"`
	Inbound     map[string]int64    `json:"inbound"`
	Resources   map[string]int64    `json:"resources"`
	Engagement  AnalyticsEngagement `json:"engagement"`
}

// Suppression is the wire body.
type Suppression struct {
	ID                string    `json:"id"`
	ProjectID         string    `json:"project_id"`
	Email             string    `json:"email"`
	Kind              string    `json:"kind"`
	Reason            string    `json:"reason,omitempty"`
	UnsubscribeListID string    `json:"unsubscribe_list_id,omitempty"`
	CreatedAt         time.Time `json:"created_at"`
}

// SuppressionCreateInput is the request body.
type SuppressionCreateInput struct {
	Email  string `json:"email"`
	Kind   string `json:"kind"`
	Reason string `json:"reason"`
}

// SuppressionListResponse is the response body.
type SuppressionListResponse struct {
	Suppressions []*Suppression `json:"suppressions"`
	NextCursor   string         `json:"next_cursor"`
}

// System is the wire body.
type System struct {
	Scope   string   `json:"scope"`
	Name    string   `json:"name"`
	Details *Details `json:"details,omitempty"`
}

// SystemMailStatus is the wire body.
type SystemMailStatus struct {
	Enabled  bool   `json:"enabled"`
	From     string `json:"from"`
	FromName string `json:"from_name"`
	Server   string `json:"server"`
	Reserved bool   `json:"reserved"`
	Problem  string `json:"problem,omitempty"`
}

// SystemMailStatusResponse is the response body.
type SystemMailStatusResponse struct {
	SystemMail SystemMailStatus `json:"system_mail"`
}

// SystemMailTestInput is the request body.
type SystemMailTestInput struct {
	To string `json:"to"`
}

// SystemResponse is the response body.
type SystemResponse struct {
	Certificates []System `json:"certificates"`
}

// Template is the wire body.
type Template struct {
	ID              string     `json:"id"`
	ProjectID       string     `json:"project_id"`
	Name            string     `json:"name"`
	Description     string     `json:"description,omitempty"`
	DefaultLanguage string     `json:"default_language"`
	ActiveVersionID *string    `json:"active_version_id,omitempty"`
	SampleData      string     `json:"sample_data,omitempty"`
	CreatedBy       string     `json:"created_by,omitempty"`
	LastEditedBy    string     `json:"last_edited_by,omitempty"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       *time.Time `json:"updated_at,omitempty"`
}

// TemplateAttachment is the wire body.
type TemplateAttachment struct {
	ID          string    `json:"id"`
	ProjectID   string    `json:"project_id"`
	TemplateID  string    `json:"template_id"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type,omitempty"`
	Size        int64     `json:"size"`
	StorageKey  string    `json:"storage_key,omitempty"`
	CreatedAt   time.Time `json:"created_at"`
}

// TemplateCreateInput is the request body.
type TemplateCreateInput struct {
	Name            string `json:"name"`
	Description     string `json:"description"`
	DefaultLanguage string `json:"default_language"`
	SampleData      string `json:"sample_data"`
	Subject         string `json:"subject"`
	HTML            string `json:"html"`
	Text            string `json:"text"`
}

// TemplateExportResponse is the response body.
type TemplateExportResponse struct {
	Export TransferDoc `json:"export"`
}

// TemplateGetResponse is the response body.
type TemplateGetResponse struct {
	Template *Template  `json:"template"`
	Versions []*Version `json:"versions"`
}

// TemplateListResponse is the response body.
type TemplateListResponse struct {
	Templates []*Template `json:"templates"`
}

// TemplatePreviewInput is the request body.
type TemplatePreviewInput struct {
	Subject string         `json:"subject"`
	HTML    string         `json:"html"`
	Text    string         `json:"text"`
	CSS     string         `json:"css"`
	Data    map[string]any `json:"data"`
}

// TemplateResponse is the response body.
type TemplateResponse struct {
	Template *Template `json:"template"`
}

// TemplateSendInput is the request body.
type TemplateSendInput struct {
	From                  string            `json:"from"`
	To                    []string          `json:"to"`
	TemplateID            string            `json:"template_id"`
	TemplateName          string            `json:"template_name"`
	Language              string            `json:"language"`
	Data                  map[string]any    `json:"data"`
	Headers               map[string]string `json:"headers"`
	Attachments           []Attachment      `json:"attachments"`
	SendAt                string            `json:"send_at"`
	DryRun                bool              `json:"dry_run"`
	DisableTracking       bool              `json:"disable_tracking"`
	SMTPGroup             string            `json:"smtp_group"`
	SMTPServerID          string            `json:"smtp_server_id"`
	UnsubscribeListID     string            `json:"unsubscribe_list_id"`
	ListUnsubscribeURL    string            `json:"list_unsubscribe_url"`
	ListUnsubscribeMailto string            `json:"list_unsubscribe_mailto"`
	ListUnsubscribePost   bool              `json:"list_unsubscribe_post"`
	Sandbox               *bool             `json:"sandbox"`
	SandboxRetentionDays  int64             `json:"sandbox_retention_days"`
}

// TemplateUpdateInput is the request body.
type TemplateUpdateInput struct {
	Name            string  `json:"name"`
	Description     *string `json:"description"`
	DefaultLanguage string  `json:"default_language"`
	SampleData      *string `json:"sample_data"`
}

// TestResponse is the response body.
type TestResponse struct {
	Test any `json:"test"`
}

// TestSendInput is the request body.
type TestSendInput struct {
	From     string         `json:"from"`
	To       []string       `json:"to"`
	Language string         `json:"language"`
	Data     map[string]any `json:"data"`
}

// TrackedLinksResponse is the response body.
type TrackedLinksResponse struct {
	Links map[string]string `json:"links"`
}

// TransferDoc is the wire body.
type TransferDoc struct {
	Format   string            `json:"format"`
	Template TransferTemplate  `json:"template"`
	Versions []TransferVersion `json:"versions"`
}

// TransferLocalization is the wire body.
type TransferLocalization struct {
	Language string `json:"language"`
	Subject  string `json:"subject"`
	HTML     string `json:"html"`
	Text     string `json:"text"`
}

// TransferStylesheet is the wire body.
type TransferStylesheet struct {
	Name string `json:"name"`
	CSS  string `json:"css"`
}

// TransferTemplate is the wire body.
type TransferTemplate struct {
	Name            string `json:"name"`
	Description     string `json:"description"`
	DefaultLanguage string `json:"default_language"`
	SampleData      string `json:"sample_data"`
}

// TransferVersion is the wire body.
type TransferVersion struct {
	Version       int64                  `json:"version"`
	Active        bool                   `json:"active"`
	SampleData    string                 `json:"sample_data"`
	Stylesheet    *TransferStylesheet    `json:"stylesheet,omitempty"`
	Localizations []TransferLocalization `json:"localizations"`
}

// TrendResponse is the response body.
type TrendResponse struct {
	DailyCounts     []DayCount       `json:"daily_counts"`
	StatusBreakdown map[string]int64 `json:"status_breakdown"`
	From            string           `json:"from"`
	To              string           `json:"to"`
}

// UnreadResponse is the response body.
type UnreadResponse struct {
	Unread int64 `json:"unread"`
}

// UnsubscribelistCreateInput is the request body.
type UnsubscribelistCreateInput struct {
	Name        string `json:"name"`
	PublicName  string `json:"public_name"`
	Description string `json:"description"`
}

// UnsubscribelistGetResponse is the response body.
type UnsubscribelistGetResponse struct {
	UnsubscribeList *UnsubscribelistList `json:"unsubscribe_list"`
}

// UnsubscribelistList is the wire body.
type UnsubscribelistList struct {
	ID              string     `json:"id"`
	ProjectID       string     `json:"project_id"`
	Name            string     `json:"name"`
	PublicName      string     `json:"public_name,omitempty"`
	Description     string     `json:"description,omitempty"`
	Active          bool       `json:"active"`
	SuppressedCount int64      `json:"suppressed_count"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       *time.Time `json:"updated_at,omitempty"`
}

// UnsubscribelistListResponse is the response body.
type UnsubscribelistListResponse struct {
	UnsubscribeLists []*UnsubscribelistList `json:"unsubscribe_lists"`
}

// UnsubscribelistUpdateInput is the request body.
type UnsubscribelistUpdateInput struct {
	Name        string  `json:"name"`
	PublicName  *string `json:"public_name"`
	Description *string `json:"description"`
	Active      *bool   `json:"active"`
}

// UpdateInput is the request body.
type UpdateInput struct {
	Settings []SettingInput `json:"settings"`
}

// UploadInput is the request body.
type UploadInput struct {
	Name    string `json:"name"`
	CertPEM string `json:"certificate"`
	KeyPEM  string `json:"private_key"`
}

// UpsertInput is the request body.
type UpsertInput struct {
	Name                 string   `json:"name"`
	Slug                 string   `json:"slug"`
	Type                 string   `json:"type"`
	ClientID             string   `json:"client_id"`
	Secret               *string  `json:"client_secret"`
	Issuer               string   `json:"issuer"`
	AuthURL              string   `json:"auth_url"`
	TokenURL             string   `json:"token_url"`
	UserInfoURL          string   `json:"userinfo_url"`
	Scopes               []string `json:"scopes"`
	Enabled              *bool    `json:"enabled"`
	Hidden               *bool    `json:"hidden"`
	AutoRegister         *bool    `json:"auto_register"`
	RequireEmailVerified *bool    `json:"require_email_verified"`
	AllowedDomains       []string `json:"allowed_domains"`
	AllowedEmails        []string `json:"allowed_emails"`
	GroupsClaim          string   `json:"groups_claim"`
	AllowedGroups        []string `json:"allowed_groups"`
}

// UsageResponse is the response body.
type UsageResponse struct {
	Usage Counts `json:"usage"`
	Plan  *Plan  `json:"plan,omitempty"`
}

// User is the wire body.
type User struct {
	ID            string     `json:"id"`
	Email         string     `json:"email"`
	AccountType   int64      `json:"account_type"`
	Admin         bool       `json:"admin"`
	Disabled      bool       `json:"disabled"`
	EmailVerified bool       `json:"email_verified"`
	TOTPEnabled   bool       `json:"totp_enabled"`
	PasskeyCount  int64      `json:"passkey_count"`
	CreatedAt     time.Time  `json:"created_at"`
	LastLoginAt   *time.Time `json:"last_login_at,omitempty"`
}

// UserListResponse is the response body.
type UserListResponse struct {
	Users []*User `json:"users"`
}

// UserResponse is the response body.
type UserResponse struct {
	User *User `json:"user"`
}

// UserUpdateInput is the request body.
type UserUpdateInput struct {
	Email         string `json:"email"`
	Password      string `json:"password"`
	Admin         *bool  `json:"admin"`
	Disabled      *bool  `json:"disabled"`
	EmailVerified *bool  `json:"email_verified"`
}

// Variant is the wire body.
type Variant struct {
	Name            string `json:"name"`
	Subject         string `json:"subject"`
	TemplateID      string `json:"template_id"`
	SplitPercentage int64  `json:"split_percentage"`
}

// VerifyInput is the request body.
type VerifyInput struct {
	Email string `json:"email"`
}

// VerifyResponse is the response body.
type VerifyResponse struct {
	Verification Result `json:"verification"`
}

// Version is the wire body.
type Version struct {
	ID           string    `json:"id"`
	TemplateID   string    `json:"template_id"`
	Version      int64     `json:"version"`
	StylesheetID *string   `json:"stylesheet_id,omitempty"`
	SampleData   string    `json:"sample_data,omitempty"`
	CreatedAt    time.Time `json:"created_at"`
}

// VersionInput is the request body.
type VersionInput struct {
	StylesheetID string `json:"stylesheet_id"`
	SampleData   string `json:"sample_data"`
}

// VersionListResponse is the response body.
type VersionListResponse struct {
	Versions []*Version `json:"versions"`
}

// VersionPreviewInput is the request body.
type VersionPreviewInput struct {
	Language string         `json:"language"`
	Data     map[string]any `json:"data"`
}

// VersionResponse is the response body.
type VersionResponse struct {
	Version *Version `json:"version"`
}

// Webhook is the wire body.
type Webhook struct {
	ID        string    `json:"id"`
	ProjectID string    `json:"project_id"`
	CreatedBy string    `json:"created_by,omitempty"`
	URL       string    `json:"url"`
	Events    []string  `json:"events"`
	Filters   []string  `json:"filters"`
	CreatedAt time.Time `json:"created_at"`
}

// WebhookCreateInput is the request body.
type WebhookCreateInput struct {
	URL     string   `json:"url"`
	Events  []string `json:"events"`
	Filters []string `json:"filters"`
}

// WebhookCreateResponse is the response body.
type WebhookCreateResponse struct {
	Webhook *Webhook `json:"webhook"`
	Secret  string   `json:"secret"`
}

// WebhookListResponse is the response body.
type WebhookListResponse struct {
	Webhooks []*Webhook `json:"webhooks"`
}
