# frozen_string_literal: true

# Every /api/v1 route, one method each.
#
# Generated by cmd/sdkgen from the same route metadata the OpenAPI
# document is built from - do not edit. Run `task sdk-gen`.
#
# A body is a plain Hash and a result is whatever the API answered,
# parsed. The schemas are in the OpenAPI document:
#
#   mailyard export-api-spec --out openapi.yaml

require "uri"

module Mailyard
  # The route surface. Reached as +client.api+.
  class API
    def initialize(transport)
      @t = transport
    end

    # Percent-encode one path segment.
    #
    # Everything outside RFC 3986's unreserved set goes, separators
    # included: an id of "../users/x" would otherwise reroute the
    # request to another endpoint, and one holding "?" or "#" would
    # inject a query or truncate the path. A space or a non-ASCII byte
    # also raised URI::InvalidURIError out of the transport, so this
    # fixes an outright crash as well.
    def esc(value)
      URI::DEFAULT_PARSER.escape(value.to_s, /[^A-Za-z0-9\-._~]/)
    end

    # List platform credentials
    def list_admin_api_keys(**query)
      @t.request("GET", "/admin/api-keys", body: nil, query: query)
    end

    # Mint a platform credential
    def create_admin_api_key(body: nil, **query)
      @t.request("POST", "/admin/api-keys", body: body, query: query)
    end

    # Delete a platform credential
    def delete_admin_api_key(id, **query)
      @t.request("DELETE", "/admin/api-keys/#{esc(id)}", body: nil, query: query)
    end

    # Revoke a platform credential
    def revoke_admin_api_key(id, **query)
      @t.request("POST", "/admin/api-keys/#{esc(id)}/revoke", body: nil, query: query)
    end

    # List managed certificates and listener assignments
    def list_admin_certificates(**query)
      @t.request("GET", "/admin/certificates", body: nil, query: query)
    end

    # Upload a certificate and its private key
    def create_admin_certificate(body: nil, **query)
      @t.request("POST", "/admin/certificates", body: body, query: query)
    end

    # Delete a managed certificate
    def delete_admin_certificate(name, **query)
      @t.request("DELETE", "/admin/certificates/#{esc(name)}", body: nil, query: query)
    end

    # Read a certificate's public half
    def get_admin_certificate_pem(name, **query)
      @t.request("GET", "/admin/certificates/#{esc(name)}/pem", body: nil, query: query)
    end

    # What ACME is configured to do, and what it holds
    def get_admin_certificates_acme(**query)
      @t.request("GET", "/admin/certificates/acme", body: nil, query: query)
    end

    # Obtain a certificate for one configured host
    def acme_order_admin_certificate(body: nil, **query)
      @t.request("POST", "/admin/certificates/acme/order", body: body, query: query)
    end

    # Discard what is cached for a host and order again
    def acme_renew_admin_certificate(body: nil, **query)
      @t.request("POST", "/admin/certificates/acme/renew", body: body, query: query)
    end

    # Generate a certificate for a listener
    def generate_admin_certificate(body: nil, **query)
      @t.request("POST", "/admin/certificates/generate", body: body, query: query)
    end

    # Generate a certificate authority
    def generate_ca_admin_certificate(body: nil, **query)
      @t.request("POST", "/admin/certificates/generate-ca", body: body, query: query)
    end

    # List the certificates the installation holds for itself
    def get_admin_certificates_system(**query)
      @t.request("GET", "/admin/certificates/system", body: nil, query: query)
    end

    # Jobs
    def list_admin_jobs(**query)
      @t.request("GET", "/admin/jobs", body: nil, query: query)
    end

    # Run job
    def run_admin_job(name, **query)
      @t.request("POST", "/admin/jobs/#{esc(name)}/run", body: nil, query: query)
    end

    # List
    def list_admin_oauth_providers(**query)
      @t.request("GET", "/admin/oauth-providers", body: nil, query: query)
    end

    # Create
    def create_admin_oauth_provider(body: nil, **query)
      @t.request("POST", "/admin/oauth-providers", body: body, query: query)
    end

    # Delete
    def delete_admin_oauth_provider(id, **query)
      @t.request("DELETE", "/admin/oauth-providers/#{esc(id)}", body: nil, query: query)
    end

    # Get
    def get_admin_oauth_provider(id, **query)
      @t.request("GET", "/admin/oauth-providers/#{esc(id)}", body: nil, query: query)
    end

    # Update
    def update_admin_oauth_provider(id, body: nil, **query)
      @t.request("PATCH", "/admin/oauth-providers/#{esc(id)}", body: body, query: query)
    end

    # Test
    def test_admin_oauth_provider(id, **query)
      @t.request("POST", "/admin/oauth-providers/#{esc(id)}/test", body: nil, query: query)
    end

    # List
    def list_admin_plans(**query)
      @t.request("GET", "/admin/plans", body: nil, query: query)
    end

    # Create
    def create_admin_plan(body: nil, **query)
      @t.request("POST", "/admin/plans", body: body, query: query)
    end

    # Delete
    def delete_admin_plan(id, **query)
      @t.request("DELETE", "/admin/plans/#{esc(id)}", body: nil, query: query)
    end

    # Update
    def update_admin_plan(id, body: nil, **query)
      @t.request("PATCH", "/admin/plans/#{esc(id)}", body: body, query: query)
    end

    # Assign
    def update_admin_project_plan(id, body: nil, **query)
      @t.request("PATCH", "/admin/projects/#{esc(id)}/plan", body: body, query: query)
    end

    # List
    def list_admin_relay_nodes(**query)
      @t.request("GET", "/admin/relay-nodes", body: nil, query: query)
    end

    # Delete
    def delete_admin_relay_node(id, **query)
      @t.request("DELETE", "/admin/relay-nodes/#{esc(id)}", body: nil, query: query)
    end

    # Approve
    def approve_admin_relay_node(id, **query)
      @t.request("POST", "/admin/relay-nodes/#{esc(id)}/approve", body: nil, query: query)
    end

    # Suspend
    def suspend_admin_relay_node(id, **query)
      @t.request("POST", "/admin/relay-nodes/#{esc(id)}/suspend", body: nil, query: query)
    end

    # Destroy the relay authority
    def delete_admin_relay_nodes_authority(**query)
      @t.request("DELETE", "/admin/relay-nodes/authority", body: nil, query: query)
    end

    # List
    def list_admin_settings(**query)
      @t.request("GET", "/admin/settings", body: nil, query: query)
    end

    # Update
    def update_admin_settings(body: nil, **query)
      @t.request("PUT", "/admin/settings", body: body, query: query)
    end

    # List
    def list_admin_shared_smtp_servers(**query)
      @t.request("GET", "/admin/shared-smtp-servers", body: nil, query: query)
    end

    # Create
    def create_admin_shared_smtp_server(body: nil, **query)
      @t.request("POST", "/admin/shared-smtp-servers", body: body, query: query)
    end

    # Delete
    def delete_admin_shared_smtp_server(id, **query)
      @t.request("DELETE", "/admin/shared-smtp-servers/#{esc(id)}", body: nil, query: query)
    end

    # Get
    def get_admin_shared_smtp_server(id, **query)
      @t.request("GET", "/admin/shared-smtp-servers/#{esc(id)}", body: nil, query: query)
    end

    # Update
    def update_admin_shared_smtp_server(id, body: nil, **query)
      @t.request("PATCH", "/admin/shared-smtp-servers/#{esc(id)}", body: body, query: query)
    end

    # Test
    def test_admin_shared_smtp_server(id, **query)
      @t.request("POST", "/admin/shared-smtp-servers/#{esc(id)}/test", body: nil, query: query)
    end

    # System mail status
    def list_admin_system_mail(**query)
      @t.request("GET", "/admin/system-mail", body: nil, query: query)
    end

    # System mail test
    def test_admin_system_mail(body: nil, **query)
      @t.request("POST", "/admin/system-mail/test", body: body, query: query)
    end

    # List
    def list_admin_users(**query)
      @t.request("GET", "/admin/users", body: nil, query: query)
    end

    # Create
    def create_admin_user(body: nil, **query)
      @t.request("POST", "/admin/users", body: body, query: query)
    end

    # Delete
    def delete_admin_user(id, **query)
      @t.request("DELETE", "/admin/users/#{esc(id)}", body: nil, query: query)
    end

    # Get
    def get_admin_user(id, **query)
      @t.request("GET", "/admin/users/#{esc(id)}", body: nil, query: query)
    end

    # Update
    def update_admin_user(id, body: nil, **query)
      @t.request("PATCH", "/admin/users/#{esc(id)}", body: body, query: query)
    end

    # Reset t o t p
    def delete_admin_user2fa(id, **query)
      @t.request("DELETE", "/admin/users/#{esc(id)}/2fa", body: nil, query: query)
    end

    # Reset passkeys
    def delete_admin_user_passkey(id, **query)
      @t.request("DELETE", "/admin/users/#{esc(id)}/passkeys", body: nil, query: query)
    end

    # Projects
    def list_admin_user_projects(id, **query)
      @t.request("GET", "/admin/users/#{esc(id)}/projects", body: nil, query: query)
    end

    # Revoke sessions
    def create_admin_user_revoke_session(id, **query)
      @t.request("POST", "/admin/users/#{esc(id)}/revoke-sessions", body: nil, query: query)
    end

    # Daily delivery trend and status breakdown Needs analytics:read.
    def list_analytics(**query)
      @t.request("GET", "/analytics", body: nil, query: query)
    end

    # List
    def list_api_keys(**query)
      @t.request("GET", "/api-keys", body: nil, query: query)
    end

    # Create
    def create_api_key(body: nil, **query)
      @t.request("POST", "/api-keys", body: body, query: query)
    end

    # Delete
    def delete_api_key(id, **query)
      @t.request("DELETE", "/api-keys/#{esc(id)}", body: nil, query: query)
    end

    # Revoke
    def revoke_api_key(id, **query)
      @t.request("POST", "/api-keys/#{esc(id)}/revoke", body: nil, query: query)
    end

    # Project log
    def list_audit_log(**query)
      @t.request("GET", "/audit-log", body: nil, query: query)
    end

    # Project event
    def get_audit_log(id, **query)
      @t.request("GET", "/audit-log/#{esc(id)}", body: nil, query: query)
    end

    # Export the project log
    def get_audit_log_export(**query)
      @t.request("GET", "/audit-log/export", body: nil, query: query)
    end

    # Delete the bounce reports for an address Needs bounces:delete.
    def delete_bounces(**query)
      @t.request("DELETE", "/bounces", body: nil, query: query)
    end

    # List bounce reports Needs bounces:read.
    def list_bounces(**query)
      @t.request("GET", "/bounces", body: nil, query: query)
    end

    # List
    def list_campaigns(**query)
      @t.request("GET", "/campaigns", body: nil, query: query)
    end

    # Create
    def create_campaign(body: nil, **query)
      @t.request("POST", "/campaigns", body: body, query: query)
    end

    # Delete
    def delete_campaign(id, **query)
      @t.request("DELETE", "/campaigns/#{esc(id)}", body: nil, query: query)
    end

    # Get
    def get_campaign(id, **query)
      @t.request("GET", "/campaigns/#{esc(id)}", body: nil, query: query)
    end

    # Update
    def update_campaign(id, body: nil, **query)
      @t.request("PATCH", "/campaigns/#{esc(id)}", body: body, query: query)
    end

    # Analytics
    def list_campaign_analytics(id, **query)
      @t.request("GET", "/campaigns/#{esc(id)}/analytics", body: nil, query: query)
    end

    # Cancel
    def cancel_campaign(id, **query)
      @t.request("POST", "/campaigns/#{esc(id)}/cancel", body: nil, query: query)
    end

    # Duplicate
    def duplicate_campaign(id, **query)
      @t.request("POST", "/campaigns/#{esc(id)}/duplicate", body: nil, query: query)
    end

    # Messages
    def list_campaign_messages(id, **query)
      @t.request("GET", "/campaigns/#{esc(id)}/messages", body: nil, query: query)
    end

    # Pause
    def pause_campaign(id, **query)
      @t.request("POST", "/campaigns/#{esc(id)}/pause", body: nil, query: query)
    end

    # Resume
    def resume_campaign(id, **query)
      @t.request("POST", "/campaigns/#{esc(id)}/resume", body: nil, query: query)
    end

    # Send
    def send_campaign(id, body: nil, **query)
      @t.request("POST", "/campaigns/#{esc(id)}/send", body: body, query: query)
    end

    # Delete contacts idle since a date Needs contacts:delete.
    def delete_contacts(**query)
      @t.request("DELETE", "/contacts", body: nil, query: query)
    end

    # Addresses this project has delivered to Needs contacts:read.
    def list_contacts(**query)
      @t.request("GET", "/contacts", body: nil, query: query)
    end

    # Delete one contact Needs contacts:delete.
    def delete_contact(id, **query)
      @t.request("DELETE", "/contacts/#{esc(id)}", body: nil, query: query)
    end

    # One contact Needs contacts:read.
    def get_contact(id, **query)
      @t.request("GET", "/contacts/#{esc(id)}", body: nil, query: query)
    end

    # Aggregate counts for a dashboard Needs analytics:read.
    def list_dashboard_stats(**query)
      @t.request("GET", "/dashboard/stats", body: nil, query: query)
    end

    # Delete contacts
    def create_data_delete_contact(body: nil, **query)
      @t.request("POST", "/data/delete-contacts", body: body, query: query)
    end

    # Delete email logs
    def create_data_delete_email_log(body: nil, **query)
      @t.request("POST", "/data/delete-email-logs", body: body, query: query)
    end

    # Export every record of the key's project Needs data:read.
    def get_data_export(**query)
      @t.request("GET", "/data/export", body: nil, query: query)
    end

    # List
    def list_domains(**query)
      @t.request("GET", "/domains", body: nil, query: query)
    end

    # Create
    def create_domain(body: nil, **query)
      @t.request("POST", "/domains", body: body, query: query)
    end

    # Delete
    def delete_domain(id, **query)
      @t.request("DELETE", "/domains/#{esc(id)}", body: nil, query: query)
    end

    # Get
    def get_domain(id, **query)
      @t.request("GET", "/domains/#{esc(id)}", body: nil, query: query)
    end

    # Verify
    def verify_domain(id, **query)
      @t.request("POST", "/domains/#{esc(id)}/verify", body: nil, query: query)
    end

    # List sent and queued emails Needs emails:read.
    def list_emails(**query)
      @t.request("GET", "/emails", body: nil, query: query)
    end

    # One email with its full delivery record Needs emails:read.
    def get_email(id, **query)
      @t.request("GET", "/emails/#{esc(id)}", body: nil, query: query)
    end

    # Attachment
    def get_email_attachment(id, idx, **query)
      @t.request("GET", "/emails/#{esc(id)}/attachments/#{esc(idx)}", body: nil, query: query, raw: true)
    end

    # Requeue a failed email Needs emails:write.
    def retry_email(id, **query)
      @t.request("POST", "/emails/#{esc(id)}/retry", body: nil, query: query)
    end

    # Delivery status only Needs emails:read.
    def list_email_status(id, **query)
      @t.request("GET", "/emails/#{esc(id)}/status", body: nil, query: query)
    end

    # Original destinations behind the click redirects Needs emails:read.
    def list_email_tracked_links(id, **query)
      @t.request("GET", "/emails/#{esc(id)}/tracked-links", body: nil, query: query)
    end

    # Queue up to 100 emails in one call Needs emails:write.
    def batch_email(body: nil, **query)
      @t.request("POST", "/emails/batch", body: body, query: query)
    end

    # What a send may carry on this installation Needs emails:read.
    def list_emails_limits(**query)
      @t.request("GET", "/emails/limits", body: nil, query: query)
    end

    # Render a template without sending Needs emails:read.
    def preview_email(body: nil, **query)
      @t.request("POST", "/emails/preview", body: body, query: query)
    end

    # Queue one email Needs emails:write.
    def send_email(body: nil, **query)
      @t.request("POST", "/emails/send", body: body, query: query)
    end

    # Render a stored template and queue the result Needs emails:write.
    def send_template_email(body: nil, **query)
      @t.request("POST", "/emails/send-template", body: body, query: query)
    end

    # Count emails by delivery status Needs emails:read.
    def list_emails_stats(**query)
      @t.request("GET", "/emails/stats", body: nil, query: query)
    end

    # Judge whether an address is worth sending to Needs emails:read.
    def verify_email(body: nil, **query)
      @t.request("POST", "/emails/verify", body: body, query: query)
    end

    # List mail received by the MX listener Needs inbound:read.
    def list_inbound_emails(**query)
      @t.request("GET", "/inbound-emails", body: nil, query: query)
    end

    # Delete
    def delete_inbound_email(id, **query)
      @t.request("DELETE", "/inbound-emails/#{esc(id)}", body: nil, query: query)
    end

    # One received message Needs inbound:read.
    def get_inbound_email(id, **query)
      @t.request("GET", "/inbound-emails/#{esc(id)}", body: nil, query: query)
    end

    # Attachment
    def get_inbound_email_attachment(id, idx, **query)
      @t.request("GET", "/inbound-emails/#{esc(id)}/attachments/#{esc(idx)}", body: nil, query: query, raw: true)
    end

    # Raw
    def get_inbound_email_raw(id, **query)
      @t.request("GET", "/inbound-emails/#{esc(id)}/raw", body: nil, query: query, raw: true)
    end

    # Retry
    def retry_inbound_email(id, **query)
      @t.request("POST", "/inbound-emails/#{esc(id)}/retry", body: nil, query: query)
    end

    # Count received mail by status Needs inbound:read.
    def list_inbound_emails_stats(**query)
      @t.request("GET", "/inbound-emails/stats", body: nil, query: query)
    end

    # Accept invitation
    def accept_invitation(token, **query)
      @t.request("POST", "/invitations/#{esc(token)}/accept", body: nil, query: query)
    end

    # Decline invitation
    def decline_invitation(token, **query)
      @t.request("POST", "/invitations/#{esc(token)}/decline", body: nil, query: query)
    end

    # List
    def list_languages(**query)
      @t.request("GET", "/languages", body: nil, query: query)
    end

    # Create
    def create_language(body: nil, **query)
      @t.request("POST", "/languages", body: body, query: query)
    end

    # Delete
    def delete_language(id, **query)
      @t.request("DELETE", "/languages/#{esc(id)}", body: nil, query: query)
    end

    # Update
    def update_language(id, body: nil, **query)
      @t.request("PUT", "/languages/#{esc(id)}", body: body, query: query)
    end

    # List mine
    def list_my_relay_nodes(**query)
      @t.request("GET", "/my/relay-nodes", body: nil, query: query)
    end

    # Delete mine
    def delete_my_relay_node(id, **query)
      @t.request("DELETE", "/my/relay-nodes/#{esc(id)}", body: nil, query: query)
    end

    # Approve mine
    def relay_nodes_approve_my(id, **query)
      @t.request("POST", "/my/relay-nodes/#{esc(id)}/approve", body: nil, query: query)
    end

    # Suspend mine
    def relay_nodes_suspend_my(id, **query)
      @t.request("POST", "/my/relay-nodes/#{esc(id)}/suspend", body: nil, query: query)
    end

    # List
    def list_notifications(**query)
      @t.request("GET", "/notifications", body: nil, query: query)
    end

    # Delete
    def delete_notification(id, **query)
      @t.request("DELETE", "/notifications/#{esc(id)}", body: nil, query: query)
    end

    # Mark read
    def read_notification(id, **query)
      @t.request("POST", "/notifications/#{esc(id)}/read", body: nil, query: query)
    end

    # Mark all read
    def read_all_notification(**query)
      @t.request("POST", "/notifications/read-all", body: nil, query: query)
    end

    # Unread
    def get_notifications_unread(**query)
      @t.request("GET", "/notifications/unread", body: nil, query: query)
    end

    # Catalog
    def list_permissions(**query)
      @t.request("GET", "/permissions", body: nil, query: query)
    end

    # List
    def list_projects(**query)
      @t.request("GET", "/projects", body: nil, query: query)
    end

    # Create
    def create_project(body: nil, **query)
      @t.request("POST", "/projects", body: body, query: query)
    end

    # Delete
    def delete_project(id, **query)
      @t.request("DELETE", "/projects/#{esc(id)}", body: nil, query: query)
    end

    # Get
    def get_project(id, **query)
      @t.request("GET", "/projects/#{esc(id)}", body: nil, query: query)
    end

    # Update
    def update_project(id, body: nil, **query)
      @t.request("PATCH", "/projects/#{esc(id)}", body: body, query: query)
    end

    # Set the default role
    def update_project_default_role(id, body: nil, **query)
      @t.request("PUT", "/projects/#{esc(id)}/default-role", body: body, query: query)
    end

    # List invitations
    def list_project_invitations(id, **query)
      @t.request("GET", "/projects/#{esc(id)}/invitations", body: nil, query: query)
    end

    # Create invitation
    def create_project_invitation(id, body: nil, **query)
      @t.request("POST", "/projects/#{esc(id)}/invitations", body: body, query: query)
    end

    # Delete invitation
    def delete_project_invitation(id, inv_id, **query)
      @t.request("DELETE", "/projects/#{esc(id)}/invitations/#{esc(inv_id)}", body: nil, query: query)
    end

    # List members
    def list_project_members(id, **query)
      @t.request("GET", "/projects/#{esc(id)}/members", body: nil, query: query)
    end

    # Add member
    def create_project_member(id, body: nil, **query)
      @t.request("POST", "/projects/#{esc(id)}/members", body: body, query: query)
    end

    # Remove member
    def delete_project_member(id, user_id, **query)
      @t.request("DELETE", "/projects/#{esc(id)}/members/#{esc(user_id)}", body: nil, query: query)
    end

    # Update member
    def update_project_member(id, user_id, body: nil, **query)
      @t.request("PATCH", "/projects/#{esc(id)}/members/#{esc(user_id)}", body: body, query: query)
    end

    # List roles
    def list_project_roles(id, **query)
      @t.request("GET", "/projects/#{esc(id)}/roles", body: nil, query: query)
    end

    # Create role
    def create_project_role(id, body: nil, **query)
      @t.request("POST", "/projects/#{esc(id)}/roles", body: body, query: query)
    end

    # Delete role
    def delete_project_role(id, role_id, **query)
      @t.request("DELETE", "/projects/#{esc(id)}/roles/#{esc(role_id)}", body: nil, query: query)
    end

    # Update role
    def update_project_role(id, role_id, body: nil, **query)
      @t.request("PATCH", "/projects/#{esc(id)}/roles/#{esc(role_id)}", body: body, query: query)
    end

    # List
    def list_sandbox(**query)
      @t.request("GET", "/sandbox", body: nil, query: query)
    end

    # Delete
    def delete_sandbox(id, **query)
      @t.request("DELETE", "/sandbox/#{esc(id)}", body: nil, query: query)
    end

    # Get
    def get_sandbox(id, **query)
      @t.request("GET", "/sandbox/#{esc(id)}", body: nil, query: query)
    end

    # Attachment
    def get_sandbox_attachment(id, idx, **query)
      @t.request("GET", "/sandbox/#{esc(id)}/attachments/#{esc(idx)}", body: nil, query: query, raw: true)
    end

    # Raw
    def get_sandbox_raw(id, **query)
      @t.request("GET", "/sandbox/#{esc(id)}/raw", body: nil, query: query, raw: true)
    end

    # Clear
    def clear_sandbox(**query)
      @t.request("POST", "/sandbox/clear", body: nil, query: query)
    end

    # List credentials
    def list_sandbox_credentials(**query)
      @t.request("GET", "/sandbox/credentials", body: nil, query: query)
    end

    # Create credential
    def create_sandbox_credential(body: nil, **query)
      @t.request("POST", "/sandbox/credentials", body: body, query: query)
    end

    # Revoke credential
    def credentials_revoke_sandbox(id, **query)
      @t.request("POST", "/sandbox/credentials/#{esc(id)}/revoke", body: nil, query: query)
    end

    # Info
    def get_sandbox_info(**query)
      @t.request("GET", "/sandbox/info", body: nil, query: query)
    end

    # List
    def list_senders(**query)
      @t.request("GET", "/senders", body: nil, query: query)
    end

    # Create
    def create_sender(body: nil, **query)
      @t.request("POST", "/senders", body: body, query: query)
    end

    # Delete
    def delete_sender(id, **query)
      @t.request("DELETE", "/senders/#{esc(id)}", body: nil, query: query)
    end

    # List
    def list_smtp_credentials(**query)
      @t.request("GET", "/smtp-credentials", body: nil, query: query)
    end

    # Create
    def create_smtp_credential(body: nil, **query)
      @t.request("POST", "/smtp-credentials", body: body, query: query)
    end

    # Delete
    def delete_smtp_credential(id, **query)
      @t.request("DELETE", "/smtp-credentials/#{esc(id)}", body: nil, query: query)
    end

    # Revoke
    def revoke_smtp_credential(id, **query)
      @t.request("POST", "/smtp-credentials/#{esc(id)}/revoke", body: nil, query: query)
    end

    # List
    def list_smtp_server_groups(**query)
      @t.request("GET", "/smtp-server-groups", body: nil, query: query)
    end

    # Create
    def create_smtp_server_group(body: nil, **query)
      @t.request("POST", "/smtp-server-groups", body: body, query: query)
    end

    # Delete
    def delete_smtp_server_group(id, **query)
      @t.request("DELETE", "/smtp-server-groups/#{esc(id)}", body: nil, query: query)
    end

    # Get
    def get_smtp_server_group(id, **query)
      @t.request("GET", "/smtp-server-groups/#{esc(id)}", body: nil, query: query)
    end

    # Update
    def update_smtp_server_group(id, body: nil, **query)
      @t.request("PATCH", "/smtp-server-groups/#{esc(id)}", body: body, query: query)
    end

    # List
    def list_smtp_servers(**query)
      @t.request("GET", "/smtp-servers", body: nil, query: query)
    end

    # Create
    def create_smtp_server(body: nil, **query)
      @t.request("POST", "/smtp-servers", body: body, query: query)
    end

    # Delete
    def delete_smtp_server(id, **query)
      @t.request("DELETE", "/smtp-servers/#{esc(id)}", body: nil, query: query)
    end

    # Get
    def get_smtp_server(id, **query)
      @t.request("GET", "/smtp-servers/#{esc(id)}", body: nil, query: query)
    end

    # Update
    def update_smtp_server(id, body: nil, **query)
      @t.request("PATCH", "/smtp-servers/#{esc(id)}", body: body, query: query)
    end

    # Disable
    def disable_smtp_server(id, **query)
      @t.request("POST", "/smtp-servers/#{esc(id)}/disable", body: nil, query: query)
    end

    # Enable
    def enable_smtp_server(id, **query)
      @t.request("POST", "/smtp-servers/#{esc(id)}/enable", body: nil, query: query)
    end

    # Test
    def test_smtp_server(id, **query)
      @t.request("POST", "/smtp-servers/#{esc(id)}/test", body: nil, query: query)
    end

    # List
    def list_stylesheets(**query)
      @t.request("GET", "/stylesheets", body: nil, query: query)
    end

    # Create
    def create_stylesheet(body: nil, **query)
      @t.request("POST", "/stylesheets", body: body, query: query)
    end

    # Delete
    def delete_stylesheet(id, **query)
      @t.request("DELETE", "/stylesheets/#{esc(id)}", body: nil, query: query)
    end

    # Get
    def get_stylesheet(id, **query)
      @t.request("GET", "/stylesheets/#{esc(id)}", body: nil, query: query)
    end

    # Update
    def update_stylesheet(id, body: nil, **query)
      @t.request("PUT", "/stylesheets/#{esc(id)}", body: body, query: query)
    end

    # List
    def list_subscriber_lists(**query)
      @t.request("GET", "/subscriber-lists", body: nil, query: query)
    end

    # Create
    def create_subscriber_list(body: nil, **query)
      @t.request("POST", "/subscriber-lists", body: body, query: query)
    end

    # Delete
    def delete_subscriber_list(id, **query)
      @t.request("DELETE", "/subscriber-lists/#{esc(id)}", body: nil, query: query)
    end

    # Get
    def get_subscriber_list(id, **query)
      @t.request("GET", "/subscriber-lists/#{esc(id)}", body: nil, query: query)
    end

    # Update
    def update_subscriber_list(id, body: nil, **query)
      @t.request("PATCH", "/subscriber-lists/#{esc(id)}", body: body, query: query)
    end

    # List members
    def list_subscriber_list_members(id, **query)
      @t.request("GET", "/subscriber-lists/#{esc(id)}/members", body: nil, query: query)
    end

    # Add member
    def create_subscriber_list_member(id, body: nil, **query)
      @t.request("POST", "/subscriber-lists/#{esc(id)}/members", body: body, query: query)
    end

    # Remove member
    def delete_subscriber_list_member(id, subscriber_id, **query)
      @t.request("DELETE", "/subscriber-lists/#{esc(id)}/members/#{esc(subscriber_id)}", body: nil, query: query)
    end

    # Re-add an address that had opted out Needs subscribers:write.
    def resubscribe_subscriber_list(id, body: nil, **query)
      @t.request("POST", "/subscriber-lists/#{esc(id)}/resubscribe", body: body, query: query)
    end

    # Remove an address from a list Needs subscribers:write.
    def unsubscribe_subscriber_list(id, body: nil, **query)
      @t.request("POST", "/subscriber-lists/#{esc(id)}/unsubscribe", body: body, query: query)
    end

    # Preview segment
    def preview_segment_subscriber_list(body: nil, **query)
      @t.request("POST", "/subscriber-lists/preview-segment", body: body, query: query)
    end

    # Add an address to a static list Needs subscribers:write.
    def subscribe_subscriber_list(body: nil, **query)
      @t.request("POST", "/subscriber-lists/subscribe", body: body, query: query)
    end

    # List
    def list_subscribers(**query)
      @t.request("GET", "/subscribers", body: nil, query: query)
    end

    # Create
    def create_subscriber(body: nil, **query)
      @t.request("POST", "/subscribers", body: body, query: query)
    end

    # Delete
    def delete_subscriber(id, **query)
      @t.request("DELETE", "/subscribers/#{esc(id)}", body: nil, query: query)
    end

    # Get
    def get_subscriber(id, **query)
      @t.request("GET", "/subscribers/#{esc(id)}", body: nil, query: query)
    end

    # Update
    def update_subscriber(id, body: nil, **query)
      @t.request("PATCH", "/subscribers/#{esc(id)}", body: body, query: query)
    end

    # Import
    def import_subscriber(body: nil, **query)
      @t.request("POST", "/subscribers/import", body: body, query: query)
    end

    # Import CSV
    def import_csv_subscriber(**query)
      @t.request("POST", "/subscribers/import/csv", body: nil, query: query)
    end

    # Unblock an address Needs suppressions:delete.
    def delete_suppressions(**query)
      @t.request("DELETE", "/suppressions", body: nil, query: query)
    end

    # List blocked addresses Needs suppressions:read.
    def list_suppressions(**query)
      @t.request("GET", "/suppressions", body: nil, query: query)
    end

    # Block an address Needs suppressions:write.
    def create_suppression(body: nil, **query)
      @t.request("POST", "/suppressions", body: body, query: query)
    end

    # List templates Needs templates:read.
    def list_templates(**query)
      @t.request("GET", "/templates", body: nil, query: query)
    end

    # Create
    def create_template(body: nil, **query)
      @t.request("POST", "/templates", body: body, query: query)
    end

    # Delete
    def delete_template(id, **query)
      @t.request("DELETE", "/templates/#{esc(id)}", body: nil, query: query)
    end

    # One template with its version history Needs templates:read.
    def get_template(id, **query)
      @t.request("GET", "/templates/#{esc(id)}", body: nil, query: query)
    end

    # Update
    def update_template(id, body: nil, **query)
      @t.request("PATCH", "/templates/#{esc(id)}", body: body, query: query)
    end

    # Activate
    def activate_template(id, version_id, **query)
      @t.request("POST", "/templates/#{esc(id)}/activate/#{esc(version_id)}", body: nil, query: query)
    end

    # List attachments
    def list_template_attachments(id, **query)
      @t.request("GET", "/templates/#{esc(id)}/attachments", body: nil, query: query)
    end

    # Upload attachment
    def create_template_attachment(id, body: nil, **query)
      @t.request("POST", "/templates/#{esc(id)}/attachments", body: body, query: query)
    end

    # Delete attachment
    def delete_template_attachment(id, att_id, **query)
      @t.request("DELETE", "/templates/#{esc(id)}/attachments/#{esc(att_id)}", body: nil, query: query)
    end

    # Download attachment
    def get_template_attachments_download(id, att_id, **query)
      @t.request("GET", "/templates/#{esc(id)}/attachments/#{esc(att_id)}/download", body: nil, query: query, raw: true)
    end

    # Export
    def get_template_export(id, **query)
      @t.request("GET", "/templates/#{esc(id)}/export", body: nil, query: query)
    end

    # Delete localization
    def delete_template_localization(id, localization_id, **query)
      @t.request("DELETE", "/templates/#{esc(id)}/localizations/#{esc(localization_id)}", body: nil, query: query)
    end

    # Send test
    def send_test_template(id, body: nil, **query)
      @t.request("POST", "/templates/#{esc(id)}/send-test", body: body, query: query)
    end

    # List versions
    def list_template_versions(id, **query)
      @t.request("GET", "/templates/#{esc(id)}/versions", body: nil, query: query)
    end

    # Create version
    def create_template_version(id, body: nil, **query)
      @t.request("POST", "/templates/#{esc(id)}/versions", body: body, query: query)
    end

    # Delete version
    def delete_template_version(id, version_id, **query)
      @t.request("DELETE", "/templates/#{esc(id)}/versions/#{esc(version_id)}", body: nil, query: query)
    end

    # Update version
    def update_template_version(id, version_id, body: nil, **query)
      @t.request("PATCH", "/templates/#{esc(id)}/versions/#{esc(version_id)}", body: body, query: query)
    end

    # List localizations
    def list_template_versions_localizations(id, version_id, **query)
      @t.request("GET", "/templates/#{esc(id)}/versions/#{esc(version_id)}/localizations", body: nil, query: query)
    end

    # Put localization
    def update_template_versions_localization(id, version_id, body: nil, **query)
      @t.request("PUT", "/templates/#{esc(id)}/versions/#{esc(version_id)}/localizations", body: body, query: query)
    end

    # Preview version
    def versions_preview_template(id, version_id, body: nil, **query)
      @t.request("POST", "/templates/#{esc(id)}/versions/#{esc(version_id)}/preview", body: body, query: query)
    end

    # Import
    def import_template(body: nil, **query)
      @t.request("POST", "/templates/import", body: body, query: query)
    end

    # Preview
    def preview_template(body: nil, **query)
      @t.request("POST", "/templates/preview", body: body, query: query)
    end

    # List transactional opt-out scopes Needs suppressions:read.
    def list_unsubscribe_lists(**query)
      @t.request("GET", "/unsubscribe-lists", body: nil, query: query)
    end

    # Create
    def create_unsubscribe_list(body: nil, **query)
      @t.request("POST", "/unsubscribe-lists", body: body, query: query)
    end

    # Delete
    def delete_unsubscribe_list(id, **query)
      @t.request("DELETE", "/unsubscribe-lists/#{esc(id)}", body: nil, query: query)
    end

    # One opt-out scope Needs suppressions:read.
    def get_unsubscribe_list(id, **query)
      @t.request("GET", "/unsubscribe-lists/#{esc(id)}", body: nil, query: query)
    end

    # Update
    def update_unsubscribe_list(id, body: nil, **query)
      @t.request("PATCH", "/unsubscribe-lists/#{esc(id)}", body: body, query: query)
    end

    # Usage
    def list_usage(**query)
      @t.request("GET", "/usage", body: nil, query: query)
    end

    # List outgoing webhooks Needs webhooks:read.
    def list_webhooks(**query)
      @t.request("GET", "/webhooks", body: nil, query: query)
    end

    # Create an outgoing webhook Needs webhooks:write.
    def create_webhook(body: nil, **query)
      @t.request("POST", "/webhooks", body: body, query: query)
    end

    # Delete a webhook Needs webhooks:delete.
    def delete_webhook(id, **query)
      @t.request("DELETE", "/webhooks/#{esc(id)}", body: nil, query: query)
    end

    # Delivery log of one webhook Needs webhooks:read.
    def list_webhook_deliveries(id, **query)
      @t.request("GET", "/webhooks/#{esc(id)}/deliveries", body: nil, query: query)
    end

    # Re-enable a disabled webhook Needs webhooks:write.
    def enable_webhook(id, **query)
      @t.request("POST", "/webhooks/#{esc(id)}/enable", body: nil, query: query)
    end

    # Rotate a webhook's signing secret Needs webhooks:write.
    def rotate_secret_webhook(id, **query)
      @t.request("POST", "/webhooks/#{esc(id)}/rotate-secret", body: nil, query: query)
    end

    # Ingest a bounce report Needs bounces:write.
    def bounce_webhook(body: nil, **query)
      @t.request("POST", "/webhooks/bounce", body: body, query: query)
    end

  end
end
