// Mailyard, Copyright (c) 2021-2026 YouSysAdmin

package template

import "github.com/yousysadmin/mailyard/internal/core/apidoc"

// ConsoleDocs describes this domain's slice of the console API.
//
// Generated, then kept honest by TestEveryConsoleRouteIsDocumented:
// the routes come from routes.go and the shapes from the response
// types each handler actually constructs, which is readable only
// because every handler returns a declared type rather than a map.
// Edit the summaries and descriptions freely - they are the half a
// generator cannot know.
func ConsoleDocs() []apidoc.Route {
	return []apidoc.Route{
		{
			Method:      "GET",
			Path:        "/templates/",
			Tag:         "template",
			Summary:     "List",
			Description: "Needs the `templates:read` permission.",
			Responses:   []apidoc.Response{apidoc.OK("The result.", ListResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/templates/",
			Tag:         "template",
			Summary:     "Create",
			Description: "Needs the `templates:write` permission.",
			Request:     createInput{},
			Responses:   []apidoc.Response{apidoc.Created("The result.", TemplateResponse{})},
		},
		{
			Method:      "DELETE",
			Path:        "/templates/:id",
			Tag:         "template",
			Summary:     "Delete",
			Description: "Needs the `templates:delete` permission.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Responses:   []apidoc.Response{apidoc.NoContent},
		},
		{
			Method:      "GET",
			Path:        "/templates/:id",
			Tag:         "template",
			Summary:     "Get",
			Description: "Needs the `templates:read` permission.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Responses:   []apidoc.Response{apidoc.OK("The result.", GetResponse{})},
		},
		{
			Method:      "PATCH",
			Path:        "/templates/:id",
			Tag:         "template",
			Summary:     "Update",
			Description: "Needs the `templates:write` permission.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Request:     updateInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", TemplateResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/templates/:id/activate/:versionId",
			Tag:         "template",
			Summary:     "Activate",
			Description: "Needs the `templates:write` permission.",
			PathParams:  []apidoc.Param{{Name: "id"}, {Name: "versionId"}},
			Responses:   []apidoc.Response{apidoc.OK("The result.", ActiveVersionResponse{})},
		},
		{
			Method:      "GET",
			Path:        "/templates/:id/attachments",
			Tag:         "template",
			Summary:     "List attachments",
			Description: "Needs the `templates:read` permission.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Responses:   []apidoc.Response{apidoc.OK("The result.", AttachmentListResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/templates/:id/attachments",
			Tag:         "template",
			Summary:     "Upload attachment",
			Description: "Needs the `templates:write` permission.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Request:     attachmentInput{},
			Responses:   []apidoc.Response{apidoc.Created("The result.", AttachmentResponse{})},
		},
		{
			Method:      "DELETE",
			Path:        "/templates/:id/attachments/:attId",
			Tag:         "template",
			Summary:     "Delete attachment",
			Description: "Needs the `templates:delete` permission.",
			PathParams:  []apidoc.Param{{Name: "id"}, {Name: "attId"}},
			Responses:   []apidoc.Response{apidoc.NoContent},
		},
		{
			Method:      "GET",
			Path:        "/templates/:id/attachments/:attId/download",
			Tag:         "template",
			Summary:     "Download attachment",
			Description: "Needs the `templates:read` permission.",
			PathParams:  []apidoc.Param{{Name: "id"}, {Name: "attId"}},
			Responses:   []apidoc.Response{apidoc.OctetStream("The decoded attachment bytes.")},
		},
		{
			Method:      "GET",
			Path:        "/templates/:id/export",
			Tag:         "template",
			Summary:     "Export",
			Description: "Needs the `templates:read` permission.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Responses:   []apidoc.Response{apidoc.OK("The result.", ExportResponse{})},
		},
		{
			Method:      "DELETE",
			Path:        "/templates/:id/localizations/:localizationId",
			Tag:         "template",
			Summary:     "Delete localization",
			Description: "Needs the `templates:delete` permission.",
			PathParams:  []apidoc.Param{{Name: "id"}, {Name: "localizationId"}},
			Responses:   []apidoc.Response{apidoc.NoContent},
		},
		{
			Method:      "GET",
			Path:        "/templates/:id/versions",
			Tag:         "template",
			Summary:     "List versions",
			Description: "Needs the `templates:read` permission.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Responses:   []apidoc.Response{apidoc.OK("The result.", VersionListResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/templates/:id/versions",
			Tag:         "template",
			Summary:     "Create version",
			Description: "Needs the `templates:write` permission.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Request:     versionInput{},
			Responses:   []apidoc.Response{apidoc.Created("The result.", VersionResponse{})},
		},
		{
			Method:      "DELETE",
			Path:        "/templates/:id/versions/:versionId",
			Tag:         "template",
			Summary:     "Delete version",
			Description: "Needs the `templates:delete` permission.",
			PathParams:  []apidoc.Param{{Name: "id"}, {Name: "versionId"}},
			Responses:   []apidoc.Response{apidoc.NoContent},
		},
		{
			Method:      "PATCH",
			Path:        "/templates/:id/versions/:versionId",
			Tag:         "template",
			Summary:     "Update version",
			Description: "Needs the `templates:write` permission.",
			PathParams:  []apidoc.Param{{Name: "id"}, {Name: "versionId"}},
			Request:     versionInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", VersionResponse{})},
		},
		{
			Method:      "GET",
			Path:        "/templates/:id/versions/:versionId/localizations",
			Tag:         "template",
			Summary:     "List localizations",
			Description: "Needs the `templates:read` permission.",
			PathParams:  []apidoc.Param{{Name: "id"}, {Name: "versionId"}},
			Responses:   []apidoc.Response{apidoc.OK("The result.", LocalizationListResponse{})},
		},
		{
			Method:      "PUT",
			Path:        "/templates/:id/versions/:versionId/localizations",
			Tag:         "template",
			Summary:     "Put localization",
			Description: "Needs the `templates:write` permission.",
			PathParams:  []apidoc.Param{{Name: "id"}, {Name: "versionId"}},
			Request:     localizationInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", LocalizationResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/templates/:id/versions/:versionId/preview",
			Tag:         "template",
			Summary:     "Preview version",
			Description: "Needs the `templates:read` permission.",
			PathParams:  []apidoc.Param{{Name: "id"}, {Name: "versionId"}},
			Request:     versionPreviewInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", RenderLanguageResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/templates/import",
			Tag:         "template",
			Summary:     "Import",
			Description: "Needs the `templates:write` permission.",
			Request:     transferDoc{},
			Responses:   []apidoc.Response{apidoc.Created("The result.", TemplateResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/templates/preview",
			Tag:         "template",
			Summary:     "Preview",
			Description: "Needs the `templates:read` permission.",
			Request:     previewInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", RenderResponse{})},
		},
	}
}
