// Mailyard, Copyright (c) 2021-2026 YouSysAdmin

package tests

import (
	"regexp"
	"sort"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/yousysadmin/mailyard/internal/openapi"
)

// secretish names a field that has no business coming back.
var secretish = regexp.MustCompile(`(?i)password|secret|token|hash|private_key|totp`)

// allowedSecretFields are the ones that are supposed to come back.
//
// Almost every entry is a SHOW-once credential: something the caller
// can never retrieve again, so the document has to say it is there or
// whoever created it has no way to use what they made.
//
// Request bodies are not in this list and never should be. Sending a
// password to configure an SMTP server, or to sign in, is the request
// working - see publishedSchemas for why the check no longer sees them.
var allowedSecretFields = map[string]bool{
	"WebhookCreateResponse.secret":           true,
	"CreatedResponse.token":                  true, // an API key, hashed at rest
	"SmtpcredentialCreatedResponse.password": true,
	"CredentialCreatedResponse.password":     true,
	"InvitationCreatedResponse.token":        true, // needed to build the invite link
	"AdminCreatedResponse.token":             true, // a platform credential, hashed at rest
	// The TOTP seed, returned once so the console can render the QR
	// code. Sealed at rest by the crypto service and never readable
	// again through any endpoint.
	"TOTPSetupResponse.secret": true,

	// Not a credential at all: the DNS TXT value the project has to
	// publish to prove it controls the zone. Useless to anyone who
	// cannot edit that DNS, and useless to the owner if we hide it.
	"Domain.verification_token": true,
	// BOOLEANS whose names match the pattern. The values are public,
	// and the account settings page and the sign-in screen cannot
	// render without them.
	"User.totp_enabled":                       true,
	"TOTPStateResponse.totp_enabled":          true,
	"AuthInfoResponse.password_reset_enabled": true,
	// Whether an identity provider has a client secret, never the secret
	// itself - the console renders "configured" from this and the model
	// keeps ClientSecret `json:"-"`. Same shape as the booleans above.
	"ProviderView.has_secret": true,
	// An IdP's token ENDPOINT, which is a public URL out of its
	// discovery document. It matches on the word "token" and is not one.
	"ProviderView.token_url": true,
}

// The enterprise build describes routes the community one does not, and
// one of them returns a credential.
//
// It cannot live in the map above: TestEveryAllowedSecretStillExists
// fails on an entry matching no field, deliberately, so an excuse
// cannot outlive the thing it excuses. In the community document
// registerOutput is described nowhere, because the route that returns
// it is not registered - which is the whole point of the split, and is
// also why the entry has to move with it.
func init() {
	if enterpriseBuild {
		// A relay node's control credential, shown once at enrolment.
		allowedSecretFields["registerOutput.token"] = true
	}
}

// These two entries, and the type they belong to, arrived together: the
// oauth provider view was a fiber.Map, so reflection saw an untyped
// object and this guard could not read a single one of its fields. The
// secret was kept off the wire by the view naming its fields by hand,
// which is exactly the unchecked half. Declaring the type is what put it
// under this test, and the first thing the test did was ask about these
// two - which is the guard working, not a regression.

// TestTheDocumentPublishesNoSecrets is the guard the reflector made
// necessary.
//
// While the document was written by hand, a field only appeared in it
// if somebody typed it. Now it lists whatever the response types
// carry, which means the single thing keeping a sealed column out of a
// public document is `json:"-"` on the model field. That tag is one
// keystroke from being forgotten, and the failure would be silent:
// the document still builds, the endpoint still answers, and an SMTP
// password is now in the API description every integrator downloads.
//
// The check is deliberately by name rather than by type. A leak would
// come from a field somebody added without thinking about this
// document, and its name is the one thing such a field reliably has.
//
// Both documents. This checked only the machine one until the product
// surface moved onto it, at which point fields it had never seen
// arrived all at once - every one legitimate, and none ever checked,
// because the console document was generated by the same reflector and
// inspected by nothing.
func TestTheDocumentPublishesNoSecrets(t *testing.T) {
	for _, s := range []struct {
		name  string
		build func() ([]byte, error)
	}{
		{"machine", openapi.MachineSpec},
		{"console", openapi.ConsoleSpec},
	} {
		t.Run(s.name, func(t *testing.T) {
			for name, fields := range publishedSchemas(t, s.build) {
				for _, field := range fields {
					if !secretish.MatchString(field) {
						continue
					}

					key := name + "." + field
					if allowedSecretFields[key] {
						continue
					}

					t.Errorf("%s is RETURNED by this API and looks like a secret.\n"+
						"Mark the model field `json:\"-\"` so it never reaches a response, "+
						"or add %q to allowedSecretFields saying which show-once "+
						"credential it is.", key, key)
				}
			}
		})
	}
}

// publishedSchemas returns the schemas a caller can actually RECEIVE,
// mapped to their field names.
//
// Reachability from a RESPONSE, not every schema in the document. The
// first version checked all of them, so every login form and every
// create-a-user body had to be allowlisted for carrying a password -
// and an allowlist that fills up with things which were never leaks is
// one nobody reads, which is exactly where a real leak would hide.
//
// Transitive, because a secret nested two types deep is published just
// as thoroughly as one at the top.
func publishedSchemas(t *testing.T, build func() ([]byte, error)) map[string][]string {
	t.Helper()
	raw, err := build()
	if err != nil {
		t.Fatalf("building the document: %v", err)
	}

	var doc map[string]any
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("parsing the document: %v", err)
	}

	schemas, _ := dig(doc, "components", "schemas").(map[string]any)
	if len(schemas) == 0 {
		t.Fatal("no schemas in the document - this test would pass vacuously")
	}

	// Roots: everything referenced from a response body.
	var pending []string
	paths, _ := doc["paths"].(map[string]any)
	for _, item := range paths {
		ops, _ := item.(map[string]any)
		for _, op := range ops {
			o, ok := op.(map[string]any)
			if !ok {
				continue
			}

			pending = append(pending, schemaRefs(o["responses"])...)
		}
	}

	if len(pending) == 0 {
		t.Fatal("no response schemas found - this test would pass vacuously")
	}

	out := map[string][]string{}
	seen := map[string]bool{}
	for len(pending) > 0 {
		name := pending[0]
		pending = pending[1:]
		if seen[name] {
			continue
		}

		seen[name] = true
		s, ok := schemas[name].(map[string]any)
		if !ok {
			continue
		}

		if props, ok := s["properties"].(map[string]any); ok {
			fields := make([]string, 0, len(props))
			for f := range props {
				fields = append(fields, f)
			}

			sort.Strings(fields)
			out[name] = fields
		}

		pending = append(pending, schemaRefs(s)...)
	}

	return out
}

// dig walks nested maps by key.
func dig(node any, keys ...string) any {
	for _, k := range keys {
		m, ok := node.(map[string]any)
		if !ok {
			return nil
		}

		node = m[k]
	}

	return node
}

// schemaRefs collects every schema name referenced anywhere under node.
func schemaRefs(node any) []string {
	var out []string
	switch v := node.(type) {
	case map[string]any:
		for k, child := range v {
			if k == "$ref" {
				if s, ok := child.(string); ok {
					out = append(out, strings.TrimPrefix(s, "#/components/schemas/"))
				}

				continue
			}

			out = append(out, schemaRefs(child)...)
		}
	case []any:
		for _, child := range v {
			out = append(out, schemaRefs(child)...)
		}
	}

	return out
}

// TestEveryAllowedSecretStillExists keeps the allowlist honest in the
// other direction: an entry whose field is gone is a stale exemption
// that would silently cover a future field of the same name.
func TestEveryAllowedSecretStillExists(t *testing.T) {
	present := map[string]bool{}
	for _, build := range []func() ([]byte, error){openapi.MachineSpec, openapi.ConsoleSpec} {
		for name, fields := range publishedSchemas(t, build) {
			for _, f := range fields {
				present[name+"."+f] = true
			}
		}
	}

	for key := range allowedSecretFields {
		if !present[key] {
			t.Errorf("allowedSecretFields names %s but no document returns that field - "+
				"drop the entry, or it will silently cover a future field of the same name", key)
		}
	}
}
