// Mailyard, Copyright (c) 2021-2026 YouSysAdmin

package sdkgen

import (
	"fmt"
	"strings"
)

// RenderPython writes the generated half of the Python client.
func RenderPython() map[string]string {
	ms := scriptMethods()

	var b strings.Builder
	b.WriteString(`"""Every /api/v1 route, one method each.

Generated by cmd/sdkgen from the same route metadata the OpenAPI
document is built from - do not edit. Run ` + "`task sdk-gen`" + `.

A body is a plain dict and a result is whatever the API answered,
parsed. The schemas are in the OpenAPI document:

    mailyard export-api-spec --out openapi.yaml
"""

from typing import Any, Mapping, Optional
from urllib.parse import quote


def _esc(value: Any) -> str:
    """Percent-encode one path segment.

    safe="" so a separator is encoded rather than passed through: an id
    of "../users/x" would otherwise reroute the request to another
    endpoint, and one containing "?" or "#" would inject a query or
    truncate the path. The Go client escapes the same values - these
    two just interpolated them raw.
    """
    return quote(str(value), safe="")


class API:
    """The route surface. Reached as ` + "`client.api`" + `."""

    def __init__(self, transport):
        self._t = transport

`)

	for _, m := range ms {
		args := []string{"self"}
		args = append(args, m.PathParams...)
		if m.HasBody {
			args = append(args, "body: Optional[Mapping[str, Any]] = None")
		}

		args = append(args, "**query: Any")

		ret := "Any"
		if m.Raw {
			ret = "bytes"
		}

		fmt.Fprintf(&b, "    def %s(%s) -> %s:\n", m.Name, strings.Join(args, ", "), ret)
		fmt.Fprintf(&b, "        %q\n", pyDoc(m))

		var path string
		if len(m.PathParams) > 0 {
			path = "f\"" + pyPath(m.Path) + "\""
		} else {
			path = fmt.Sprintf("%q", m.Path)
		}

		body := "None"
		if m.HasBody {
			body = "body"
		}

		raw := ""
		if m.Raw {
			raw = ", raw=True"
		}

		fmt.Fprintf(&b, "        return self._t.request(%q, %s, body=%s, query=query%s)\n\n",
			m.HTTPMethod, path, body, raw)
	}

	return map[string]string{"api.py": b.String()}
}

// RenderRuby writes the generated half of the Ruby client.
func RenderRuby() map[string]string {
	ms := scriptMethods()

	var b strings.Builder
	b.WriteString(`# frozen_string_literal: true

# Every /api/v1 route, one method each.
#
# Generated by cmd/sdkgen from the same route metadata the OpenAPI
# document is built from - do not edit. Run ` + "`task sdk-gen`" + `.
#
# A body is a plain Hash and a result is whatever the API answered,
# parsed. The schemas are in the OpenAPI document:
#
#   mailyard export-api-spec --out openapi.yaml

require "uri"

module Mailyard
  # The route surface. Reached as +client.api+.
  class API
    def initialize(transport)
      @t = transport
    end

    # Percent-encode one path segment.
    #
    # Everything outside RFC 3986's unreserved set goes, separators
    # included: an id of "../users/x" would otherwise reroute the
    # request to another endpoint, and one holding "?" or "#" would
    # inject a query or truncate the path. A space or a non-ASCII byte
    # also raised URI::InvalidURIError out of the transport, so this
    # fixes an outright crash as well.
    def esc(value)
      URI::DEFAULT_PARSER.escape(value.to_s, /[^A-Za-z0-9\-._~]/)
    end

`)

	for _, m := range ms {
		// Path parameters positional, everything else by keyword. A
		// trailing positional hash is swallowed as the first argument
		// at the call site, so create_template(body: {...}) sent
		// {"body": {...}} and the server answered "Name is required".
		args := append([]string{}, m.PathParams...)
		if m.HasBody {
			args = append(args, "body: nil")
		}

		args = append(args, "**query")

		fmt.Fprintf(&b, "    # %s\n", pyDoc(m))
		fmt.Fprintf(&b, "    def %s(%s)\n", m.Name, strings.Join(args, ", "))

		path := "\"" + rubyPath(m.Path) + "\""
		body := "nil"
		if m.HasBody {
			body = "body"
		}

		raw := ""
		if m.Raw {
			raw = ", raw: true"
		}

		fmt.Fprintf(&b, "      @t.request(%q, %s, body: %s, query: query%s)\n    end\n\n",
			m.HTTPMethod, path, body, raw)
	}

	b.WriteString("  end\nend\n")

	return map[string]string{"api.rb": b.String()}
}

// interpolatePath rewrites every {name} placeholder into the target
// language's interpolation, with the value passed through that
// language's escape helper.
//
// The escape is not decoration. A path parameter reaches these clients
// as an ordinary string, so an id of "../users/x" walked the URL up a
// level and hit a different endpoint, and one carrying "?" or "#"
// injected a query or truncated the path. The Go generator has escaped
// these since it was written - script.go rendered them raw.
//
// Built left to right rather than by replacing in place: a replacement
// introduces a brace of its own, and scanning the result again finds
// it forever.
func interpolatePath(p, prefix, esc string) string {
	var b strings.Builder
	for {
		i := strings.Index(p, "{")
		if i == -1 {
			b.WriteString(p)

			return b.String()
		}

		j := strings.Index(p[i:], "}")
		if j == -1 {
			b.WriteString(p)

			return b.String()
		}

		b.WriteString(p[:i])
		b.WriteString(prefix + "{" + esc + "(" + p[i+1:i+j] + ")}")
		p = p[i+j+1:]
	}
}

// pyPath turns {id} into an f-string slot that escapes the value.
func pyPath(p string) string { return interpolatePath(p, "", "_esc") }

// rubyPath turns {id} into Ruby's #{...} interpolation, escaping the
// value.
func rubyPath(p string) string { return interpolatePath(p, "#", "esc") }
