// Mailyard, Copyright (c) 2021-2026 YouSysAdmin

package auth

import "github.com/yousysadmin/mailyard/internal/core/apidoc"

// ConsoleDocs describes this domain's slice of the console API.
//
// Generated, then kept honest by TestEveryConsoleRouteIsDocumented:
// the routes come from routes.go and the shapes from the response
// types each handler actually constructs, which is readable only
// because every handler returns a declared type rather than a map.
// Edit the summaries and descriptions freely - they are the half a
// generator cannot know.
func ConsoleDocs() []apidoc.Route {
	return []apidoc.Route{
		{
			Method:      "POST",
			Path:        "/auth/2fa/disable",
			Summary:     "T o t p disable",
			Description: "Any signed-in account.",
			Request:     totpCodeInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", TOTPStateResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/2fa/enable",
			Summary:     "Turn two-factor auth on",
			Description: "Any signed-in account. The response carries the recovery codes, shown here and never again.",
			Request:     totpCodeInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", TOTPStateResponse{})},
		},
		{
			Method:      "GET",
			Path:        "/auth/2fa/recovery-codes",
			Summary:     "Count the unspent recovery codes",
			Description: "Any signed-in account.",
			Responses:   []apidoc.Response{apidoc.OK("The result.", RecoveryCodesStatusResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/2fa/recovery-codes",
			Summary:     "Generate a fresh set of recovery codes",
			Description: "Any signed-in account, proving the password. Voids the previous set. Shown once.",
			Request:     passkeyReauthInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", RecoveryCodesResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/2fa/setup",
			Summary:     "T o t p setup",
			Description: "Any signed-in account, proving the password.",
			Request:     totpSetupInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", TOTPSetupResponse{})},
		},
		{
			Method:      "GET",
			Path:        "/auth/info",
			Summary:     "Info",
			Description: "Open, no session needed.",
			Responses:   []apidoc.Response{apidoc.OK("The result.", AuthDisabledResponse{}), apidoc.OK("The result.", AuthInfoResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/login",
			Summary:     "Login",
			Description: "Open, no session needed.",
			Request:     loginInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", UserResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/logout",
			Summary:     "Logout",
			Description: "Open, no session needed.",
			Responses:   []apidoc.Response{apidoc.NoContent},
		},
		{
			Method:      "GET",
			Path:        "/auth/me",
			Summary:     "Me",
			Description: "Any signed-in account.",
			Responses:   []apidoc.Response{apidoc.OK("The result.", AuthDisabledResponse{}), apidoc.OK("The result.", UserResponse{})},
		},
		{
			Method:      "GET",
			Path:        "/auth/oauth/:slug/callback",
			Summary:     "O auth callback",
			Description: "The provider's redirect back, carrying either a code or an error.",
			PathParams:  []apidoc.Param{{Name: "slug"}},
			Query: []apidoc.Param{
				{Name: "code", Description: "The authorization code to exchange."},
				{Name: "state", Description: "The state issued by the start step."},
				{Name: "error", Description: "The provider's error code when it refused."},
				{Name: "error_description", Description: "The provider's explanation of the error."},
			},
			Responses: []apidoc.Response{apidoc.Redirect(302, "The console, signed in, or its sign-in page asking for the two-factor code.")},
		},
		{
			Method:      "POST",
			Path:        "/auth/oauth/2fa",
			Summary:     "Identity provider second factor",
			Description: "Open, no session needed. Finishes an identity provider sign-in for an account with two-factor auth on, carried by the cookie the callback set.",
			Request:     oidcSecondFactorInput{},
			Responses:   []apidoc.Response{apidoc.OK("The account, now signed in.", OIDCSecondFactorResponse{})},
		},
		{
			Method:      "GET",
			Path:        "/auth/oauth/:slug/start",
			Summary:     "O auth start",
			Description: "Begins the sign-in with this provider.",
			PathParams:  []apidoc.Param{{Name: "slug"}},
			Query: []apidoc.Param{
				{Name: "invite", Description: "An invitation token to accept once signed in."},
			},
			Responses: []apidoc.Response{apidoc.Redirect(302, "The provider's authorization endpoint.")},
		},
		{
			Method:      "POST",
			Path:        "/auth/passkey/login/begin",
			Summary:     "Passkey login begin",
			Description: "Open, no session needed.",
			Responses:   []apidoc.Response{apidoc.OK("WebAuthn assertion options, passed to the browser unchanged.", PasskeyChallengeResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/passkey/login/finish",
			Summary:     "Passkey login finish",
			Description: "Open, no session needed.",
			Responses:   []apidoc.Response{apidoc.OK("The result.", UserResponse{})},
		},
		{
			Method:      "GET",
			Path:        "/auth/passkeys",
			Summary:     "Passkey list",
			Description: "Any signed-in account.",
			Responses:   []apidoc.Response{apidoc.OK("The result.", PasskeyListResponse{})},
		},
		{
			Method:      "PATCH",
			Path:        "/auth/passkeys/:id",
			Summary:     "Passkey rename",
			Description: "Any signed-in account.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Request:     passkeyRenameInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", RenamedResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/passkeys/:id/delete",
			Summary:     "Passkey delete",
			Description: "Any signed-in account. Proves the password.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Request:     passkeyReauthInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", RemovedResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/passkeys/register/begin",
			Summary:     "Passkey register begin",
			Description: "Any signed-in account. Proves the password.",
			Request:     passkeyReauthInput{},
			Responses:   []apidoc.Response{apidoc.OK("WebAuthn creation options, passed to the browser unchanged.", PasskeyChallengeResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/passkeys/register/finish",
			Summary:     "Passkey register finish",
			Description: "Any signed-in account.",
			Query: []apidoc.Param{
				{Name: "name", Description: "A label for the new passkey, truncated to 60 characters."},
			},
			Responses: []apidoc.Response{apidoc.Created("The result.", PasskeyResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/password",
			Summary:     "Change your own password",
			Description: "Any signed-in account with a local password.",
			Request:     changePasswordInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", MessageResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/password-reset/confirm",
			Summary:     "Password reset confirm",
			Description: "Open, no session needed.",
			Request:     resetConfirmInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", MessageResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/password-reset/request",
			Summary:     "Password reset request",
			Description: "Open, no session needed.",
			Request:     resetRequestInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", MessageResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/register",
			Summary:     "Register",
			Description: "Open, no session needed. Registered only when self-signup is enabled.",
			Request:     registerInput{},
			Responses:   []apidoc.Response{apidoc.Created("The result.", RegisterPendingResponse{}), apidoc.Created("The result.", UserResponse{})},
		},
		{
			Method:      "GET",
			Path:        "/auth/sessions",
			Summary:     "List sessions",
			Description: "Any signed-in account.",
			Responses:   []apidoc.Response{apidoc.OK("The result.", SessionListResponse{})},
		},
		{
			Method:      "DELETE",
			Path:        "/auth/sessions/:id",
			Summary:     "Revoke session",
			Description: "Any signed-in account.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Responses:   []apidoc.Response{apidoc.OK("The result.", RevokedResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/sessions/revoke-others",
			Summary:     "Revoke other sessions",
			Description: "Any signed-in account.",
			Responses:   []apidoc.Response{apidoc.OK("The result.", RevokedResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/verify-email",
			Summary:     "Verify email confirm",
			Description: "Open, no session needed.",
			Request:     verifyConfirmInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", MessageResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/verify-email/resend",
			Summary:     "Verify email resend",
			Description: "Open, no session needed.",
			Request:     verifyResendInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", MessageResponse{})},
		},
		{
			Method:      "GET",
			Path:        "/system-mail",
			Summary:     "System mail status",
			Description: "Platform admin.",
			Responses:   []apidoc.Response{apidoc.OK("The result.", SystemMailStatusResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/system-mail/test",
			Summary:     "System mail test",
			Description: "Platform admin.",
			Request:     systemMailTestInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", MessageResponse{})},
		},
	}
}
