// Mailyard, Copyright (c) 2021-2026 YouSysAdmin

package auth

import "github.com/yousysadmin/mailyard/internal/core/apidoc"

// ConsoleDocs describes this domain's slice of the console API.
//
// Generated, then kept honest by TestEveryConsoleRouteIsDocumented:
// the routes come from routes.go and the shapes from the response
// types each handler actually constructs, which is readable only
// because every handler returns a declared type rather than a map.
// Edit the summaries and descriptions freely - they are the half a
// generator cannot know.
func ConsoleDocs() []apidoc.Route {
	return []apidoc.Route{
		{
			Method:      "POST",
			Path:        "/auth/2fa/disable",
			Tag:         "auth",
			Summary:     "T o t p disable",
			Description: "Any signed-in member.",
			Request:     totpCodeInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", TOTPStateResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/2fa/enable",
			Tag:         "auth",
			Summary:     "Turn two-factor auth on",
			Description: "Any signed-in member. The response carries the recovery codes, shown here and never again.",
			Request:     totpCodeInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", TOTPStateResponse{})},
		},
		{
			Method:      "GET",
			Path:        "/auth/2fa/recovery-codes",
			Tag:         "auth",
			Summary:     "Count the unspent recovery codes",
			Description: "Any signed-in member.",
			Responses:   []apidoc.Response{apidoc.OK("The result.", RecoveryCodesStatusResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/2fa/recovery-codes",
			Tag:         "auth",
			Summary:     "Generate a fresh set of recovery codes",
			Description: "Any signed-in member, proving the password. Voids the previous set. Shown once.",
			Request:     passkeyReauthInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", RecoveryCodesResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/2fa/setup",
			Tag:         "auth",
			Summary:     "T o t p setup",
			Description: "Any signed-in member.",
			Responses:   []apidoc.Response{apidoc.OK("The result.", TOTPSetupResponse{})},
		},
		{
			Method:      "GET",
			Path:        "/auth/info",
			Tag:         "auth",
			Summary:     "Info",
			Description: "Any signed-in member.",
			Responses:   []apidoc.Response{apidoc.OK("The result.", AuthDisabledResponse{}), apidoc.OK("The result.", AuthInfoResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/login",
			Tag:         "auth",
			Summary:     "Login",
			Description: "Any signed-in member.",
			Request:     loginInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", UserResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/logout",
			Tag:         "auth",
			Summary:     "Logout",
			Description: "Any signed-in member.",
			Responses:   []apidoc.Response{apidoc.NoContent},
		},
		{
			Method:      "GET",
			Path:        "/auth/me",
			Tag:         "auth",
			Summary:     "Me",
			Description: "Any signed-in member.",
			Responses:   []apidoc.Response{apidoc.OK("The result.", AuthDisabledResponse{}), apidoc.OK("The result.", UserResponse{})},
		},
		{
			Method:      "GET",
			Path:        "/auth/oauth/:slug/callback",
			Tag:         "auth",
			Summary:     "O auth callback",
			Description: "Any signed-in member.",
			PathParams:  []apidoc.Param{{Name: "slug"}},
			Responses:   []apidoc.Response{apidoc.Redirect(302, "The console, signed in.")},
		},
		{
			Method:      "GET",
			Path:        "/auth/oauth/:slug/start",
			Tag:         "auth",
			Summary:     "O auth start",
			Description: "Any signed-in member.",
			PathParams:  []apidoc.Param{{Name: "slug"}},
			Responses:   []apidoc.Response{apidoc.Redirect(302, "The provider's authorization endpoint.")},
		},
		{
			Method:      "POST",
			Path:        "/auth/passkey/login/begin",
			Tag:         "auth",
			Summary:     "Passkey login begin",
			Description: "Any signed-in member.",
			Responses:   []apidoc.Response{apidoc.OK("WebAuthn assertion options, passed to the browser unchanged.", PasskeyChallengeResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/passkey/login/finish",
			Tag:         "auth",
			Summary:     "Passkey login finish",
			Description: "Any signed-in member.",
			Responses:   []apidoc.Response{apidoc.OK("The result.", UserResponse{})},
		},
		{
			Method:      "GET",
			Path:        "/auth/passkeys",
			Tag:         "auth",
			Summary:     "Passkey list",
			Description: "Any signed-in member.",
			Responses:   []apidoc.Response{apidoc.OK("The result.", PasskeyListResponse{})},
		},
		{
			Method:      "PATCH",
			Path:        "/auth/passkeys/:id",
			Tag:         "auth",
			Summary:     "Passkey rename",
			Description: "Any signed-in member.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Request:     passkeyRenameInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", RenamedResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/passkeys/:id/delete",
			Tag:         "auth",
			Summary:     "Passkey delete",
			Description: "Any signed-in member.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Request:     passkeyReauthInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", RemovedResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/passkeys/register/begin",
			Tag:         "auth",
			Summary:     "Passkey register begin",
			Description: "Any signed-in member.",
			Request:     passkeyReauthInput{},
			Responses:   []apidoc.Response{apidoc.OK("WebAuthn creation options, passed to the browser unchanged.", PasskeyChallengeResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/passkeys/register/finish",
			Tag:         "auth",
			Summary:     "Passkey register finish",
			Description: "Any signed-in member.",
			Responses:   []apidoc.Response{apidoc.Created("The result.", PasskeyResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/password",
			Tag:         "auth",
			Summary:     "Change your own password",
			Description: "Any signed-in member with a local account.",
			Request:     changePasswordInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", MessageResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/password-reset/confirm",
			Tag:         "auth",
			Summary:     "Password reset confirm",
			Description: "Any signed-in member.",
			Request:     resetConfirmInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", MessageResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/password-reset/request",
			Tag:         "auth",
			Summary:     "Password reset request",
			Description: "Any signed-in member.",
			Request:     resetRequestInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", MessageResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/register",
			Tag:         "auth",
			Summary:     "Register",
			Description: "Any signed-in member.",
			Request:     registerInput{},
			Responses:   []apidoc.Response{apidoc.Created("The result.", RegisterPendingResponse{}), apidoc.Created("The result.", UserResponse{})},
		},
		{
			Method:      "GET",
			Path:        "/auth/sessions",
			Tag:         "auth",
			Summary:     "List sessions",
			Description: "Any signed-in member.",
			Responses:   []apidoc.Response{apidoc.OK("The result.", SessionListResponse{})},
		},
		{
			Method:      "DELETE",
			Path:        "/auth/sessions/:id",
			Tag:         "auth",
			Summary:     "Revoke session",
			Description: "Any signed-in member.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Responses:   []apidoc.Response{apidoc.OK("The result.", RevokedResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/sessions/revoke-others",
			Tag:         "auth",
			Summary:     "Revoke other sessions",
			Description: "Any signed-in member.",
			Responses:   []apidoc.Response{apidoc.OK("The result.", RevokedResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/verify-email",
			Tag:         "auth",
			Summary:     "Verify email confirm",
			Description: "Any signed-in member.",
			Request:     verifyConfirmInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", UserResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/auth/verify-email/resend",
			Tag:         "auth",
			Summary:     "Verify email resend",
			Description: "Any signed-in member.",
			Request:     verifyResendInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", MessageResponse{})},
		},
		{
			Method:      "GET",
			Path:        "/system-mail",
			Tag:         "auth",
			Summary:     "System mail status",
			Description: "Platform admin.",
			Responses:   []apidoc.Response{apidoc.OK("The result.", SystemMailStatusResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/system-mail/test",
			Tag:         "auth",
			Summary:     "System mail test",
			Description: "Platform admin.",
			Request:     systemMailTestInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", MessageResponse{})},
		},
	}
}
