// Mailyard, Copyright (c) 2021-2026 YouSysAdmin

package project

import "github.com/yousysadmin/mailyard/internal/core/apidoc"

// ConsoleDocs describes this domain's slice of the console API.
//
// Generated, then kept honest by TestEveryConsoleRouteIsDocumented:
// the routes come from routes.go and the shapes from the response
// types each handler actually constructs, which is readable only
// because every handler returns a declared type rather than a map.
// Edit the summaries and descriptions freely - they are the half a
// generator cannot know.
func ConsoleDocs() []apidoc.Route {
	return []apidoc.Route{
		{
			Method:      "POST",
			Path:        "/invitations/:token/accept",
			Tag:         "project",
			Summary:     "Accept invitation",
			Description: "Any signed-in member.",
			PathParams:  []apidoc.Param{{Name: "token"}},
			Responses:   []apidoc.Response{apidoc.OK("The result.", JoinedResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/invitations/:token/decline",
			Tag:         "project",
			Summary:     "Decline invitation",
			Description: "Any signed-in member.",
			PathParams:  []apidoc.Param{{Name: "token"}},
			Responses:   []apidoc.Response{apidoc.OK("The result.", DeclinedResponse{})},
		},
		{
			Method:      "GET",
			Path:        "/permissions",
			Tag:         "project",
			Summary:     "Catalog",
			Description: "Any signed-in member.",
			Responses:   []apidoc.Response{apidoc.OK("The result.", CatalogResponse{})},
		},
		{
			Method:      "GET",
			Path:        "/projects/",
			Tag:         "project",
			Summary:     "List",
			Description: "Any signed-in member.",
			Responses:   []apidoc.Response{apidoc.OK("The result.", ListResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/projects/",
			Tag:         "project",
			Summary:     "Create",
			Description: "Platform administrators, plus any signed-in account when the user_project_creation platform setting is on. It is off by default, so on a fresh installation this answers 403 to everybody else. GET /projects reports the same answer as can_create.",
			Request:     createInput{},
			Responses:   []apidoc.Response{apidoc.Created("The result.", ProjectResponse{})},
		},
		{
			Method:      "DELETE",
			Path:        "/projects/:id",
			Tag:         "project",
			Summary:     "Delete",
			Description: "Any signed-in member.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Responses:   []apidoc.Response{apidoc.NoContent},
		},
		{
			Method:      "GET",
			Path:        "/projects/:id",
			Tag:         "project",
			Summary:     "Get",
			Description: "Any signed-in member.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Responses:   []apidoc.Response{apidoc.OK("The result.", ProjectAccessResponse{})},
		},
		{
			Method:      "PATCH",
			Path:        "/projects/:id",
			Tag:         "project",
			Summary:     "Update",
			Description: "Any signed-in member.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Request:     updateInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", ProjectResponse{})},
		},
		{
			Method:      "GET",
			Path:        "/projects/:id/roles",
			Tag:         "project",
			Summary:     "List roles",
			Description: "Any signed-in member.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Responses:   []apidoc.Response{apidoc.OK("The result.", RoleListResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/projects/:id/roles",
			Tag:         "project",
			Summary:     "Create role",
			Description: "Any signed-in member.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Request:     roleInput{},
			Responses:   []apidoc.Response{apidoc.Created("The result.", RoleResponse{})},
		},
		{
			Method:      "DELETE",
			Path:        "/projects/:id/roles/:roleId",
			Tag:         "project",
			Summary:     "Delete role",
			Description: "Any signed-in member.",
			PathParams:  []apidoc.Param{{Name: "id"}, {Name: "roleId"}},
			Responses:   []apidoc.Response{apidoc.NoContent},
		},
		{
			Method:      "PATCH",
			Path:        "/projects/:id/roles/:roleId",
			Tag:         "project",
			Summary:     "Update role",
			Description: "Any signed-in member.",
			PathParams:  []apidoc.Param{{Name: "id"}, {Name: "roleId"}},
			Request:     roleInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", RoleResponse{})},
		},
		{
			Method:      "PUT",
			Path:        "/projects/:id/default-role",
			Tag:         "project",
			Summary:     "Set the default role",
			Description: "Any signed-in member.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Request:     defaultRoleInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", ProjectResponse{})},
		},
		{
			Method:      "GET",
			Path:        "/projects/:id/invitations",
			Tag:         "project",
			Summary:     "List invitations",
			Description: "Any signed-in member.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Responses:   []apidoc.Response{apidoc.OK("The result.", InvitationListResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/projects/:id/invitations",
			Tag:         "project",
			Summary:     "Create invitation",
			Description: "Any signed-in member.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Request:     inviteInput{},
			Responses:   []apidoc.Response{apidoc.Created("The result.", InvitationCreatedResponse{})},
		},
		{
			Method:      "DELETE",
			Path:        "/projects/:id/invitations/:invId",
			Tag:         "project",
			Summary:     "Delete invitation",
			Description: "Any signed-in member.",
			PathParams:  []apidoc.Param{{Name: "id"}, {Name: "invId"}},
			Responses:   []apidoc.Response{apidoc.NoContent},
		},
		{
			Method:      "GET",
			Path:        "/projects/:id/members",
			Tag:         "project",
			Summary:     "List members",
			Description: "Any signed-in member.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Responses:   []apidoc.Response{apidoc.OK("The result.", MemberListResponse{})},
		},
		{
			Method:      "POST",
			Path:        "/projects/:id/members",
			Tag:         "project",
			Summary:     "Add member",
			Description: "Any signed-in member.",
			PathParams:  []apidoc.Param{{Name: "id"}},
			Request:     memberInput{},
			Responses:   []apidoc.Response{apidoc.Created("The result.", MemberResponse{})},
		},
		{
			Method:      "DELETE",
			Path:        "/projects/:id/members/:userId",
			Tag:         "project",
			Summary:     "Remove member",
			Description: "Any signed-in member.",
			PathParams:  []apidoc.Param{{Name: "id"}, {Name: "userId"}},
			Responses:   []apidoc.Response{apidoc.NoContent},
		},
		{
			Method:      "PATCH",
			Path:        "/projects/:id/members/:userId",
			Tag:         "project",
			Summary:     "Update member",
			Description: "Any signed-in member.",
			PathParams:  []apidoc.Param{{Name: "id"}, {Name: "userId"}},
			Request:     memberRoleInput{},
			Responses:   []apidoc.Response{apidoc.OK("The result.", MemberResponse{})},
		},
	}
}
