"""Every /api/v1 route, one method each.

Generated by cmd/sdkgen from the same route metadata the OpenAPI
document is built from - do not edit. Run `task sdk-gen`.

A body is a plain dict and a result is whatever the API answered,
parsed. The schemas are in the OpenAPI document:

    mailyard export-api-spec --out openapi.yaml
"""

from typing import Any, Mapping, Optional
from urllib.parse import quote


def _esc(value: Any) -> str:
    """Percent-encode one path segment.

    safe="" so a separator is encoded rather than passed through: an id
    of "../users/x" would otherwise reroute the request to another
    endpoint, and one containing "?" or "#" would inject a query or
    truncate the path. The Go client escapes the same values - these
    two just interpolated them raw.
    """
    return quote(str(value), safe="")


class API:
    """The route surface. Reached as `client.api`."""

    def __init__(self, transport):
        self._t = transport

    def list_admin_api_keys(self, **query: Any) -> Any:
        "List platform credentials"
        return self._t.request("GET", "/admin/api-keys", body=None, query=query)

    def create_admin_api_key(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Mint a platform credential"
        return self._t.request("POST", "/admin/api-keys", body=body, query=query)

    def delete_admin_api_key(self, id, **query: Any) -> Any:
        "Delete a platform credential"
        return self._t.request("DELETE", f"/admin/api-keys/{_esc(id)}", body=None, query=query)

    def revoke_admin_api_key(self, id, **query: Any) -> Any:
        "Revoke a platform credential"
        return self._t.request("POST", f"/admin/api-keys/{_esc(id)}/revoke", body=None, query=query)

    def list_admin_certificates(self, **query: Any) -> Any:
        "List managed certificates and listener assignments"
        return self._t.request("GET", "/admin/certificates", body=None, query=query)

    def create_admin_certificate(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Upload a certificate and its private key"
        return self._t.request("POST", "/admin/certificates", body=body, query=query)

    def delete_admin_certificate(self, name, **query: Any) -> Any:
        "Delete a managed certificate"
        return self._t.request("DELETE", f"/admin/certificates/{_esc(name)}", body=None, query=query)

    def get_admin_certificate_pem(self, name, **query: Any) -> Any:
        "Read a certificate's public half"
        return self._t.request("GET", f"/admin/certificates/{_esc(name)}/pem", body=None, query=query)

    def get_admin_certificates_acme(self, **query: Any) -> Any:
        "What ACME is configured to do, and what it holds"
        return self._t.request("GET", "/admin/certificates/acme", body=None, query=query)

    def acme_order_admin_certificate(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Obtain a certificate for one configured host"
        return self._t.request("POST", "/admin/certificates/acme/order", body=body, query=query)

    def acme_renew_admin_certificate(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Discard what is cached for a host and order again"
        return self._t.request("POST", "/admin/certificates/acme/renew", body=body, query=query)

    def generate_admin_certificate(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Generate a certificate for a listener"
        return self._t.request("POST", "/admin/certificates/generate", body=body, query=query)

    def generate_ca_admin_certificate(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Generate a certificate authority"
        return self._t.request("POST", "/admin/certificates/generate-ca", body=body, query=query)

    def get_admin_certificates_system(self, **query: Any) -> Any:
        "List the certificates the installation holds for itself"
        return self._t.request("GET", "/admin/certificates/system", body=None, query=query)

    def list_admin_jobs(self, **query: Any) -> Any:
        "Jobs"
        return self._t.request("GET", "/admin/jobs", body=None, query=query)

    def run_admin_job(self, name, **query: Any) -> Any:
        "Run job"
        return self._t.request("POST", f"/admin/jobs/{_esc(name)}/run", body=None, query=query)

    def list_admin_oauth_providers(self, **query: Any) -> Any:
        "List"
        return self._t.request("GET", "/admin/oauth-providers", body=None, query=query)

    def create_admin_oauth_provider(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Create"
        return self._t.request("POST", "/admin/oauth-providers", body=body, query=query)

    def delete_admin_oauth_provider(self, id, **query: Any) -> Any:
        "Delete"
        return self._t.request("DELETE", f"/admin/oauth-providers/{_esc(id)}", body=None, query=query)

    def get_admin_oauth_provider(self, id, **query: Any) -> Any:
        "Get"
        return self._t.request("GET", f"/admin/oauth-providers/{_esc(id)}", body=None, query=query)

    def update_admin_oauth_provider(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Update"
        return self._t.request("PATCH", f"/admin/oauth-providers/{_esc(id)}", body=body, query=query)

    def test_admin_oauth_provider(self, id, **query: Any) -> Any:
        "Test"
        return self._t.request("POST", f"/admin/oauth-providers/{_esc(id)}/test", body=None, query=query)

    def list_admin_plans(self, **query: Any) -> Any:
        "List"
        return self._t.request("GET", "/admin/plans", body=None, query=query)

    def create_admin_plan(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Create"
        return self._t.request("POST", "/admin/plans", body=body, query=query)

    def delete_admin_plan(self, id, **query: Any) -> Any:
        "Delete"
        return self._t.request("DELETE", f"/admin/plans/{_esc(id)}", body=None, query=query)

    def update_admin_plan(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Update"
        return self._t.request("PATCH", f"/admin/plans/{_esc(id)}", body=body, query=query)

    def update_admin_project_plan(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Assign"
        return self._t.request("PATCH", f"/admin/projects/{_esc(id)}/plan", body=body, query=query)

    def list_admin_relay_nodes(self, **query: Any) -> Any:
        "List"
        return self._t.request("GET", "/admin/relay-nodes", body=None, query=query)

    def delete_admin_relay_node(self, id, **query: Any) -> Any:
        "Delete"
        return self._t.request("DELETE", f"/admin/relay-nodes/{_esc(id)}", body=None, query=query)

    def approve_admin_relay_node(self, id, **query: Any) -> Any:
        "Approve"
        return self._t.request("POST", f"/admin/relay-nodes/{_esc(id)}/approve", body=None, query=query)

    def suspend_admin_relay_node(self, id, **query: Any) -> Any:
        "Suspend"
        return self._t.request("POST", f"/admin/relay-nodes/{_esc(id)}/suspend", body=None, query=query)

    def delete_admin_relay_nodes_authority(self, **query: Any) -> Any:
        "Destroy the relay authority"
        return self._t.request("DELETE", "/admin/relay-nodes/authority", body=None, query=query)

    def list_admin_settings(self, **query: Any) -> Any:
        "List"
        return self._t.request("GET", "/admin/settings", body=None, query=query)

    def update_admin_settings(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Update"
        return self._t.request("PUT", "/admin/settings", body=body, query=query)

    def list_admin_shared_smtp_servers(self, **query: Any) -> Any:
        "List"
        return self._t.request("GET", "/admin/shared-smtp-servers", body=None, query=query)

    def create_admin_shared_smtp_server(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Create"
        return self._t.request("POST", "/admin/shared-smtp-servers", body=body, query=query)

    def delete_admin_shared_smtp_server(self, id, **query: Any) -> Any:
        "Delete"
        return self._t.request("DELETE", f"/admin/shared-smtp-servers/{_esc(id)}", body=None, query=query)

    def get_admin_shared_smtp_server(self, id, **query: Any) -> Any:
        "Get"
        return self._t.request("GET", f"/admin/shared-smtp-servers/{_esc(id)}", body=None, query=query)

    def update_admin_shared_smtp_server(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Update"
        return self._t.request("PATCH", f"/admin/shared-smtp-servers/{_esc(id)}", body=body, query=query)

    def test_admin_shared_smtp_server(self, id, **query: Any) -> Any:
        "Test"
        return self._t.request("POST", f"/admin/shared-smtp-servers/{_esc(id)}/test", body=None, query=query)

    def list_admin_system_mail(self, **query: Any) -> Any:
        "System mail status"
        return self._t.request("GET", "/admin/system-mail", body=None, query=query)

    def test_admin_system_mail(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "System mail test"
        return self._t.request("POST", "/admin/system-mail/test", body=body, query=query)

    def list_admin_users(self, **query: Any) -> Any:
        "List"
        return self._t.request("GET", "/admin/users", body=None, query=query)

    def create_admin_user(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Create"
        return self._t.request("POST", "/admin/users", body=body, query=query)

    def delete_admin_user(self, id, **query: Any) -> Any:
        "Delete"
        return self._t.request("DELETE", f"/admin/users/{_esc(id)}", body=None, query=query)

    def get_admin_user(self, id, **query: Any) -> Any:
        "Get"
        return self._t.request("GET", f"/admin/users/{_esc(id)}", body=None, query=query)

    def update_admin_user(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Update"
        return self._t.request("PATCH", f"/admin/users/{_esc(id)}", body=body, query=query)

    def delete_admin_user2fa(self, id, **query: Any) -> Any:
        "Reset t o t p"
        return self._t.request("DELETE", f"/admin/users/{_esc(id)}/2fa", body=None, query=query)

    def delete_admin_user_passkey(self, id, **query: Any) -> Any:
        "Reset passkeys"
        return self._t.request("DELETE", f"/admin/users/{_esc(id)}/passkeys", body=None, query=query)

    def list_admin_user_projects(self, id, **query: Any) -> Any:
        "Projects"
        return self._t.request("GET", f"/admin/users/{_esc(id)}/projects", body=None, query=query)

    def create_admin_user_revoke_session(self, id, **query: Any) -> Any:
        "Revoke sessions"
        return self._t.request("POST", f"/admin/users/{_esc(id)}/revoke-sessions", body=None, query=query)

    def list_analytics(self, **query: Any) -> Any:
        "Daily delivery trend and status breakdown Needs analytics:read."
        return self._t.request("GET", "/analytics", body=None, query=query)

    def list_api_keys(self, **query: Any) -> Any:
        "List"
        return self._t.request("GET", "/api-keys", body=None, query=query)

    def create_api_key(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Create"
        return self._t.request("POST", "/api-keys", body=body, query=query)

    def delete_api_key(self, id, **query: Any) -> Any:
        "Delete"
        return self._t.request("DELETE", f"/api-keys/{_esc(id)}", body=None, query=query)

    def revoke_api_key(self, id, **query: Any) -> Any:
        "Revoke"
        return self._t.request("POST", f"/api-keys/{_esc(id)}/revoke", body=None, query=query)

    def list_audit_log(self, **query: Any) -> Any:
        "Project log"
        return self._t.request("GET", "/audit-log", body=None, query=query)

    def get_audit_log(self, id, **query: Any) -> Any:
        "Project event"
        return self._t.request("GET", f"/audit-log/{_esc(id)}", body=None, query=query)

    def get_audit_log_export(self, **query: Any) -> Any:
        "Export the project log"
        return self._t.request("GET", "/audit-log/export", body=None, query=query)

    def delete_bounces(self, **query: Any) -> Any:
        "Delete the bounce reports for an address Needs bounces:delete."
        return self._t.request("DELETE", "/bounces", body=None, query=query)

    def list_bounces(self, **query: Any) -> Any:
        "List bounce reports Needs bounces:read."
        return self._t.request("GET", "/bounces", body=None, query=query)

    def list_campaigns(self, **query: Any) -> Any:
        "List"
        return self._t.request("GET", "/campaigns", body=None, query=query)

    def create_campaign(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Create"
        return self._t.request("POST", "/campaigns", body=body, query=query)

    def delete_campaign(self, id, **query: Any) -> Any:
        "Delete"
        return self._t.request("DELETE", f"/campaigns/{_esc(id)}", body=None, query=query)

    def get_campaign(self, id, **query: Any) -> Any:
        "Get"
        return self._t.request("GET", f"/campaigns/{_esc(id)}", body=None, query=query)

    def update_campaign(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Update"
        return self._t.request("PATCH", f"/campaigns/{_esc(id)}", body=body, query=query)

    def list_campaign_analytics(self, id, **query: Any) -> Any:
        "Analytics"
        return self._t.request("GET", f"/campaigns/{_esc(id)}/analytics", body=None, query=query)

    def cancel_campaign(self, id, **query: Any) -> Any:
        "Cancel"
        return self._t.request("POST", f"/campaigns/{_esc(id)}/cancel", body=None, query=query)

    def duplicate_campaign(self, id, **query: Any) -> Any:
        "Duplicate"
        return self._t.request("POST", f"/campaigns/{_esc(id)}/duplicate", body=None, query=query)

    def list_campaign_messages(self, id, **query: Any) -> Any:
        "Messages"
        return self._t.request("GET", f"/campaigns/{_esc(id)}/messages", body=None, query=query)

    def pause_campaign(self, id, **query: Any) -> Any:
        "Pause"
        return self._t.request("POST", f"/campaigns/{_esc(id)}/pause", body=None, query=query)

    def resume_campaign(self, id, **query: Any) -> Any:
        "Resume"
        return self._t.request("POST", f"/campaigns/{_esc(id)}/resume", body=None, query=query)

    def send_campaign(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Send"
        return self._t.request("POST", f"/campaigns/{_esc(id)}/send", body=body, query=query)

    def delete_contacts(self, **query: Any) -> Any:
        "Delete contacts idle since a date Needs contacts:delete."
        return self._t.request("DELETE", "/contacts", body=None, query=query)

    def list_contacts(self, **query: Any) -> Any:
        "Addresses this project has delivered to Needs contacts:read."
        return self._t.request("GET", "/contacts", body=None, query=query)

    def delete_contact(self, id, **query: Any) -> Any:
        "Delete one contact Needs contacts:delete."
        return self._t.request("DELETE", f"/contacts/{_esc(id)}", body=None, query=query)

    def get_contact(self, id, **query: Any) -> Any:
        "One contact Needs contacts:read."
        return self._t.request("GET", f"/contacts/{_esc(id)}", body=None, query=query)

    def list_dashboard_stats(self, **query: Any) -> Any:
        "Aggregate counts for a dashboard Needs analytics:read."
        return self._t.request("GET", "/dashboard/stats", body=None, query=query)

    def create_data_delete_contact(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Delete contacts"
        return self._t.request("POST", "/data/delete-contacts", body=body, query=query)

    def create_data_delete_email_log(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Delete email logs"
        return self._t.request("POST", "/data/delete-email-logs", body=body, query=query)

    def get_data_export(self, **query: Any) -> Any:
        "Export every record of the key's project Needs data:read."
        return self._t.request("GET", "/data/export", body=None, query=query)

    def list_domains(self, **query: Any) -> Any:
        "List"
        return self._t.request("GET", "/domains", body=None, query=query)

    def create_domain(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Create"
        return self._t.request("POST", "/domains", body=body, query=query)

    def delete_domain(self, id, **query: Any) -> Any:
        "Delete"
        return self._t.request("DELETE", f"/domains/{_esc(id)}", body=None, query=query)

    def get_domain(self, id, **query: Any) -> Any:
        "Get"
        return self._t.request("GET", f"/domains/{_esc(id)}", body=None, query=query)

    def verify_domain(self, id, **query: Any) -> Any:
        "Verify"
        return self._t.request("POST", f"/domains/{_esc(id)}/verify", body=None, query=query)

    def list_emails(self, **query: Any) -> Any:
        "List sent and queued emails Needs emails:read."
        return self._t.request("GET", "/emails", body=None, query=query)

    def get_email(self, id, **query: Any) -> Any:
        "One email with its full delivery record Needs emails:read."
        return self._t.request("GET", f"/emails/{_esc(id)}", body=None, query=query)

    def get_email_attachment(self, id, idx, **query: Any) -> bytes:
        "Attachment"
        return self._t.request("GET", f"/emails/{_esc(id)}/attachments/{_esc(idx)}", body=None, query=query, raw=True)

    def retry_email(self, id, **query: Any) -> Any:
        "Requeue a failed email Needs emails:write."
        return self._t.request("POST", f"/emails/{_esc(id)}/retry", body=None, query=query)

    def list_email_status(self, id, **query: Any) -> Any:
        "Delivery status only Needs emails:read."
        return self._t.request("GET", f"/emails/{_esc(id)}/status", body=None, query=query)

    def list_email_tracked_links(self, id, **query: Any) -> Any:
        "Original destinations behind the click redirects Needs emails:read."
        return self._t.request("GET", f"/emails/{_esc(id)}/tracked-links", body=None, query=query)

    def batch_email(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Queue up to 100 emails in one call Needs emails:write."
        return self._t.request("POST", "/emails/batch", body=body, query=query)

    def list_emails_limits(self, **query: Any) -> Any:
        "What a send may carry on this installation Needs emails:read."
        return self._t.request("GET", "/emails/limits", body=None, query=query)

    def preview_email(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Render a template without sending Needs emails:read."
        return self._t.request("POST", "/emails/preview", body=body, query=query)

    def send_email(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Queue one email Needs emails:write."
        return self._t.request("POST", "/emails/send", body=body, query=query)

    def send_template_email(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Render a stored template and queue the result Needs emails:write."
        return self._t.request("POST", "/emails/send-template", body=body, query=query)

    def list_emails_stats(self, **query: Any) -> Any:
        "Count emails by delivery status Needs emails:read."
        return self._t.request("GET", "/emails/stats", body=None, query=query)

    def verify_email(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Judge whether an address is worth sending to Needs emails:read."
        return self._t.request("POST", "/emails/verify", body=body, query=query)

    def list_inbound_emails(self, **query: Any) -> Any:
        "List mail received by the MX listener Needs inbound:read."
        return self._t.request("GET", "/inbound-emails", body=None, query=query)

    def delete_inbound_email(self, id, **query: Any) -> Any:
        "Delete"
        return self._t.request("DELETE", f"/inbound-emails/{_esc(id)}", body=None, query=query)

    def get_inbound_email(self, id, **query: Any) -> Any:
        "One received message Needs inbound:read."
        return self._t.request("GET", f"/inbound-emails/{_esc(id)}", body=None, query=query)

    def get_inbound_email_attachment(self, id, idx, **query: Any) -> bytes:
        "Attachment"
        return self._t.request("GET", f"/inbound-emails/{_esc(id)}/attachments/{_esc(idx)}", body=None, query=query, raw=True)

    def get_inbound_email_raw(self, id, **query: Any) -> bytes:
        "Raw"
        return self._t.request("GET", f"/inbound-emails/{_esc(id)}/raw", body=None, query=query, raw=True)

    def retry_inbound_email(self, id, **query: Any) -> Any:
        "Retry"
        return self._t.request("POST", f"/inbound-emails/{_esc(id)}/retry", body=None, query=query)

    def list_inbound_emails_stats(self, **query: Any) -> Any:
        "Count received mail by status Needs inbound:read."
        return self._t.request("GET", "/inbound-emails/stats", body=None, query=query)

    def accept_invitation(self, token, **query: Any) -> Any:
        "Accept invitation"
        return self._t.request("POST", f"/invitations/{_esc(token)}/accept", body=None, query=query)

    def decline_invitation(self, token, **query: Any) -> Any:
        "Decline invitation"
        return self._t.request("POST", f"/invitations/{_esc(token)}/decline", body=None, query=query)

    def list_languages(self, **query: Any) -> Any:
        "List"
        return self._t.request("GET", "/languages", body=None, query=query)

    def create_language(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Create"
        return self._t.request("POST", "/languages", body=body, query=query)

    def delete_language(self, id, **query: Any) -> Any:
        "Delete"
        return self._t.request("DELETE", f"/languages/{_esc(id)}", body=None, query=query)

    def update_language(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Update"
        return self._t.request("PUT", f"/languages/{_esc(id)}", body=body, query=query)

    def list_my_relay_nodes(self, **query: Any) -> Any:
        "List mine"
        return self._t.request("GET", "/my/relay-nodes", body=None, query=query)

    def delete_my_relay_node(self, id, **query: Any) -> Any:
        "Delete mine"
        return self._t.request("DELETE", f"/my/relay-nodes/{_esc(id)}", body=None, query=query)

    def relay_nodes_approve_my(self, id, **query: Any) -> Any:
        "Approve mine"
        return self._t.request("POST", f"/my/relay-nodes/{_esc(id)}/approve", body=None, query=query)

    def relay_nodes_suspend_my(self, id, **query: Any) -> Any:
        "Suspend mine"
        return self._t.request("POST", f"/my/relay-nodes/{_esc(id)}/suspend", body=None, query=query)

    def list_notifications(self, **query: Any) -> Any:
        "List"
        return self._t.request("GET", "/notifications", body=None, query=query)

    def delete_notification(self, id, **query: Any) -> Any:
        "Delete"
        return self._t.request("DELETE", f"/notifications/{_esc(id)}", body=None, query=query)

    def read_notification(self, id, **query: Any) -> Any:
        "Mark read"
        return self._t.request("POST", f"/notifications/{_esc(id)}/read", body=None, query=query)

    def read_all_notification(self, **query: Any) -> Any:
        "Mark all read"
        return self._t.request("POST", "/notifications/read-all", body=None, query=query)

    def get_notifications_unread(self, **query: Any) -> Any:
        "Unread"
        return self._t.request("GET", "/notifications/unread", body=None, query=query)

    def list_permissions(self, **query: Any) -> Any:
        "Catalog"
        return self._t.request("GET", "/permissions", body=None, query=query)

    def list_projects(self, **query: Any) -> Any:
        "List"
        return self._t.request("GET", "/projects", body=None, query=query)

    def create_project(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Create"
        return self._t.request("POST", "/projects", body=body, query=query)

    def delete_project(self, id, **query: Any) -> Any:
        "Delete"
        return self._t.request("DELETE", f"/projects/{_esc(id)}", body=None, query=query)

    def get_project(self, id, **query: Any) -> Any:
        "Get"
        return self._t.request("GET", f"/projects/{_esc(id)}", body=None, query=query)

    def update_project(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Update"
        return self._t.request("PATCH", f"/projects/{_esc(id)}", body=body, query=query)

    def update_project_default_role(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Set the default role"
        return self._t.request("PUT", f"/projects/{_esc(id)}/default-role", body=body, query=query)

    def list_project_invitations(self, id, **query: Any) -> Any:
        "List invitations"
        return self._t.request("GET", f"/projects/{_esc(id)}/invitations", body=None, query=query)

    def create_project_invitation(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Create invitation"
        return self._t.request("POST", f"/projects/{_esc(id)}/invitations", body=body, query=query)

    def delete_project_invitation(self, id, inv_id, **query: Any) -> Any:
        "Delete invitation"
        return self._t.request("DELETE", f"/projects/{_esc(id)}/invitations/{_esc(inv_id)}", body=None, query=query)

    def list_project_members(self, id, **query: Any) -> Any:
        "List members"
        return self._t.request("GET", f"/projects/{_esc(id)}/members", body=None, query=query)

    def create_project_member(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Add member"
        return self._t.request("POST", f"/projects/{_esc(id)}/members", body=body, query=query)

    def delete_project_member(self, id, user_id, **query: Any) -> Any:
        "Remove member"
        return self._t.request("DELETE", f"/projects/{_esc(id)}/members/{_esc(user_id)}", body=None, query=query)

    def update_project_member(self, id, user_id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Update member"
        return self._t.request("PATCH", f"/projects/{_esc(id)}/members/{_esc(user_id)}", body=body, query=query)

    def list_project_roles(self, id, **query: Any) -> Any:
        "List roles"
        return self._t.request("GET", f"/projects/{_esc(id)}/roles", body=None, query=query)

    def create_project_role(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Create role"
        return self._t.request("POST", f"/projects/{_esc(id)}/roles", body=body, query=query)

    def delete_project_role(self, id, role_id, **query: Any) -> Any:
        "Delete role"
        return self._t.request("DELETE", f"/projects/{_esc(id)}/roles/{_esc(role_id)}", body=None, query=query)

    def update_project_role(self, id, role_id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Update role"
        return self._t.request("PATCH", f"/projects/{_esc(id)}/roles/{_esc(role_id)}", body=body, query=query)

    def list_sandbox(self, **query: Any) -> Any:
        "List"
        return self._t.request("GET", "/sandbox", body=None, query=query)

    def delete_sandbox(self, id, **query: Any) -> Any:
        "Delete"
        return self._t.request("DELETE", f"/sandbox/{_esc(id)}", body=None, query=query)

    def get_sandbox(self, id, **query: Any) -> Any:
        "Get"
        return self._t.request("GET", f"/sandbox/{_esc(id)}", body=None, query=query)

    def get_sandbox_attachment(self, id, idx, **query: Any) -> bytes:
        "Attachment"
        return self._t.request("GET", f"/sandbox/{_esc(id)}/attachments/{_esc(idx)}", body=None, query=query, raw=True)

    def get_sandbox_raw(self, id, **query: Any) -> bytes:
        "Raw"
        return self._t.request("GET", f"/sandbox/{_esc(id)}/raw", body=None, query=query, raw=True)

    def clear_sandbox(self, **query: Any) -> Any:
        "Clear"
        return self._t.request("POST", "/sandbox/clear", body=None, query=query)

    def list_sandbox_credentials(self, **query: Any) -> Any:
        "List credentials"
        return self._t.request("GET", "/sandbox/credentials", body=None, query=query)

    def create_sandbox_credential(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Create credential"
        return self._t.request("POST", "/sandbox/credentials", body=body, query=query)

    def credentials_revoke_sandbox(self, id, **query: Any) -> Any:
        "Revoke credential"
        return self._t.request("POST", f"/sandbox/credentials/{_esc(id)}/revoke", body=None, query=query)

    def get_sandbox_info(self, **query: Any) -> Any:
        "Info"
        return self._t.request("GET", "/sandbox/info", body=None, query=query)

    def list_senders(self, **query: Any) -> Any:
        "List"
        return self._t.request("GET", "/senders", body=None, query=query)

    def create_sender(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Create"
        return self._t.request("POST", "/senders", body=body, query=query)

    def delete_sender(self, id, **query: Any) -> Any:
        "Delete"
        return self._t.request("DELETE", f"/senders/{_esc(id)}", body=None, query=query)

    def list_smtp_credentials(self, **query: Any) -> Any:
        "List"
        return self._t.request("GET", "/smtp-credentials", body=None, query=query)

    def create_smtp_credential(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Create"
        return self._t.request("POST", "/smtp-credentials", body=body, query=query)

    def delete_smtp_credential(self, id, **query: Any) -> Any:
        "Delete"
        return self._t.request("DELETE", f"/smtp-credentials/{_esc(id)}", body=None, query=query)

    def revoke_smtp_credential(self, id, **query: Any) -> Any:
        "Revoke"
        return self._t.request("POST", f"/smtp-credentials/{_esc(id)}/revoke", body=None, query=query)

    def list_smtp_server_groups(self, **query: Any) -> Any:
        "List"
        return self._t.request("GET", "/smtp-server-groups", body=None, query=query)

    def create_smtp_server_group(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Create"
        return self._t.request("POST", "/smtp-server-groups", body=body, query=query)

    def delete_smtp_server_group(self, id, **query: Any) -> Any:
        "Delete"
        return self._t.request("DELETE", f"/smtp-server-groups/{_esc(id)}", body=None, query=query)

    def get_smtp_server_group(self, id, **query: Any) -> Any:
        "Get"
        return self._t.request("GET", f"/smtp-server-groups/{_esc(id)}", body=None, query=query)

    def update_smtp_server_group(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Update"
        return self._t.request("PATCH", f"/smtp-server-groups/{_esc(id)}", body=body, query=query)

    def list_smtp_servers(self, **query: Any) -> Any:
        "List"
        return self._t.request("GET", "/smtp-servers", body=None, query=query)

    def create_smtp_server(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Create"
        return self._t.request("POST", "/smtp-servers", body=body, query=query)

    def delete_smtp_server(self, id, **query: Any) -> Any:
        "Delete"
        return self._t.request("DELETE", f"/smtp-servers/{_esc(id)}", body=None, query=query)

    def get_smtp_server(self, id, **query: Any) -> Any:
        "Get"
        return self._t.request("GET", f"/smtp-servers/{_esc(id)}", body=None, query=query)

    def update_smtp_server(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Update"
        return self._t.request("PATCH", f"/smtp-servers/{_esc(id)}", body=body, query=query)

    def disable_smtp_server(self, id, **query: Any) -> Any:
        "Disable"
        return self._t.request("POST", f"/smtp-servers/{_esc(id)}/disable", body=None, query=query)

    def enable_smtp_server(self, id, **query: Any) -> Any:
        "Enable"
        return self._t.request("POST", f"/smtp-servers/{_esc(id)}/enable", body=None, query=query)

    def test_smtp_server(self, id, **query: Any) -> Any:
        "Test"
        return self._t.request("POST", f"/smtp-servers/{_esc(id)}/test", body=None, query=query)

    def list_stylesheets(self, **query: Any) -> Any:
        "List"
        return self._t.request("GET", "/stylesheets", body=None, query=query)

    def create_stylesheet(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Create"
        return self._t.request("POST", "/stylesheets", body=body, query=query)

    def delete_stylesheet(self, id, **query: Any) -> Any:
        "Delete"
        return self._t.request("DELETE", f"/stylesheets/{_esc(id)}", body=None, query=query)

    def get_stylesheet(self, id, **query: Any) -> Any:
        "Get"
        return self._t.request("GET", f"/stylesheets/{_esc(id)}", body=None, query=query)

    def update_stylesheet(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Update"
        return self._t.request("PUT", f"/stylesheets/{_esc(id)}", body=body, query=query)

    def list_subscriber_lists(self, **query: Any) -> Any:
        "List"
        return self._t.request("GET", "/subscriber-lists", body=None, query=query)

    def create_subscriber_list(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Create"
        return self._t.request("POST", "/subscriber-lists", body=body, query=query)

    def delete_subscriber_list(self, id, **query: Any) -> Any:
        "Delete"
        return self._t.request("DELETE", f"/subscriber-lists/{_esc(id)}", body=None, query=query)

    def get_subscriber_list(self, id, **query: Any) -> Any:
        "Get"
        return self._t.request("GET", f"/subscriber-lists/{_esc(id)}", body=None, query=query)

    def update_subscriber_list(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Update"
        return self._t.request("PATCH", f"/subscriber-lists/{_esc(id)}", body=body, query=query)

    def list_subscriber_list_members(self, id, **query: Any) -> Any:
        "List members"
        return self._t.request("GET", f"/subscriber-lists/{_esc(id)}/members", body=None, query=query)

    def create_subscriber_list_member(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Add member"
        return self._t.request("POST", f"/subscriber-lists/{_esc(id)}/members", body=body, query=query)

    def delete_subscriber_list_member(self, id, subscriber_id, **query: Any) -> Any:
        "Remove member"
        return self._t.request("DELETE", f"/subscriber-lists/{_esc(id)}/members/{_esc(subscriber_id)}", body=None, query=query)

    def resubscribe_subscriber_list(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Re-add an address that had opted out Needs subscribers:write."
        return self._t.request("POST", f"/subscriber-lists/{_esc(id)}/resubscribe", body=body, query=query)

    def unsubscribe_subscriber_list(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Remove an address from a list Needs subscribers:write."
        return self._t.request("POST", f"/subscriber-lists/{_esc(id)}/unsubscribe", body=body, query=query)

    def preview_segment_subscriber_list(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Preview segment"
        return self._t.request("POST", "/subscriber-lists/preview-segment", body=body, query=query)

    def subscribe_subscriber_list(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Add an address to a static list Needs subscribers:write."
        return self._t.request("POST", "/subscriber-lists/subscribe", body=body, query=query)

    def list_subscribers(self, **query: Any) -> Any:
        "List"
        return self._t.request("GET", "/subscribers", body=None, query=query)

    def create_subscriber(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Create"
        return self._t.request("POST", "/subscribers", body=body, query=query)

    def delete_subscriber(self, id, **query: Any) -> Any:
        "Delete"
        return self._t.request("DELETE", f"/subscribers/{_esc(id)}", body=None, query=query)

    def get_subscriber(self, id, **query: Any) -> Any:
        "Get"
        return self._t.request("GET", f"/subscribers/{_esc(id)}", body=None, query=query)

    def update_subscriber(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Update"
        return self._t.request("PATCH", f"/subscribers/{_esc(id)}", body=body, query=query)

    def import_subscriber(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Import"
        return self._t.request("POST", "/subscribers/import", body=body, query=query)

    def import_csv_subscriber(self, **query: Any) -> Any:
        "Import CSV"
        return self._t.request("POST", "/subscribers/import/csv", body=None, query=query)

    def delete_suppressions(self, **query: Any) -> Any:
        "Unblock an address Needs suppressions:delete."
        return self._t.request("DELETE", "/suppressions", body=None, query=query)

    def list_suppressions(self, **query: Any) -> Any:
        "List blocked addresses Needs suppressions:read."
        return self._t.request("GET", "/suppressions", body=None, query=query)

    def create_suppression(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Block an address Needs suppressions:write."
        return self._t.request("POST", "/suppressions", body=body, query=query)

    def list_templates(self, **query: Any) -> Any:
        "List templates Needs templates:read."
        return self._t.request("GET", "/templates", body=None, query=query)

    def create_template(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Create"
        return self._t.request("POST", "/templates", body=body, query=query)

    def delete_template(self, id, **query: Any) -> Any:
        "Delete"
        return self._t.request("DELETE", f"/templates/{_esc(id)}", body=None, query=query)

    def get_template(self, id, **query: Any) -> Any:
        "One template with its version history Needs templates:read."
        return self._t.request("GET", f"/templates/{_esc(id)}", body=None, query=query)

    def update_template(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Update"
        return self._t.request("PATCH", f"/templates/{_esc(id)}", body=body, query=query)

    def activate_template(self, id, version_id, **query: Any) -> Any:
        "Activate"
        return self._t.request("POST", f"/templates/{_esc(id)}/activate/{_esc(version_id)}", body=None, query=query)

    def list_template_attachments(self, id, **query: Any) -> Any:
        "List attachments"
        return self._t.request("GET", f"/templates/{_esc(id)}/attachments", body=None, query=query)

    def create_template_attachment(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Upload attachment"
        return self._t.request("POST", f"/templates/{_esc(id)}/attachments", body=body, query=query)

    def delete_template_attachment(self, id, att_id, **query: Any) -> Any:
        "Delete attachment"
        return self._t.request("DELETE", f"/templates/{_esc(id)}/attachments/{_esc(att_id)}", body=None, query=query)

    def get_template_attachments_download(self, id, att_id, **query: Any) -> bytes:
        "Download attachment"
        return self._t.request("GET", f"/templates/{_esc(id)}/attachments/{_esc(att_id)}/download", body=None, query=query, raw=True)

    def get_template_export(self, id, **query: Any) -> Any:
        "Export"
        return self._t.request("GET", f"/templates/{_esc(id)}/export", body=None, query=query)

    def delete_template_localization(self, id, localization_id, **query: Any) -> Any:
        "Delete localization"
        return self._t.request("DELETE", f"/templates/{_esc(id)}/localizations/{_esc(localization_id)}", body=None, query=query)

    def send_test_template(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Send test"
        return self._t.request("POST", f"/templates/{_esc(id)}/send-test", body=body, query=query)

    def list_template_versions(self, id, **query: Any) -> Any:
        "List versions"
        return self._t.request("GET", f"/templates/{_esc(id)}/versions", body=None, query=query)

    def create_template_version(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Create version"
        return self._t.request("POST", f"/templates/{_esc(id)}/versions", body=body, query=query)

    def delete_template_version(self, id, version_id, **query: Any) -> Any:
        "Delete version"
        return self._t.request("DELETE", f"/templates/{_esc(id)}/versions/{_esc(version_id)}", body=None, query=query)

    def update_template_version(self, id, version_id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Update version"
        return self._t.request("PATCH", f"/templates/{_esc(id)}/versions/{_esc(version_id)}", body=body, query=query)

    def list_template_versions_localizations(self, id, version_id, **query: Any) -> Any:
        "List localizations"
        return self._t.request("GET", f"/templates/{_esc(id)}/versions/{_esc(version_id)}/localizations", body=None, query=query)

    def update_template_versions_localization(self, id, version_id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Put localization"
        return self._t.request("PUT", f"/templates/{_esc(id)}/versions/{_esc(version_id)}/localizations", body=body, query=query)

    def versions_preview_template(self, id, version_id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Preview version"
        return self._t.request("POST", f"/templates/{_esc(id)}/versions/{_esc(version_id)}/preview", body=body, query=query)

    def import_template(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Import"
        return self._t.request("POST", "/templates/import", body=body, query=query)

    def preview_template(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Preview"
        return self._t.request("POST", "/templates/preview", body=body, query=query)

    def list_unsubscribe_lists(self, **query: Any) -> Any:
        "List transactional opt-out scopes Needs suppressions:read."
        return self._t.request("GET", "/unsubscribe-lists", body=None, query=query)

    def create_unsubscribe_list(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Create"
        return self._t.request("POST", "/unsubscribe-lists", body=body, query=query)

    def delete_unsubscribe_list(self, id, **query: Any) -> Any:
        "Delete"
        return self._t.request("DELETE", f"/unsubscribe-lists/{_esc(id)}", body=None, query=query)

    def get_unsubscribe_list(self, id, **query: Any) -> Any:
        "One opt-out scope Needs suppressions:read."
        return self._t.request("GET", f"/unsubscribe-lists/{_esc(id)}", body=None, query=query)

    def update_unsubscribe_list(self, id, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Update"
        return self._t.request("PATCH", f"/unsubscribe-lists/{_esc(id)}", body=body, query=query)

    def list_usage(self, **query: Any) -> Any:
        "Usage"
        return self._t.request("GET", "/usage", body=None, query=query)

    def list_webhooks(self, **query: Any) -> Any:
        "List outgoing webhooks Needs webhooks:read."
        return self._t.request("GET", "/webhooks", body=None, query=query)

    def create_webhook(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Create an outgoing webhook Needs webhooks:write."
        return self._t.request("POST", "/webhooks", body=body, query=query)

    def delete_webhook(self, id, **query: Any) -> Any:
        "Delete a webhook Needs webhooks:delete."
        return self._t.request("DELETE", f"/webhooks/{_esc(id)}", body=None, query=query)

    def list_webhook_deliveries(self, id, **query: Any) -> Any:
        "Delivery log of one webhook Needs webhooks:read."
        return self._t.request("GET", f"/webhooks/{_esc(id)}/deliveries", body=None, query=query)

    def enable_webhook(self, id, **query: Any) -> Any:
        "Re-enable a disabled webhook Needs webhooks:write."
        return self._t.request("POST", f"/webhooks/{_esc(id)}/enable", body=None, query=query)

    def bounce_webhook(self, body: Optional[Mapping[str, Any]] = None, **query: Any) -> Any:
        "Ingest a bounce report Needs bounces:write."
        return self._t.request("POST", "/webhooks/bounce", body=body, query=query)

